import { stableProductionId } from "./ProductionDeterminism";
import { AdapterBackedProductionExecutionDurableStorage } from "./ProductionExecutionDurableStorage";
import { validateProductionExecutionDurableLease } from "./ProductionExecutionDurableLease";
import type { ProductionExecutionDurableRecord } from "@/types/productionExecutionDurableStorage";
import type { ProductionExecutionIdempotencyReservationRequest } from "@/types/productionExecutionIdempotency";
import type { ProductionExecutionPersistenceAdapter, ProductionExecutionPersistenceErrorCode } from "@/types/productionExecutionPersistence";
import { type ProductionExecutionClaimAbandonRequest, type ProductionExecutionClaimConflict, type ProductionExecutionClaimCoordinationPlan, type ProductionExecutionClaimOperationResult, type ProductionExecutionClaimPolicy, type ProductionExecutionClaimPreflightResult, type ProductionExecutionClaimReasonCode, type ProductionExecutionClaimRecoveryAssessment, type ProductionExecutionClaimReleaseRequest, type ProductionExecutionClaimRequest, type ProductionExecutionDurableClaimRecord } from "@/types/productionExecutionDurableClaim";

const terminal=new Set(["succeeded","failed","cancelled","partially-succeeded"]);
export const defaultProductionExecutionClaimPolicy:ProductionExecutionClaimPolicy={policyVersion:"production-execution-claim-v1",reservationTtlSeconds:300};

export class AdapterBackedProductionExecutionClaimService{
 private readonly storage:AdapterBackedProductionExecutionDurableStorage;
 constructor(private readonly adapter:ProductionExecutionPersistenceAdapter){this.storage=new AdapterBackedProductionExecutionDurableStorage(adapter)}

 async preflight(request:ProductionExecutionClaimRequest,policy:ProductionExecutionClaimPolicy):Promise<ProductionExecutionClaimPreflightResult>{
  const coordination=plan(request);const fail=(code:ProductionExecutionClaimReasonCode,conflict?:ProductionExecutionClaimConflict):ProductionExecutionClaimPreflightResult=>({schemaVersion:"1",ok:false,reasonCode:code,coordination,expectedClaimVersion:request.expectedClaimVersion,actualClaimVersion:0,evidence:[`reason:${code}`],...(conflict?{conflict}:{})});
  if(!validRequest(request)||!validPolicy(policy))return fail(request.recordId.includes("..")||request.claimId.includes("..")?"CLAIM_TRAVERSAL_DENIED":"CLAIM_PATH_INVALID");
  const reservation=await this.adapter.read("reservation",request.reservationId);if(reservation.status!=="found")return fail(reservation.status==="not-found"?"CLAIM_RESERVATION_CONFLICT":mapPersistence(reservation.errorCode));
  const reservationReason=validateReservation(reservation.value,request,policy);if(reservationReason)return fail(reservationReason);
  const durable=await this.storage.read(request.recordId);if(!durable.record)return fail(mapStorage(durable.reasonCode));const record=durable.record;
  const recordReason=validateRecordBindings(record,request);if(recordReason)return fail(recordReason);if(terminal.has(record.state))return fail("CLAIM_TERMINAL_STATE");if(record.recovery)return fail("CLAIM_RECOVERY_REQUIRED");
  const lease=record.durableLease;if(!lease)return fail("CLAIM_LEASE_MISMATCH");if(!validateProductionExecutionDurableLease(lease))return fail("CLAIM_INTEGRITY_MISMATCH");if(lease.status!=="active")return fail("CLAIM_LEASE_MISMATCH");if(Date.parse(request.evaluatedAt)>=Date.parse(lease.expiresAt))return fail("CLAIM_LEASE_EXPIRED");
  if(lease.identity.workerId!==request.workerId)return fail("CLAIM_OWNER_MISMATCH");if(lease.identity.workerSessionId!==request.workerSessionId)return fail("CLAIM_SESSION_MISMATCH");if(lease.identity.leaseId!==request.leaseId)return fail("CLAIM_LEASE_MISMATCH");
  if(request.expectedReservationVersion!==1)return fail(request.expectedReservationVersion<1?"CLAIM_STALE_WRITE":"CLAIM_VERSION_CONFLICT",versionConflict(request.expectedReservationVersion,1));if(request.expectedIdempotencyVersion!==record.recordVersion)return fail(request.expectedIdempotencyVersion<record.recordVersion?"CLAIM_STALE_WRITE":"CLAIM_VERSION_CONFLICT",versionConflict(request.expectedIdempotencyVersion,record.recordVersion));if(request.expectedLeaseVersion!==lease.version)return fail(request.expectedLeaseVersion<lease.version?"CLAIM_STALE_WRITE":"CLAIM_VERSION_CONFLICT",versionConflict(request.expectedLeaseVersion,lease.version));
  const latest=await this.latestClaim(request.claimId);if(latest.error)return fail(latest.error);if(latest.claim){if(claimReplay(latest.claim,request))return{schemaVersion:"1",ok:true,reasonCode:"CLAIM_REPLAYED",claim:latest.claim,coordination,expectedClaimVersion:request.expectedClaimVersion,actualClaimVersion:latest.claim.claimVersion,evidence:["reason:CLAIM_REPLAYED"]};if(latest.claim.identity.claimId===request.claimId&&latest.claim.state==="active")return fail("CLAIM_ID_CONFLICT",conflict("claim-id","CLAIM_ID_CONFLICT"));if(latest.claim.state!=="active")return fail("CLAIM_TRANSITION_INVALID",conflict("state","CLAIM_TRANSITION_INVALID"));}
  const active=await this.activeClaimForRecord(request.recordId);if(active&&active.identity.claimId!==request.claimId)return fail("CLAIM_ID_CONFLICT",conflict("claim-id","CLAIM_ID_CONFLICT"));if(request.expectedClaimVersion!==0)return fail(request.expectedClaimVersion<0?"CLAIM_STALE_WRITE":"CLAIM_VERSION_CONFLICT",versionConflict(request.expectedClaimVersion,0));
  return{schemaVersion:"1",ok:true,reasonCode:"CLAIM_ACTIVE",coordination,expectedClaimVersion:0,actualClaimVersion:0,evidence:["reason:CLAIM_ACTIVE","preflight:write-free"]};
 }

 async acquireExecutionClaim(request:ProductionExecutionClaimRequest,policy:ProductionExecutionClaimPolicy):Promise<ProductionExecutionClaimOperationResult>{const preflight=await this.preflight(request,policy);if(!preflight.ok)return operation(preflight.reasonCode,preflight.coordination,{conflict:preflight.conflict,diagnostics:preflight.diagnostics});if(preflight.reasonCode==="CLAIM_REPLAYED"&&preflight.claim)return operation("CLAIM_REPLAYED",preflight.coordination,{ok:true,decision:"replayed",claim:preflight.claim});const claim=buildClaim(request);return this.writeClaim(claim,preflight.coordination,"acquired","CLAIM_ACQUIRED");}

 async releaseExecutionClaim(request:ProductionExecutionClaimReleaseRequest):Promise<ProductionExecutionClaimOperationResult>{return this.closeClaim(request,"released");}
 async abandonExecutionClaim(request:ProductionExecutionClaimAbandonRequest):Promise<ProductionExecutionClaimOperationResult>{const latest=await this.latestClaim(request.claimId);const coordination=releasePlan(request);if(latest.error)return operation(latest.error,coordination);if(!latest.claim)return operation("CLAIM_NOT_FOUND",coordination);const record=await this.storage.read(latest.claim.identity.recordId);const lease=record.record?.durableLease;const allowed=request.reason==="coordination-recovery"||Boolean(lease&&Date.parse(request.evaluatedAt)>=Date.parse(lease.expiresAt));if(!allowed)return operation("CLAIM_ABANDON_NOT_ALLOWED",coordination);return this.closeClaim(request,"abandoned");}

  async evaluateExecutionClaimRecovery(claimId:string,evaluatedAt:string):Promise<ProductionExecutionClaimRecoveryAssessment>{if(!safe(claimId)||!date(evaluatedAt))return assessment("indeterminate",claimId.includes("..")?"CLAIM_TRAVERSAL_DENIED":"CLAIM_INDETERMINATE",true);const latest=await this.latestClaim(claimId);if(latest.error)return assessment(latest.error==="CLAIM_INTEGRITY_MISMATCH"?"integrity-mismatch":"indeterminate",latest.error,true);if(!latest.claim)return assessment("no-claim","CLAIM_NOT_FOUND",false);const claim=latest.claim;if(!validClaim(claim))return assessment("integrity-mismatch","CLAIM_INTEGRITY_MISMATCH",true,claim);if(claim.evidence.includes("coordination:partial-commit"))return assessment("partial-coordination","CLAIM_PARTIAL_COMMIT",true,claim);const reservation=await this.adapter.read("reservation",claim.identity.reservationId);if(reservation.status!=="found")return assessment("missing-linked-record","CLAIM_RECOVERY_REQUIRED",true,claim);const durable=await this.storage.read(claim.identity.recordId);if(!durable.record)return assessment("missing-linked-record",mapStorage(durable.reasonCode),true,claim);const record=durable.record,lease=record.durableLease;if(!lease)return assessment("missing-linked-record","CLAIM_RECOVERY_REQUIRED",true,claim);if(record.recordVersion!==claim.binding.idempotencyVersion||lease.version!==claim.binding.leaseVersion)return assessment("stale-linked-version","CLAIM_STALE_WRITE",true,claim);if(claim.state!=="active")return assessment("replay-safe",claim.state==="released"?"CLAIM_RELEASED":"CLAIM_ABANDONED",false,claim);if(lease.status==="released")return assessment("released-lease","CLAIM_RECOVERY_REQUIRED",true,claim);if(Date.parse(evaluatedAt)>=Date.parse(lease.expiresAt))return assessment("expired-lease","CLAIM_RECOVERY_REQUIRED",true,claim);return assessment("valid-active","CLAIM_ACTIVE",false,claim);}

 private async closeClaim(request:ProductionExecutionClaimReleaseRequest,state:"released"|"abandoned"):Promise<ProductionExecutionClaimOperationResult>{const coordination=releasePlan(request);if(!safe(request.claimId)||!safe(request.workerId)||!safe(request.workerSessionId)||!safe(request.leaseId)||!date(request.evaluatedAt))return operation(request.claimId.includes("..")?"CLAIM_TRAVERSAL_DENIED":"CLAIM_PATH_INVALID",coordination);const latest=await this.latestClaim(request.claimId);if(latest.error)return operation(latest.error,coordination);const claim=latest.claim;if(!claim)return operation("CLAIM_NOT_FOUND",coordination);if(claim.state===state&&claim.updatedAt===request.evaluatedAt)return operation("CLAIM_REPLAYED",coordination,{ok:true,decision:"replayed",claim});if(claim.identity.workerId!==request.workerId)return operation("CLAIM_OWNER_MISMATCH",coordination);if(claim.identity.workerSessionId!==request.workerSessionId)return operation("CLAIM_SESSION_MISMATCH",coordination);if(claim.identity.leaseId!==request.leaseId)return operation("CLAIM_LEASE_MISMATCH",coordination);if(request.expectedClaimVersion!==claim.claimVersion)return operation(request.expectedClaimVersion<claim.claimVersion?"CLAIM_STALE_WRITE":"CLAIM_VERSION_CONFLICT",coordination);if(claim.state!=="active")return operation(state==="released"?"CLAIM_RELEASE_NOT_ALLOWED":"CLAIM_ABANDON_NOT_ALLOWED",coordination);const next=withIntegrity({...claim,state,claimVersion:claim.claimVersion+1,updatedAt:request.evaluatedAt,...(state==="released"?{releasedAt:request.evaluatedAt}:{abandonedAt:request.evaluatedAt})});return this.writeClaim(next,coordination,state,state==="released"?"CLAIM_RELEASED":"CLAIM_ABANDONED");}
 private async writeClaim(claim:ProductionExecutionDurableClaimRecord,coordination:ProductionExecutionClaimCoordinationPlan,decision:"acquired"|"released"|"abandoned",code:ProductionExecutionClaimReasonCode){const write=await this.adapter.write("claim",`${claim.identity.claimId}-v${claim.claimVersion}`,claim);if(!write.ok)return operation(write.errorCode==="PERSISTENCE_EXISTING_RECORD_CONFLICT"?"CLAIM_NEXT_VERSION_CONFLICT":mapWrite(write.errorCode),coordination,{diagnostics:write.diagnostics});const read=await this.adapter.read("claim",`${claim.identity.claimId}-v${claim.claimVersion}`);if(read.status!=="found"||!validClaim(read.value))return operation("CLAIM_READBACK_FAILED",coordination);return operation(code,coordination,{ok:true,decision,claim:read.value});}
 private async latestClaim(claimId:string):Promise<{claim?:ProductionExecutionDurableClaimRecord;error?:ProductionExecutionClaimReasonCode}>{const listed=await this.adapter.listKeys("claim");if(!listed.ok)return{error:"CLAIM_INDETERMINATE"};const expression=new RegExp(`^${escape(claimId)}-v([1-9][0-9]*)$`),versions=listed.keys.map(key=>({key,match:expression.exec(key)})).filter(item=>item.match).sort((a,b)=>Number(b.match![1])-Number(a.match![1]));if(!versions.length)return{};const read=await this.adapter.read("claim",versions[0].key);if(read.status!=="found")return{error:read.status==="not-found"?"CLAIM_NOT_FOUND":mapPersistence(read.errorCode)};return validClaim(read.value)?{claim:read.value}:{error:"CLAIM_INTEGRITY_MISMATCH"};}
 private async activeClaimForRecord(recordId:string){const listed=await this.adapter.listKeys("claim");if(!listed.ok)return undefined;const latest=new Map<string,{version:number;key:string}>();for(const key of listed.keys){const match=/^(.+)-v([1-9][0-9]*)$/.exec(key);if(match&&(!latest.has(match[1])||latest.get(match[1])!.version<Number(match[2])))latest.set(match[1],{version:Number(match[2]),key})}for(const item of latest.values()){const read=await this.adapter.read("claim",item.key);if(read.status==="found"&&read.value.state==="active"&&read.value.identity.recordId===recordId)return read.value}return undefined;}
}

function buildClaim(request:ProductionExecutionClaimRequest){const identity={claimId:request.claimId,recordId:request.recordId,reservationId:request.reservationId,requestId:request.requestId,idempotencyKey:request.idempotencyKey,executionFingerprint:request.executionFingerprint,workerId:request.workerId,workerSessionId:request.workerSessionId,leaseId:request.leaseId};const binding={reservationVersion:request.expectedReservationVersion,idempotencyVersion:request.expectedIdempotencyVersion,leaseVersion:request.expectedLeaseVersion,bindingFingerprint:stableProductionId("claim-binding",identity)};return withIntegrity({schemaVersion:"1",storageVersion:"1",identity,binding,ownership:{ownerFingerprint:stableProductionId("claim-owner",{workerId:request.workerId,workerSessionId:request.workerSessionId,leaseId:request.leaseId}),reservationEvidence:`reservation:${stableProductionId("claim-reservation",{reservationId:request.reservationId,version:request.expectedReservationVersion})}`,idempotencyEvidence:`idempotency:${stableProductionId("claim-idempotency",{recordId:request.recordId,version:request.expectedIdempotencyVersion})}`,leaseEvidence:`lease:${stableProductionId("claim-lease",{leaseId:request.leaseId,version:request.expectedLeaseVersion})}`},state:"active",claimVersion:1,acquiredAt:request.evaluatedAt,updatedAt:request.evaluatedAt,evidence:["coordination:single-record","transactional:false","rollback:explicit-recovery"]});}
function withIntegrity(value:Omit<ProductionExecutionDurableClaimRecord,"integrity">|ProductionExecutionDurableClaimRecord):ProductionExecutionDurableClaimRecord{const{integrity:unused,...body}=value as ProductionExecutionDurableClaimRecord;void unused;return{...body,integrity:{algorithm:"stable-production-id-v1",fingerprint:stableProductionId("durable-claim-integrity",body)}};}
export function validateProductionExecutionDurableClaim(value:unknown){return validClaim(value)}
export function classifyProductionExecutionClaimArtifact(value:unknown):ProductionExecutionClaimReasonCode{if(!value||typeof value!=="object"||Array.isArray(value))return"CLAIM_RECORD_MALFORMED";const record=value as Record<string,unknown>;if(record.schemaVersion!=="1")return"CLAIM_SCHEMA_UNSUPPORTED";if(record.storageVersion!=="1")return"CLAIM_STORAGE_VERSION_UNSUPPORTED";return validClaim(value)?"CLAIM_ACTIVE":"CLAIM_INTEGRITY_MISMATCH";}
function validClaim(value:unknown):value is ProductionExecutionDurableClaimRecord{if(!value||typeof value!=="object"||Array.isArray(value))return false;const claim=value as ProductionExecutionDurableClaimRecord;if(claim.schemaVersion!=="1"||claim.storageVersion!=="1"||!safe(claim.identity?.claimId)||!safe(claim.identity?.recordId)||!safe(claim.identity?.reservationId)||![claim.identity.requestId,claim.identity.idempotencyKey,claim.identity.executionFingerprint].every(nonempty)||!safe(claim.identity.workerId)||!safe(claim.identity.workerSessionId)||!safe(claim.identity.leaseId)||!Number.isInteger(claim.binding?.reservationVersion)||!Number.isInteger(claim.binding?.idempotencyVersion)||!Number.isInteger(claim.binding?.leaseVersion)||!nonempty(claim.binding?.bindingFingerprint)||!["active","released","abandoned"].includes(claim.state)||!Number.isInteger(claim.claimVersion)||claim.claimVersion<1||!date(claim.acquiredAt)||!date(claim.updatedAt)||!claim.integrity)return false;return withIntegrity(claim).integrity.fingerprint===claim.integrity.fingerprint;}
function validateReservation(reservation:ProductionExecutionIdempotencyReservationRequest,request:ProductionExecutionClaimRequest,policy:ProductionExecutionClaimPolicy):ProductionExecutionClaimReasonCode|undefined{if(reservation.identity.identityFingerprint!==request.reservationId)return"CLAIM_RESERVATION_CONFLICT";if(reservation.identity.requestId!==request.requestId)return"CLAIM_REQUEST_CONFLICT";if(reservation.identity.idempotencyKey!==request.idempotencyKey)return"CLAIM_IDEMPOTENCY_CONFLICT";if(reservation.identity.executionFingerprint!==request.executionFingerprint)return"CLAIM_FINGERPRINT_CONFLICT";if(Date.parse(request.evaluatedAt)>=Date.parse(reservation.requestedAt)+policy.reservationTtlSeconds*1000)return"CLAIM_RESERVATION_EXPIRED";return undefined;}
function validateRecordBindings(record:ProductionExecutionDurableRecord,request:ProductionExecutionClaimRequest):ProductionExecutionClaimReasonCode|undefined{if(record.requestId!==request.requestId)return"CLAIM_REQUEST_CONFLICT";if(record.idempotencyKey!==request.idempotencyKey)return"CLAIM_IDEMPOTENCY_CONFLICT";if(record.executionFingerprint!==request.executionFingerprint)return"CLAIM_FINGERPRINT_CONFLICT";if(record.identityFingerprint!==request.reservationId)return"CLAIM_RESERVATION_CONFLICT";return undefined;}
function claimReplay(claim:ProductionExecutionDurableClaimRecord,request:ProductionExecutionClaimRequest){return claim.state==="active"&&claim.identity.claimId===request.claimId&&claim.identity.recordId===request.recordId&&claim.identity.reservationId===request.reservationId&&claim.identity.requestId===request.requestId&&claim.identity.idempotencyKey===request.idempotencyKey&&claim.identity.executionFingerprint===request.executionFingerprint&&claim.identity.workerId===request.workerId&&claim.identity.workerSessionId===request.workerSessionId&&claim.identity.leaseId===request.leaseId&&claim.binding.reservationVersion===request.expectedReservationVersion&&claim.binding.idempotencyVersion===request.expectedIdempotencyVersion&&claim.binding.leaseVersion===request.expectedLeaseVersion;}
function plan(request:ProductionExecutionClaimRequest):ProductionExecutionClaimCoordinationPlan{return{snapshotId:stableProductionId("claim-preflight",request),writeFreePreflight:true,intendedWrites:["claim-coordination-record"],commitOrder:["claim-coordination-record"],transactional:false,implicitRollback:false};}function releasePlan(request:ProductionExecutionClaimReleaseRequest){return{snapshotId:stableProductionId("claim-release",request),writeFreePreflight:true,intendedWrites:["claim-coordination-record"],commitOrder:["claim-coordination-record"],transactional:false,implicitRollback:false}as const;}
function operation(code:ProductionExecutionClaimReasonCode,coordination:ProductionExecutionClaimCoordinationPlan,over:Partial<ProductionExecutionClaimOperationResult>={}):ProductionExecutionClaimOperationResult{return{schemaVersion:"1",ok:false,decision:code==="CLAIM_RECOVERY_REQUIRED"?"recovery-required":code==="CLAIM_INDETERMINATE"?"indeterminate":"deny",reasonCode:code,coordination,partialCommit:false,compensationRequired:false,evidence:[`reason:${code}`],...over};}
function assessment(classification:ProductionExecutionClaimRecoveryAssessment["classification"],reasonCode:ProductionExecutionClaimReasonCode,recoveryRequired:boolean,claim?:ProductionExecutionDurableClaimRecord):ProductionExecutionClaimRecoveryAssessment{return{schemaVersion:"1",classification,reasonCode,writeFree:true,recoveryRequired,...(claim?{claim}:{}),evidence:[`reason:${reasonCode}`]};}
function conflict(category:ProductionExecutionClaimConflict["category"],reasonCode:ProductionExecutionClaimReasonCode):ProductionExecutionClaimConflict{return{category,reasonCode};}function versionConflict(expectedVersion:number,actualVersion:number):ProductionExecutionClaimConflict{return{category:"version",reasonCode:expectedVersion<actualVersion?"CLAIM_STALE_WRITE":"CLAIM_VERSION_CONFLICT",expectedVersion,actualVersion};}
function validRequest(request:ProductionExecutionClaimRequest){return[safe(request.claimId),safe(request.recordId),safe(request.reservationId),safe(request.workerId),safe(request.workerSessionId),safe(request.leaseId),nonempty(request.requestId),nonempty(request.idempotencyKey),nonempty(request.executionFingerprint),date(request.evaluatedAt),Number.isInteger(request.expectedReservationVersion),Number.isInteger(request.expectedIdempotencyVersion),Number.isInteger(request.expectedLeaseVersion),Number.isInteger(request.expectedClaimVersion)].every(Boolean);}function validPolicy(policy:ProductionExecutionClaimPolicy){return nonempty(policy.policyVersion)&&Number.isInteger(policy.reservationTtlSeconds)&&policy.reservationTtlSeconds>0;}
function mapStorage(code:string):ProductionExecutionClaimReasonCode{return code==="DURABLE_STORAGE_RECORD_MISSING"?"CLAIM_IDEMPOTENCY_CONFLICT":code==="DURABLE_STORAGE_TRAVERSAL_DENIED"?"CLAIM_TRAVERSAL_DENIED":code==="DURABLE_STORAGE_PATH_INVALID"?"CLAIM_PATH_INVALID":code.includes("INTEGRITY")||code.includes("CORRUPTION")?"CLAIM_INTEGRITY_MISMATCH":code==="DURABLE_STORAGE_RECOVERY_REQUIRED"?"CLAIM_RECOVERY_REQUIRED":"CLAIM_INDETERMINATE";}function mapPersistence(code:ProductionExecutionPersistenceErrorCode):ProductionExecutionClaimReasonCode{return code==="PERSISTENCE_SCHEMA_UNSUPPORTED"?"CLAIM_SCHEMA_UNSUPPORTED":code==="PERSISTENCE_RECORD_CORRUPT"?"CLAIM_INTEGRITY_MISMATCH":"CLAIM_INDETERMINATE";}function mapWrite(code:ProductionExecutionPersistenceErrorCode):ProductionExecutionClaimReasonCode{return code==="PERSISTENCE_COMMIT_FAILED"||code==="PERSISTENCE_TEMP_WRITE_FAILED"||code==="PERSISTENCE_TEMP_VALIDATION_FAILED"?"CLAIM_ATOMIC_COMMIT_FAILED":mapPersistence(code);}
function safe(value:string|undefined){return typeof value==="string"&&/^[a-z0-9](?:[a-z0-9_-]{0,100}[a-z0-9])?$/.test(value)&&!value.includes("..");}function nonempty(value:unknown){return typeof value==="string"&&value.length>0;}function date(value:string){const parsed=Date.parse(value);return Number.isFinite(parsed)&&new Date(parsed).toISOString()===value;}function escape(value:string){return value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
