import { stableProductionId } from "./ProductionDeterminism";
import { AdapterBackedProductionExecutionDurableStorage } from "./ProductionExecutionDurableStorage";
import type { ProductionExecutionDurableRecord } from "@/types/productionExecutionDurableStorage";
import type { ProductionExecutionPersistenceAdapter, ProductionExecutionPersistenceErrorCode } from "@/types/productionExecutionPersistence";
import { productionExecutionDurableLeaseSchemaVersion, type ProductionExecutionDurableLease, type ProductionExecutionDurableLeasePolicy, type ProductionExecutionDurableLeaseReasonCode, type ProductionExecutionDurableWorkerIdentity, type ProductionExecutionLeaseAcquisitionRequest, type ProductionExecutionLeaseEvaluationRequest, type ProductionExecutionLeaseEvaluationResult, type ProductionExecutionLeaseHeartbeatRequest, type ProductionExecutionLeaseOperationResult, type ProductionExecutionLeaseReleaseRequest, type ProductionExecutionLeaseTakeoverRequest, type ProductionExecutionWorkerSessionIdentity } from "@/types/productionExecutionDurableLease";

const terminal = new Set(["succeeded", "failed", "cancelled", "partially-succeeded"]);
export const defaultProductionExecutionDurableLeasePolicy: ProductionExecutionDurableLeasePolicy = { policyVersion:"production-execution-durable-lease-v1", reservationTtlSeconds:300, minimumLeaseDurationSeconds:1, maximumLeaseDurationSeconds:300, maximumRenewalWindowSeconds:300 };

export class AdapterBackedProductionExecutionDurableLeaseService {
  private readonly storage: AdapterBackedProductionExecutionDurableStorage;
  constructor(private readonly adapter: ProductionExecutionPersistenceAdapter) { this.storage = new AdapterBackedProductionExecutionDurableStorage(adapter); }

  async acquire(request: ProductionExecutionLeaseAcquisitionRequest, policy: ProductionExecutionDurableLeasePolicy): Promise<ProductionExecutionLeaseOperationResult> {
    const loaded = await this.load(request.recordId);
    if (!loaded.ok || !loaded.record) return loaded;
    const record = loaded.record, existing = record.durableLease;
    if (existing && acquisitionReplay(existing, request)) return result("LEASE_REPLAYED", { decision:"replayed", lease:existing, record, expectedVersion:request.expectedVersion, actualVersion:record.recordVersion });
    const common = validateMutation(record, request, policy); if (common) return common;
    if (terminal.has(record.state)) return denied("LEASE_TERMINAL_STATE", record, request.expectedVersion);
    if (reservationExpired(record, request.evaluatedAt, policy)) return denied("RESERVATION_EXPIRED", record, request.expectedVersion);
    const interval = validateInterval(request.acquiredAt, request.heartbeatAt, request.expiresAt, request.evaluatedAt, request.session.startedAt, policy); if (interval) return denied(interval, record, request.expectedVersion);
    if (existing?.status === "active" && Date.parse(request.evaluatedAt) < Date.parse(existing.expiresAt)) return denied(acquisitionConflict(existing, request), record, request.expectedVersion);
    if (existing) return denied("LEASE_TAKEOVER_NOT_ALLOWED", record, request.expectedVersion);
    const lease = buildLease(record, request, undefined);
    return this.commit(record, request.expectedVersion, request.evaluatedAt, lease, "acquired", "LEASE_ACQUIRED");
  }

  async heartbeat(request: ProductionExecutionLeaseHeartbeatRequest, policy: ProductionExecutionDurableLeasePolicy): Promise<ProductionExecutionLeaseOperationResult> {
    const loaded=await this.load(request.recordId);if(!loaded.ok||!loaded.record)return loaded;const record=loaded.record,lease=record.durableLease;
    if (!lease) return denied("LEASE_NOT_FOUND",record,request.expectedVersion);
    if (heartbeatReplay(lease,request)) return result("LEASE_REPLAYED",{decision:"replayed",lease,record,expectedVersion:request.expectedVersion,actualVersion:record.recordVersion});
    const common=validateMutation(record,request,policy);if(common)return common;if(terminal.has(record.state))return denied(record.state==="cancelled"?"LEASE_CANCELLED":"LEASE_TERMINAL_STATE",record,request.expectedVersion);
    const owner=ownershipReason(lease,request);if(owner)return denied(owner,record,request.expectedVersion);
    if(lease.status==="released")return denied("LEASE_RELEASED",record,request.expectedVersion);if(lease.status==="cancelled")return denied("LEASE_CANCELLED",record,request.expectedVersion);
    if(Date.parse(request.evaluatedAt)>=Date.parse(lease.expiresAt))return denied("LEASE_EXPIRED",record,request.expectedVersion);
    if(!date(request.heartbeatAt)||!date(request.expiresAt))return denied("LEASE_TIMESTAMP_INVALID",record,request.expectedVersion);
    if(Date.parse(request.heartbeatAt)<Date.parse(lease.heartbeatAt))return denied("LEASE_HEARTBEAT_STALE",record,request.expectedVersion);
    if(Date.parse(request.expiresAt)<=Date.parse(lease.expiresAt)||Date.parse(request.expiresAt)<=Date.parse(request.heartbeatAt)||Date.parse(request.expiresAt)-Date.parse(request.evaluatedAt)>policy.maximumRenewalWindowSeconds*1000)return denied("LEASE_RENEWAL_INVALID",record,request.expectedVersion);
    const next=withIntegrity({...lease,heartbeatAt:request.heartbeatAt,expiresAt:request.expiresAt,version:lease.version+1});
    return this.commit(record,request.expectedVersion,request.evaluatedAt,next,"renewed","LEASE_ACTIVE");
  }

  async release(request: ProductionExecutionLeaseReleaseRequest, policy: ProductionExecutionDurableLeasePolicy): Promise<ProductionExecutionLeaseOperationResult> {
    const loaded=await this.load(request.recordId);if(!loaded.ok||!loaded.record)return loaded;const record=loaded.record,lease=record.durableLease;
    if(!lease)return denied("LEASE_NOT_FOUND",record,request.expectedVersion);
    if(lease.status==="released"&&lease.releasedAt===request.releasedAt&&ownershipReason(lease,request)===undefined)return result("LEASE_REPLAYED",{decision:"replayed",lease,record,expectedVersion:request.expectedVersion,actualVersion:record.recordVersion});
    const common=validateMutation(record,request,policy);if(common)return common;const owner=ownershipReason(lease,request);if(owner)return denied(owner,record,request.expectedVersion);
    if(record.state==="cancelled"||lease.status==="cancelled")return denied("LEASE_CANCELLED",record,request.expectedVersion);if(lease.status==="released")return denied("LEASE_TRANSITION_INVALID",record,request.expectedVersion);
    if(!date(request.releasedAt)||Date.parse(request.releasedAt)<Date.parse(lease.heartbeatAt)||Date.parse(request.releasedAt)!==Date.parse(request.evaluatedAt))return denied("LEASE_TIMESTAMP_INVALID",record,request.expectedVersion);
    const next=withIntegrity({...lease,status:"released",releasedAt:request.releasedAt,version:lease.version+1});
    return this.commit(record,request.expectedVersion,request.evaluatedAt,next,"released","LEASE_RELEASED");
  }

  async evaluate(request: ProductionExecutionLeaseEvaluationRequest): Promise<ProductionExecutionLeaseEvaluationResult> {
    if(!safe(request.recordId))return evaluation("indeterminate",request.recordId.includes("..")?"LEASE_TRAVERSAL_DENIED":"LEASE_PATH_INVALID",false);if(!date(request.evaluatedAt))return evaluation("indeterminate","LEASE_INDETERMINATE",false);
    const read=await this.storage.read(request.recordId);if(!read.record)return evaluation("indeterminate",mapRead(read.reasonCode),false);const lease=read.record.durableLease;
    if(!lease)return evaluation("indeterminate","LEASE_NOT_FOUND",false);if(!validLease(lease))return evaluation("indeterminate","LEASE_INTEGRITY_MISMATCH",false);
    if(request.workerId&&request.workerId!==lease.identity.workerId)return evaluation("ownership-mismatch","LEASE_OWNER_MISMATCH",false,lease);
    if(request.workerSessionId&&request.workerSessionId!==lease.identity.workerSessionId)return evaluation("ownership-mismatch","LEASE_SESSION_MISMATCH",false,lease);
    if(request.leaseId&&request.leaseId!==lease.identity.leaseId)return evaluation("ownership-mismatch","LEASE_ID_CONFLICT",false,lease);
    if(lease.status==="released")return evaluation("released","LEASE_RELEASED",false,lease);if(lease.status==="cancelled")return evaluation("cancelled","LEASE_CANCELLED",false,lease);
    return Date.parse(request.evaluatedAt)>=Date.parse(lease.expiresAt)?evaluation("expired","LEASE_EXPIRED",true,lease):evaluation("active","LEASE_ACTIVE",false,lease);
  }

  async evaluateTakeover(request: ProductionExecutionLeaseEvaluationRequest): Promise<ProductionExecutionLeaseEvaluationResult> { const value=await this.evaluate(request);return value.state==="expired"?{...value,reasonCode:"LEASE_TAKEOVER_ALLOWED",takeoverAllowed:true,evidence:["reason:LEASE_TAKEOVER_ALLOWED"]}:{...value,reasonCode:"LEASE_TAKEOVER_NOT_ALLOWED",takeoverAllowed:false,evidence:["reason:LEASE_TAKEOVER_NOT_ALLOWED"]}; }

  async takeover(request: ProductionExecutionLeaseTakeoverRequest, policy: ProductionExecutionDurableLeasePolicy): Promise<ProductionExecutionLeaseOperationResult> {
    const loaded=await this.load(request.recordId);if(!loaded.ok||!loaded.record)return loaded;const record=loaded.record,previous=record.durableLease;if(!previous)return denied("LEASE_NOT_FOUND",record,request.expectedVersion);
    if(acquisitionReplay(previous,request))return result("LEASE_REPLAYED",{decision:"replayed",lease:previous,record,expectedVersion:request.expectedVersion,actualVersion:record.recordVersion});
    const common=validateMutation(record,request,policy);if(common)return common;if(terminal.has(record.state))return denied("LEASE_TERMINAL_STATE",record,request.expectedVersion);if(!validLease(previous))return denied("LEASE_INTEGRITY_MISMATCH",record,request.expectedVersion);
    if(previous.status!=="active"||Date.parse(request.evaluatedAt)<Date.parse(previous.expiresAt))return denied("LEASE_TAKEOVER_NOT_ALLOWED",record,request.expectedVersion);
    const interval=validateInterval(request.acquiredAt,request.heartbeatAt,request.expiresAt,request.evaluatedAt,request.session.startedAt,policy);if(interval)return denied(interval,record,request.expectedVersion);
    const lease=buildLease(record,request,previous.ownership.ownerFingerprint);return this.commit(record,request.expectedVersion,request.evaluatedAt,lease,"taken-over","LEASE_ACQUIRED");
  }

  private async load(recordId:string):Promise<ProductionExecutionLeaseOperationResult>{if(!safe(recordId))return result(recordId.includes("..")?"LEASE_TRAVERSAL_DENIED":"LEASE_PATH_INVALID");const read=await this.storage.read(recordId);if(!read.record)return result(mapRead(read.reasonCode));if(read.record.durableLease&&!validLease(read.record.durableLease))return denied("LEASE_INTEGRITY_MISMATCH",read.record);if(read.record.recovery&&!terminal.has(read.record.state))return denied("LEASE_RECOVERY_REQUIRED",read.record);return result("LEASE_ACTIVE",{ok:true,record:read.record,actualVersion:read.record.recordVersion});}
  private async commit(record:ProductionExecutionDurableRecord,expectedVersion:number,evaluatedAt:string,lease:ProductionExecutionDurableLease,decision:ProductionExecutionLeaseOperationResult["decision"],code:ProductionExecutionDurableLeaseReasonCode){const version=record.recordVersion+1;const next:ProductionExecutionDurableRecord={...record,durableLease:lease,recordVersion:version,updatedAt:evaluatedAt,integrity:{...record.integrity,version}};const validation=this.storage.validateRecord(next);if(!validation.ok)return denied("LEASE_INTEGRITY_MISMATCH",record,expectedVersion);const write=await this.adapter.write("idempotency",`${record.recordId}-v${version}`,next);if(!write.ok)return result(write.errorCode==="PERSISTENCE_EXISTING_RECORD_CONFLICT"?"LEASE_NEXT_VERSION_CONFLICT":mapWrite(write.errorCode),{record,expectedVersion,actualVersion:record.recordVersion,diagnostics:write.diagnostics});const readback=await this.adapter.read("idempotency",`${record.recordId}-v${version}`);if(readback.status!=="found")return result("LEASE_READBACK_FAILED",{record,expectedVersion,actualVersion:record.recordVersion});const persisted=readback.value as ProductionExecutionDurableRecord;if(!persisted.durableLease||!validLease(persisted.durableLease))return result("LEASE_READBACK_FAILED",{record,expectedVersion,actualVersion:record.recordVersion});return result(code,{ok:true,decision,lease:persisted.durableLease,record:persisted,expectedVersion,actualVersion:version});}
}

function validateMutation(record:ProductionExecutionDurableRecord,request:{expectedVersion:number;evaluatedAt:string;worker:ProductionExecutionDurableWorkerIdentity;session:ProductionExecutionWorkerSessionIdentity;leaseId:string},policy:ProductionExecutionDurableLeasePolicy){if(!date(request.evaluatedAt)||!validWorker(request.worker)||!validSession(request.session,request.worker)||!safe(request.leaseId)||!validPolicy(policy))return denied(!date(request.evaluatedAt)?"LEASE_TIMESTAMP_INVALID":"LEASE_RECORD_MALFORMED",record,request.expectedVersion);if(request.expectedVersion!==record.recordVersion)return denied(request.expectedVersion<record.recordVersion?"LEASE_STALE_WRITE":"LEASE_VERSION_CONFLICT",record,request.expectedVersion);return undefined;}
function validateInterval(acquiredAt:string,heartbeatAt:string,expiresAt:string,evaluatedAt:string,sessionStartedAt:string,policy:ProductionExecutionDurableLeasePolicy):ProductionExecutionDurableLeaseReasonCode|undefined{if(![acquiredAt,heartbeatAt,expiresAt,evaluatedAt,sessionStartedAt].every(date))return"LEASE_TIMESTAMP_INVALID";const acquired=Date.parse(acquiredAt),heartbeat=Date.parse(heartbeatAt),expires=Date.parse(expiresAt),evaluated=Date.parse(evaluatedAt),session=Date.parse(sessionStartedAt);if(session>acquired||acquired>heartbeat||heartbeat>evaluated||evaluated>=expires)return"LEASE_TIMESTAMP_INVALID";const duration=(expires-acquired)/1000;return duration<policy.minimumLeaseDurationSeconds||duration>policy.maximumLeaseDurationSeconds?"LEASE_INTERVAL_INVALID":undefined;}
function validWorker(worker:ProductionExecutionDurableWorkerIdentity){return worker.schemaVersion==="1"&&safe(worker.workerId)&&worker.workerType==="server"&&worker.identitySource==="trusted-server"&&worker.operationScope.length>0&&worker.operationScope.every(safeScope);}
function validSession(session:ProductionExecutionWorkerSessionIdentity,worker:ProductionExecutionDurableWorkerIdentity){return session.schemaVersion==="1"&&safe(session.workerSessionId)&&session.workerId===worker.workerId&&session.identitySource==="trusted-server"&&date(session.startedAt);}
function validPolicy(policy:ProductionExecutionDurableLeasePolicy){return Boolean(safeScope(policy.policyVersion)&&Number.isInteger(policy.reservationTtlSeconds)&&policy.reservationTtlSeconds>0&&Number.isInteger(policy.minimumLeaseDurationSeconds)&&policy.minimumLeaseDurationSeconds>0&&Number.isInteger(policy.maximumLeaseDurationSeconds)&&policy.maximumLeaseDurationSeconds>=policy.minimumLeaseDurationSeconds&&Number.isInteger(policy.maximumRenewalWindowSeconds)&&policy.maximumRenewalWindowSeconds>0);}
function reservationExpired(record:ProductionExecutionDurableRecord,evaluatedAt:string,policy:ProductionExecutionDurableLeasePolicy){return Date.parse(evaluatedAt)>=Date.parse(record.reservedAt??record.createdAt)+policy.reservationTtlSeconds*1000;}
function buildLease(record:ProductionExecutionDurableRecord,request:ProductionExecutionLeaseAcquisitionRequest|ProductionExecutionLeaseTakeoverRequest,previous?:string):ProductionExecutionDurableLease{const identity={leaseId:request.leaseId,workerId:request.worker.workerId,workerSessionId:request.session.workerSessionId,recordId:record.recordId,idempotencyKey:record.idempotencyKey,requestId:record.requestId,executionFingerprint:record.executionFingerprint};const ownerFingerprint=stableProductionId("lease-owner",identity);return withIntegrity({schemaVersion:"1",identity,status:"active",acquiredAt:request.acquiredAt,heartbeatAt:request.heartbeatAt,expiresAt:request.expiresAt,version:1,ownership:{ownerFingerprint,workerEvidence:`worker:${stableProductionId("worker",{workerId:request.worker.workerId,scope:request.worker.operationScope})}`,sessionEvidence:`session:${stableProductionId("session",{workerSessionId:request.session.workerSessionId,startedAt:request.session.startedAt})}`,...(previous?{previousOwnerFingerprint:previous}:{})}});}
function withIntegrity(lease:Omit<ProductionExecutionDurableLease,"integrity">|ProductionExecutionDurableLease):ProductionExecutionDurableLease{const {integrity:unused,...body}=lease as ProductionExecutionDurableLease;void unused;return{...body,integrity:{algorithm:"stable-production-id-v1",fingerprint:stableProductionId("durable-lease-integrity",body)}};}
export function validateProductionExecutionDurableLease(lease:ProductionExecutionDurableLease){return validLease(lease);}
function validLease(lease:ProductionExecutionDurableLease){if(lease.schemaVersion!=="1"||!safe(lease.identity.leaseId)||!safe(lease.identity.workerId)||!safe(lease.identity.workerSessionId)||!safe(lease.identity.recordId)||!lease.identity.idempotencyKey||!lease.identity.requestId||!lease.identity.executionFingerprint||!Number.isInteger(lease.version)||lease.version<1||!["active","released","cancelled"].includes(lease.status)||![lease.acquiredAt,lease.heartbeatAt,lease.expiresAt].every(date))return false;if(Date.parse(lease.acquiredAt)>Date.parse(lease.heartbeatAt)||Date.parse(lease.heartbeatAt)>=Date.parse(lease.expiresAt))return false;if(lease.status==="released"&&(!lease.releasedAt||!date(lease.releasedAt)))return false;if(lease.status==="cancelled"&&(!lease.cancelledAt||!date(lease.cancelledAt)))return false;const rebuilt=withIntegrity(lease);return lease.integrity.algorithm==="stable-production-id-v1"&&rebuilt.integrity.fingerprint===lease.integrity.fingerprint;}
function acquisitionReplay(lease:ProductionExecutionDurableLease,request:ProductionExecutionLeaseAcquisitionRequest|ProductionExecutionLeaseTakeoverRequest){return lease.status==="active"&&lease.identity.leaseId===request.leaseId&&lease.identity.workerId===request.worker.workerId&&lease.identity.workerSessionId===request.session.workerSessionId&&lease.acquiredAt===request.acquiredAt&&lease.heartbeatAt===request.heartbeatAt&&lease.expiresAt===request.expiresAt;}
function heartbeatReplay(lease:ProductionExecutionDurableLease,request:ProductionExecutionLeaseHeartbeatRequest){return lease.status==="active"&&!ownershipReason(lease,request)&&lease.heartbeatAt===request.heartbeatAt&&lease.expiresAt===request.expiresAt;}
function ownershipReason(lease:ProductionExecutionDurableLease,request:{worker:ProductionExecutionDurableWorkerIdentity;session:ProductionExecutionWorkerSessionIdentity;leaseId:string}){if(lease.identity.workerId!==request.worker.workerId)return"LEASE_OWNER_MISMATCH" as const;if(lease.identity.workerSessionId!==request.session.workerSessionId)return"LEASE_SESSION_MISMATCH" as const;if(lease.identity.leaseId!==request.leaseId)return"LEASE_ID_CONFLICT" as const;return undefined;}
function acquisitionConflict(lease:ProductionExecutionDurableLease,request:ProductionExecutionLeaseAcquisitionRequest){if(lease.identity.workerId!==request.worker.workerId)return"LEASE_OWNER_MISMATCH";if(lease.identity.workerSessionId!==request.session.workerSessionId)return"LEASE_SESSION_MISMATCH";if(lease.identity.leaseId!==request.leaseId)return"LEASE_ID_CONFLICT";return"LEASE_OWNERSHIP_CONFLICT";}
function denied(code:ProductionExecutionDurableLeaseReasonCode,record?:ProductionExecutionDurableRecord,expectedVersion?:number){return result(code,{record,expectedVersion,actualVersion:record?.recordVersion,conflict:["LEASE_OWNER_MISMATCH","LEASE_SESSION_MISMATCH","LEASE_ID_CONFLICT","LEASE_OWNERSHIP_CONFLICT","LEASE_VERSION_CONFLICT","LEASE_STALE_WRITE","LEASE_NEXT_VERSION_CONFLICT"].includes(code)?{category:code.includes("SESSION")?"session":code.includes("VERSION")||code.includes("STALE")?"version":code.includes("ID")?"lease-id":"owner",expectedVersion,actualVersion:record?.recordVersion,publicCode:code}:undefined});}
function result(code:ProductionExecutionDurableLeaseReasonCode,over:Partial<ProductionExecutionLeaseOperationResult>={}):ProductionExecutionLeaseOperationResult{return{schemaVersion:productionExecutionDurableLeaseSchemaVersion,ok:false,decision:code==="LEASE_INDETERMINATE"?"indeterminate":"deny",reasonCode:code,reason:code.replaceAll("_"," ").toLowerCase(),evidence:[`reason:${code}`],...over};}
function evaluation(state:ProductionExecutionLeaseEvaluationResult["state"],reasonCode:ProductionExecutionDurableLeaseReasonCode,takeoverAllowed:boolean,lease?:ProductionExecutionDurableLease):ProductionExecutionLeaseEvaluationResult{return{schemaVersion:"1",state,reasonCode,takeoverAllowed,...(lease?{lease}:{}),evidence:[`reason:${reasonCode}`]};}
function mapRead(code:string):ProductionExecutionDurableLeaseReasonCode{return code==="DURABLE_STORAGE_RECORD_MISSING"?"LEASE_NOT_FOUND":code==="DURABLE_STORAGE_TRAVERSAL_DENIED"?"LEASE_TRAVERSAL_DENIED":code==="DURABLE_STORAGE_PATH_INVALID"?"LEASE_PATH_INVALID":code.includes("INTEGRITY")||code.includes("CORRUPTION")?"LEASE_INTEGRITY_MISMATCH":code==="DURABLE_STORAGE_RECOVERY_REQUIRED"?"LEASE_RECOVERY_REQUIRED":"LEASE_INDETERMINATE";}
function mapWrite(code:ProductionExecutionPersistenceErrorCode):ProductionExecutionDurableLeaseReasonCode{return code==="PERSISTENCE_RECORD_CORRUPT"?"LEASE_INTEGRITY_MISMATCH":code==="PERSISTENCE_COMMIT_FAILED"||code==="PERSISTENCE_TEMP_WRITE_FAILED"||code==="PERSISTENCE_TEMP_VALIDATION_FAILED"?"LEASE_ATOMIC_COMMIT_FAILED":"LEASE_INDETERMINATE";}
function safe(value:string){return/^[a-z0-9](?:[a-z0-9_-]{0,100}[a-z0-9])?$/.test(value)&&!value.includes("..");}function safeScope(value:string){return/^[a-z0-9](?:[a-z0-9._:-]{0,198}[a-z0-9])?$/.test(value)&&!value.includes("..");}function date(value:string){const parsed=Date.parse(value);return Number.isFinite(parsed)&&new Date(parsed).toISOString()===value;}
