import { ProjectReader } from "@/lib/projects/ProjectReader";
import { PipelineJobManager } from "@/lib/pipeline/PipelineJobManager";
import { PipelineRunner } from "@/lib/pipeline/PipelineRunner";
import { stableProductionId } from "./ProductionDeterminism";
import { buildProductionPipelineExecutionIdentity } from "./ProductionPipelineExecutionIdentity";
export { buildProductionPipelineExecutionIdentity } from "./ProductionPipelineExecutionIdentity";
import { ProductionPipelineExecutionAdapter, type ProductionPipelineExecutionContext } from "./ProductionPipelineExecutionAdapter";
import { ProductionExecutionFilePersistenceAdapter } from "./ProductionExecutionPersistence";
import { AdapterBackedProductionExecutionDurableStorage, defaultProductionExecutionDurableStoragePolicy } from "./ProductionExecutionDurableStorage";
import { AdapterBackedProductionExecutionDurableLeaseService, defaultProductionExecutionDurableLeasePolicy } from "./ProductionExecutionDurableLease";
import { AdapterBackedProductionExecutionClaimService, defaultProductionExecutionClaimPolicy } from "./ProductionExecutionDurableClaim";
import { buildProductionExecutionIdempotencyIdentity, defaultProductionExecutionIdempotencyPolicy } from "./ProductionExecutionIdempotency";
import { defaultProductionExecutionAttemptPolicy } from "./ProductionExecutionDurableAttempt";
import { settlePendingSuccessfulProductionPipelineExecutions, settleSuccessfulProductionPipelineExecution } from "./ProductionPipelineTerminalSettlement";
import type { ProductionWorkerLifecycle } from "./ProductionWorkerLifecycle";
import type { ProductionExecutionAuthorizationResult } from "@/types/productionExecutionAuthorization";import type { ProductionExecutionConfirmationValidationResult } from "@/types/productionExecutionConfirmation";import type { ProductionExecutionIdempotencyRecord, ProductionExecutionIdempotencyReservationRequest } from "@/types/productionExecutionIdempotency";import type { ProductionExecutionWorkerExecutionRequest } from "@/types/productionExecutionWorker";

const ttlSeconds=31_536_000,workerId="pipeline-worker",sessionId="pipeline-session-v1";
export function configureProductionPipelineExecution(options:{enabled?:boolean;lifecycle?:ProductionWorkerLifecycle}={}):boolean{const enabled=options.enabled??process.env.ATOLYE_DURABLE_PIPELINE_EXECUTION==="enabled";PipelineRunner.configureContinuationAdmission(options.lifecycle);if(!enabled){PipelineRunner.configureDurableExecution();return false}if(!options.lifecycle){PipelineRunner.configureDurableExecution();return false}PipelineRunner.configureDurableExecution(createProductionPipelineExecutionExecutor(options.lifecycle));return true}
export function createProductionPipelineExecutionExecutor(lifecycle:ProductionWorkerLifecycle){return{execute:(context:ProductionPipelineExecutionContext,handler:()=>Promise<boolean>)=>execute(context,handler,lifecycle)}}
async function execute(context:ProductionPipelineExecutionContext,handler:()=>Promise<boolean>,lifecycle:ProductionWorkerLifecycle){return lifecycle.execute(async()=>{const predecessorAdapter=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:`${ProjectReader.getProjectFolder(context.projectSlug)}/production-execution`}),predecessors=await settlePendingSuccessfulProductionPipelineExecutions(predecessorAdapter);if(!predecessors.ok)throw new Error(`Pipeline predecessor terminal settlement failed: ${predecessors.reasonCode}`);const prepared=await prepareProductionPipelineExecution(context);return new ProductionPipelineExecutionAdapter(prepared.adapter,()=>prepared.request,result=>settleSuccessfulProductionPipelineExecution(prepared.settlement,result)).execute(context,handler)})}
export async function prepareProductionPipelineExecution(context:ProductionPipelineExecutionContext){const job=await PipelineJobManager.getJobForStageReadOnly(context.projectSlug,context.stage),attemptNumber=job?.attempts??0,jobId=job?.id??`${context.projectSlug}-${context.stage}`,anchor=job?.updatedAt??job?.createdAt??new Date().toISOString(),now=new Date().toISOString(),durable=buildProductionPipelineExecutionIdentity(context,{id:jobId,attempts:attemptNumber}),{core,requestId,idempotencyKey,executionFingerprint,claimId,leaseId,attemptId,recordId,runningEventId,terminalEventId}=durable,operation=`pipeline.stage.${context.runType}`,authorization:ProductionExecutionAuthorizationResult={schemaVersion:"1",decisionId:stableProductionId("pipeline-authorization",core),decision:"allow",authorized:true,reasonCode:"AUTHORIZED",reason:"trusted pipeline composition",evaluatedAt:anchor,requestId,idempotencyKey,executionFingerprint,actorId:"pipeline-system",actorType:"system",projectSlug:context.projectSlug,operation,action:"retry-stage",stage:context.stage,requiredCapabilities:[],grantedCapabilities:[],missingCapabilities:[],policyVersion:"pipeline-durable-v1",risk:"high",requiresConfirmation:true,requiredConfirmationLevel:"high",evidence:["source:pipeline-composition"]},confirmation:ProductionExecutionConfirmationValidationResult={schemaVersion:"1",decision:"valid",valid:true,reasonCode:"CONFIRMATION_VALID",reason:"trusted pipeline composition",evaluatedAt:anchor,confirmationId:stableProductionId("pipeline-confirmation",core),confirmationRequestId:stableProductionId("pipeline-confirmation-request",core),authorizationDecisionId:stableProductionId("pipeline-authorization",core),requestId,idempotencyKey,actorId:"pipeline-system",projectSlug:context.projectSlug,operation,action:"retry-stage",stage:context.stage,riskLevel:"high",requiredConfirmationLevel:"high",providedConfirmationLevel:"high",bindingMatches:true,bindingFingerprint:stableProductionId("pipeline-confirmation-binding",core),expired:false,singleUse:true,consumed:false,policyVersion:"pipeline-durable-v1",evidence:["source:pipeline-composition"]};
 const idPolicy={...defaultProductionExecutionIdempotencyPolicy,enabled:true,reservationTtlSeconds:ttlSeconds},storagePolicy={...defaultProductionExecutionDurableStoragePolicy,enabled:true,reservationTtlSeconds:ttlSeconds,idempotencyPolicy:idPolicy},leasePolicy={...defaultProductionExecutionDurableLeasePolicy,reservationTtlSeconds:ttlSeconds,maximumLeaseDurationSeconds:ttlSeconds},claimPolicy={...defaultProductionExecutionClaimPolicy,reservationTtlSeconds:ttlSeconds},attemptPolicy={...defaultProductionExecutionAttemptPolicy,reservationTtlSeconds:ttlSeconds},identity=buildProductionExecutionIdempotencyIdentity({authorization,confirmation},{evaluatedAt:anchor,policy:idPolicy}).identity!;
 const adapter=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:`${ProjectReader.getProjectFolder(context.projectSlug)}/production-execution`}),storage=new AdapterBackedProductionExecutionDurableStorage(adapter),leases=new AdapterBackedProductionExecutionDurableLeaseService(adapter),claims=new AdapterBackedProductionExecutionClaimService(adapter),reservation:ProductionExecutionIdempotencyReservationRequest={schemaVersion:"1",identity,authorization,confirmation,requestedAt:anchor,expectedInitialState:"reserved",attempt:attemptNumber+1,maxAttempts:3,reservationTtlSeconds:ttlSeconds,policyContext:{source:"server",environment:"hosted"},metadata:{source:"server"}},record:ProductionExecutionIdempotencyRecord={schemaVersion:"1",recordId,identityFingerprint:identity.identityFingerprint,idempotencyKey:identity.idempotencyKey,requestId:identity.requestId,executionFingerprint:identity.executionFingerprint,bindingFingerprint:identity.bindingFingerprint,actorId:identity.actorId,projectSlug:identity.projectSlug,operation:identity.operation,action:identity.action,stage:identity.stage,authorizationDecisionId:identity.authorizationDecisionId,confirmationRequestId:identity.confirmationRequestId,confirmationId:identity.confirmationId,policyVersion:identity.policyVersion,riskLevel:identity.riskLevel,state:"reserved",attempt:attemptNumber+1,maxAttempts:3,createdAt:anchor,updatedAt:anchor,reservedAt:anchor,evidence:["source:pipeline-composition"],integrity:{algorithm:"stable-production-id-v1",fingerprint:identity.identityFingerprint,version:1}};
 const reservationRead=await adapter.read("reservation",identity.identityFingerprint),reservationReady=reservationRead.status==="found"||(await storage.createReservation(reservation,{evaluatedAt:anchor,policy:storagePolicy})).ok,existingRecord=await storage.read(record.recordId),recordReady=Boolean(existingRecord.record)||(await storage.createRecord(record,{evaluatedAt:anchor,policy:storagePolicy})).ok;if(!reservationReady||!recordReady)throw new Error("Pipeline durable reservation preparation failed.");const worker={schemaVersion:"1" as const,workerId,workerType:"server" as const,operationScope:[operation],identitySource:"trusted-server" as const},session={schemaVersion:"1" as const,workerSessionId:sessionId,workerId,startedAt:anchor,identitySource:"trusted-server" as const},terminalReplay=existingRecord.record?.state==="succeeded"&&existingRecord.record.durableLease?.status==="released";if(!terminalReplay){const acquired=await leases.acquire({recordId:record.recordId,expectedVersion:1,evaluatedAt:anchor,worker,session,leaseId,acquiredAt:anchor,heartbeatAt:anchor,expiresAt:new Date(Date.parse(anchor)+ttlSeconds*1000).toISOString()},leasePolicy);if(!acquired.ok&&acquired.reasonCode!=="LEASE_REPLAYED")throw new Error(`Pipeline durable lease preparation failed: ${acquired.reasonCode}`)}const claimRequest={claimId,recordId:record.recordId,reservationId:identity.identityFingerprint,requestId,idempotencyKey,executionFingerprint,workerId,workerSessionId:sessionId,leaseId,expectedReservationVersion:1,expectedIdempotencyVersion:2,expectedLeaseVersion:1,expectedClaimVersion:0,evaluatedAt:now};if(!terminalReplay){const claimed=await claims.acquireExecutionClaim(claimRequest,claimPolicy);if(!claimed.ok)throw new Error("Pipeline durable claim preparation failed.")}
 const request:ProductionExecutionWorkerExecutionRequest={coordinator:{claim:claimRequest,attempt:{attemptId,claimId,reservationId:identity.identityFingerprint,recordId:record.recordId,requestId,idempotencyKey,executionFingerprint,workerId,workerSessionId:sessionId,leaseId,expectedClaimVersion:1,expectedAttemptVersion:0,evaluatedAt:now}},policy:{claim:claimPolicy,attempt:attemptPolicy},runningAt:now,finishedAt:now,runningEventId,terminalEventId};return{adapter,request,settlement:{adapter,request,idempotencyPolicy:idPolicy,leasePolicy,worker,session}}}







