import type { ProductionExecutionAuthorizationRisk } from "./productionExecutionAuthorization";
import type { ProductionExecutionIdempotencyRecord } from "./productionExecutionIdempotency";
export const productionExecutionTransactionSchemaVersion = "1" as const;
export type ProductionExecutionTransactionStrategy = "read-only" | "atomic-replace" | "manifest-last" | "multi-resource-staged" | "unsupported";
export type ProductionExecutionTransactionStepType = "validate-preconditions" | "prepare-temporary-resource" | "write-temporary-resource" | "validate-temporary-resource" | "commit-resource" | "update-manifest" | "verify-consistency" | "record-result" | "cleanup-temporary-resource" | "rollback-resource" | "unsupported";
export interface ProductionExecutionMutationIntent { resourceType:string; logicalResourceId:string; relativeTarget:string; expectedCurrentFingerprint:string; proposedFingerprint:string; writeMode:"create"|"replace"|"append"|"delete"|"none"; contentKind:string; requiredValidation:string[]; manifestDependency:boolean; sensitive:boolean; allowed:boolean }
export interface ProductionExecutionTransactionStep { stepId:string; sequence:number; type:ProductionExecutionTransactionStepType; resource:string; required:boolean; dependsOn:string[]; preconditions:string[]; expectedOutcome:string; failureMode:string; rollbackStepId?:string; journalEventType:string; status:"planned"|"unsupported" }
export interface ProductionExecutionTransactionPlan { schemaVersion:typeof productionExecutionTransactionSchemaVersion; transactionId:string; operationId:string; idempotencyRecordId:string; requestId:string; idempotencyKey:string; executionFingerprint:string; actorId:string; projectSlug:string; operation:string; action:string; stage?:string; policyVersion:string; riskLevel:ProductionExecutionAuthorizationRisk; attempt:number; plannedAt:string; strategy:ProductionExecutionTransactionStrategy; steps:ProductionExecutionTransactionStep[]; resources:ProductionExecutionMutationIntent[]; preconditions:string[]; postconditions:string[]; rollbackPlan:{required:boolean;steps:string[]}; consistencyPlan:{required:boolean;checks:string[]}; journalPlan:{required:boolean;eventTypes:string[]}; integrity:{algorithm:"stable-production-id-v1";fingerprint:string} }
export interface ProductionExecutionTransactionPolicy { policyVersion:string; enabled:boolean; allowedWriteModes:("create"|"replace"|"none")[]; requireManifestLast:boolean; requireRollbackPlan:boolean; requireJournalPlan:boolean; requireConsistencyVerification:boolean }
export interface ProductionExecutionTransactionInput { record:ProductionExecutionIdempotencyRecord; authorizationValid:boolean; confirmationValid:boolean; reservationValid:boolean; resources:ProductionExecutionMutationIntent[] }
export interface ProductionExecutionTransactionBuildResult { ok:boolean; plan?:ProductionExecutionTransactionPlan; reasonCode:ProductionExecutionTransactionReasonCode; reason:string; evidence:string[] }
export type ProductionExecutionTransactionReasonCode = "TRANSACTION_VALID"|"TRANSACTION_POLICY_DISABLED"|"TRANSACTION_INPUT_INVALID"|"TRANSACTION_ID_INVALID"|"TRANSACTION_BINDING_MISMATCH"|"TRANSACTION_STRATEGY_UNSUPPORTED"|"TRANSACTION_STEP_DUPLICATE"|"TRANSACTION_STEP_MISSING"|"TRANSACTION_DEPENDENCY_MISSING"|"TRANSACTION_DEPENDENCY_CYCLE"|"TRANSACTION_SEQUENCE_INVALID"|"TEMPORARY_RESOURCE_REQUIRED"|"TEMPORARY_VALIDATION_REQUIRED"|"COMMIT_BEFORE_VALIDATION"|"MANIFEST_ORDER_INVALID"|"CONSISTENCY_VERIFICATION_REQUIRED"|"ROLLBACK_PLAN_REQUIRED"|"JOURNAL_PLAN_REQUIRED"|"RESOURCE_TARGET_INVALID"|"RESOURCE_TRAVERSAL_DENIED"|"RESOURCE_FINGERPRINT_MISSING"|"WRITE_MODE_UNSUPPORTED"|"TRANSACTION_INDETERMINATE";
export interface ProductionExecutionTransactionValidationResult { decision:"valid"|"invalid"|"indeterminate"; valid:boolean; reasonCode:ProductionExecutionTransactionReasonCode; reason:string; transactionId:string; evaluatedAt:string; evidence:string[] }
