import type{ProductionExecutionDispatchEligibilityResult,ProductionExecutionDispatchEnvelope}from"./productionExecutionDispatch";import type{ProductionExecutionIdempotencyLease}from"./productionExecutionIdempotency";
export const productionExecutionWorkerSchemaVersion="1"as const;export type ProductionExecutionWorkerType="local"|"server"|"isolated"|"system"|"unknown";
export interface ProductionExecutionWorkerIdentity{workerId:string;workerType:ProductionExecutionWorkerType;trusted:boolean;identitySource:string;instanceId:string;supportedSchemaVersions:string[];capabilities:string[];operationScope:string[];stageScope:string[];startedAt:string;buildVersion:string;environmentClass:string;integrity:{algorithm:"stable-production-id-v1";fingerprint:string}}
export interface ProductionExecutionWorkerClaim{claimId:string;workerId:string;dispatchId:string;jobId:string;operationId:string;transactionId:string;idempotencyRecordId:string;executionFingerprint:string;attempt:number;lease:ProductionExecutionIdempotencyLease;claimedAt:string;expectedState:"queued";requiredCapabilities:string[];requiredOperationScope:string[];requiredStageScope:string[];policyVersion:string;integrity:{algorithm:"stable-production-id-v1";fingerprint:string}}
export interface ProductionExecutionWorkerPolicy{policyVersion:string;enabled:boolean;trustedIdentitySources:string[];supportedSchemaVersions:string[];supportedBuildVersions:string[];allowedWorkerTypes:ProductionExecutionWorkerType[];rolloutWorkerIds:string[]}
export interface ProductionExecutionWorkerClaimInput{worker:ProductionExecutionWorkerIdentity;dispatch:ProductionExecutionDispatchEnvelope;dispatchEligibility:ProductionExecutionDispatchEligibilityResult;idempotencyState:string;lease?:ProductionExecutionIdempotencyLease;cancelled:boolean}
export type ProductionExecutionWorkerReasonCode="WORKER_ELIGIBLE"|"WORKER_POLICY_DISABLED"|"WORKER_IDENTITY_INVALID"|"WORKER_UNTRUSTED"|"WORKER_IDENTITY_SOURCE_UNTRUSTED"|"WORKER_SCHEMA_UNSUPPORTED"|"WORKER_BUILD_UNSUPPORTED"|"WORKER_CAPABILITY_MISSING"|"WORKER_OPERATION_SCOPE_DENIED"|"WORKER_STAGE_SCOPE_DENIED"|"WORKER_DISPATCH_INVALID"|"WORKER_ATTEMPT_MISMATCH"|"WORKER_FINGERPRINT_MISMATCH"|"WORKER_LEASE_REQUIRED"|"WORKER_LEASE_INVALID"|"WORKER_LEASE_OWNERSHIP_CONFLICT"|"WORKER_OPERATION_CANCELLED"|"WORKER_ROLLOUT_BLOCKED"|"WORKER_PLAN_INVALID"|"WORKER_RESOURCE_DENIED"|"WORKER_RESULT_INVALID"|"WORKER_INDETERMINATE";
export interface ProductionExecutionWorkerClaimResult{eligible:boolean;decision:"eligible"|"blocked"|"deny"|"indeterminate";reasonCode:ProductionExecutionWorkerReasonCode;claim?:ProductionExecutionWorkerClaim;evidence:string[]}
export interface ProductionExecutionWorkerPlan{executionPlanId:string;workerId:string;claimId:string;transactionId:string;orderedSteps:{stepId:string;type:string;resource:string}[];allowedResources:string[];expectedFingerprints:string[];cancellationPolicy:string;timeoutPolicy:{seconds:number};resultPolicy:string;failurePolicy:string;journalRequirements:string[];integrity:{algorithm:"stable-production-id-v1";fingerprint:string}}
export interface ProductionExecutionWorkerResultEnvelope{status:"succeeded"|"failed"|"cancelled"|"partially-succeeded"|"invalid";operationId:string;transactionId:string;claimId:string;workerId:string;attempt:number;startedAt:string;finishedAt:string;completedSteps:string[];failedStep?:string;resultFingerprint:string;partial:boolean;safeSummary:string;failure?:{code:string;category:string;safeMessage:string};evidence:string[];integrity:{algorithm:"stable-production-id-v1";fingerprint:string}}
