import type { ProductionExecutionPersistenceDiagnostic } from "./productionExecutionPersistence";

export const productionExecutionDurableClaimSchemaVersion="1" as const;
export const productionExecutionDurableClaimStorageVersion="1" as const;
export type ProductionExecutionClaimLifecycleState="active"|"released"|"abandoned";
export type ProductionExecutionClaimReasonCode=
  |"CLAIM_ACQUIRED"|"CLAIM_REPLAYED"|"CLAIM_ACTIVE"|"CLAIM_RELEASED"|"CLAIM_ABANDONED"|"CLAIM_NOT_FOUND"
  |"CLAIM_ID_CONFLICT"|"CLAIM_RESERVATION_CONFLICT"|"CLAIM_IDEMPOTENCY_CONFLICT"|"CLAIM_REQUEST_CONFLICT"|"CLAIM_FINGERPRINT_CONFLICT"|"CLAIM_OWNER_MISMATCH"|"CLAIM_SESSION_MISMATCH"|"CLAIM_LEASE_MISMATCH"
  |"CLAIM_VERSION_CONFLICT"|"CLAIM_STALE_WRITE"|"CLAIM_NEXT_VERSION_CONFLICT"|"CLAIM_PARTIAL_COMMIT"
  |"CLAIM_LEASE_EXPIRED"|"CLAIM_RESERVATION_EXPIRED"|"CLAIM_TERMINAL_STATE"|"CLAIM_TRANSITION_INVALID"|"CLAIM_RELEASE_NOT_ALLOWED"|"CLAIM_ABANDON_NOT_ALLOWED"
  |"CLAIM_RECORD_MALFORMED"|"CLAIM_SCHEMA_UNSUPPORTED"|"CLAIM_STORAGE_VERSION_UNSUPPORTED"|"CLAIM_INTEGRITY_MISMATCH"|"CLAIM_RECOVERY_REQUIRED"|"CLAIM_COMPENSATION_REQUIRED"|"CLAIM_ATOMIC_COMMIT_FAILED"|"CLAIM_READBACK_FAILED"|"CLAIM_INDETERMINATE"
  |"CLAIM_PATH_INVALID"|"CLAIM_TRAVERSAL_DENIED";
export interface ProductionExecutionClaimIdentity{claimId:string;recordId:string;reservationId:string;requestId:string;idempotencyKey:string;operation?:string;executionFingerprint:string;workerId:string;workerSessionId:string;leaseId:string}
export interface ProductionExecutionClaimBinding{reservationVersion:number;idempotencyVersion:number;leaseVersion:number;bindingFingerprint:string}
export interface ProductionExecutionClaimOwnershipEvidence{ownerFingerprint:string;reservationEvidence:string;idempotencyEvidence:string;leaseEvidence:string}
export interface ProductionExecutionClaimPolicy{policyVersion:string;reservationTtlSeconds:number}
export interface ProductionExecutionDurableClaimRecord{schemaVersion:typeof productionExecutionDurableClaimSchemaVersion;storageVersion:typeof productionExecutionDurableClaimStorageVersion;identity:ProductionExecutionClaimIdentity;binding:ProductionExecutionClaimBinding;ownership:ProductionExecutionClaimOwnershipEvidence;state:ProductionExecutionClaimLifecycleState;claimVersion:number;acquiredAt:string;updatedAt:string;releasedAt?:string;abandonedAt?:string;evidence:readonly string[];integrity:{algorithm:"stable-production-id-v1";fingerprint:string}}
export interface ProductionExecutionClaimRequest{claimId:string;recordId:string;reservationId:string;requestId:string;idempotencyKey:string;operation?:string;executionFingerprint:string;workerId:string;workerSessionId:string;leaseId:string;expectedReservationVersion:number;expectedIdempotencyVersion:number;expectedLeaseVersion:number;expectedClaimVersion:number;evaluatedAt:string}
export interface ProductionExecutionClaimReleaseRequest{claimId:string;workerId:string;workerSessionId:string;leaseId:string;expectedClaimVersion:number;evaluatedAt:string}
export interface ProductionExecutionClaimAbandonRequest extends ProductionExecutionClaimReleaseRequest{reason:"expired-lease"|"coordination-recovery"}
export interface ProductionExecutionClaimConflict{category:"claim-id"|"reservation"|"idempotency"|"request"|"fingerprint"|"owner"|"session"|"lease"|"version"|"state"|"integrity";reasonCode:ProductionExecutionClaimReasonCode;expectedVersion?:number;actualVersion?:number}
export interface ProductionExecutionClaimCoordinationPlan{snapshotId:string;writeFreePreflight:true;intendedWrites:readonly["claim-coordination-record"];commitOrder:readonly["claim-coordination-record"];transactional:false;implicitRollback:false}
export interface ProductionExecutionClaimPreflightResult{schemaVersion:typeof productionExecutionDurableClaimSchemaVersion;ok:boolean;reasonCode:ProductionExecutionClaimReasonCode;claim?:ProductionExecutionDurableClaimRecord;coordination:ProductionExecutionClaimCoordinationPlan;expectedClaimVersion:number;actualClaimVersion:number;evidence:readonly string[];conflict?:ProductionExecutionClaimConflict;diagnostics?:readonly ProductionExecutionPersistenceDiagnostic[]}
export interface ProductionExecutionClaimOperationResult{schemaVersion:typeof productionExecutionDurableClaimSchemaVersion;ok:boolean;decision:"acquired"|"released"|"abandoned"|"replayed"|"deny"|"recovery-required"|"indeterminate";reasonCode:ProductionExecutionClaimReasonCode;claim?:ProductionExecutionDurableClaimRecord;coordination:ProductionExecutionClaimCoordinationPlan;partialCommit:boolean;compensationRequired:boolean;evidence:readonly string[];conflict?:ProductionExecutionClaimConflict;diagnostics?:readonly ProductionExecutionPersistenceDiagnostic[]}
export type ProductionExecutionClaimRecoveryClassification="no-claim"|"valid-active"|"replay-safe"|"expired-lease"|"released-lease"|"missing-linked-record"|"stale-linked-version"|"partial-coordination"|"malformed"|"integrity-mismatch"|"unsupported-version"|"ambiguous-evidence"|"recovery-required"|"indeterminate";
export interface ProductionExecutionClaimRecoveryAssessment{schemaVersion:typeof productionExecutionDurableClaimSchemaVersion;classification:ProductionExecutionClaimRecoveryClassification;reasonCode:ProductionExecutionClaimReasonCode;writeFree:true;recoveryRequired:boolean;claim?:ProductionExecutionDurableClaimRecord;evidence:readonly string[];diagnostics?:readonly ProductionExecutionPersistenceDiagnostic[]}
