import type{ProductionExecutionPersistenceDiagnostic}from"./productionExecutionPersistence";
export const productionExecutionDurableAttemptSchemaVersion="1"as const;export const productionExecutionDurableAttemptStorageVersion="1"as const;
export type ProductionExecutionAttemptState="opened"|"active"|"outcome-proposed"|"succeeded"|"failed"|"cancelled"|"abandoned";export type ProductionExecutionOutcomeType="success"|"failure"|"cancellation";export type ProductionExecutionJournalEntryType="ATTEMPT_OPENED"|"CHECKPOINT_RECORDED"|"PROGRESS_RECORDED"|"WARNING_RECORDED"|"OUTCOME_PROPOSED"|"OUTCOME_FINALIZED"|"ATTEMPT_ABANDONED";
export type ProductionExecutionAttemptReasonCode="ATTEMPT_OPENED"|"ATTEMPT_REPLAYED"|"ATTEMPT_ACTIVE"|"ATTEMPT_OUTCOME_PROPOSED"|"ATTEMPT_SUCCEEDED"|"ATTEMPT_FAILED"|"ATTEMPT_CANCELLED"|"ATTEMPT_ABANDONED"|"ATTEMPT_NOT_FOUND"|"ATTEMPT_ID_CONFLICT"|"ATTEMPT_CLAIM_CONFLICT"|"ATTEMPT_RESERVATION_CONFLICT"|"ATTEMPT_IDEMPOTENCY_CONFLICT"|"ATTEMPT_REQUEST_CONFLICT"|"ATTEMPT_FINGERPRINT_CONFLICT"|"ATTEMPT_OWNER_MISMATCH"|"ATTEMPT_SESSION_MISMATCH"|"ATTEMPT_LEASE_MISMATCH"|"JOURNAL_ENTRY_APPENDED"|"JOURNAL_ENTRY_REPLAYED"|"JOURNAL_ENTRY_ID_CONFLICT"|"JOURNAL_SEQUENCE_CONFLICT"|"JOURNAL_SEQUENCE_GAP"|"JOURNAL_ENTRY_INVALID"|"JOURNAL_FINALIZED_ATTEMPT"|"OUTCOME_PROPOSED"|"OUTCOME_REPLAYED"|"OUTCOME_CONFLICT"|"OUTCOME_FINALIZED"|"OUTCOME_FINALIZATION_NOT_ALLOWED"|"OUTCOME_PROPOSAL_REQUIRED"|"OUTCOME_TERMINAL_CONFLICT"|"ATTEMPT_VERSION_CONFLICT"|"ATTEMPT_STALE_WRITE"|"ATTEMPT_NEXT_VERSION_CONFLICT"|"ATTEMPT_PARTIAL_COMMIT"|"ATTEMPT_CLAIM_NOT_ACTIVE"|"ATTEMPT_LEASE_EXPIRED"|"ATTEMPT_RESERVATION_EXPIRED"|"ATTEMPT_TERMINAL_STATE"|"ATTEMPT_TRANSITION_INVALID"|"ATTEMPT_RECORD_MALFORMED"|"ATTEMPT_SCHEMA_UNSUPPORTED"|"ATTEMPT_STORAGE_VERSION_UNSUPPORTED"|"ATTEMPT_INTEGRITY_MISMATCH"|"ATTEMPT_RECOVERY_REQUIRED"|"ATTEMPT_COMPENSATION_REQUIRED"|"ATTEMPT_ATOMIC_COMMIT_FAILED"|"ATTEMPT_READBACK_FAILED"|"ATTEMPT_INDETERMINATE"|"ATTEMPT_PATH_INVALID"|"ATTEMPT_TRAVERSAL_DENIED";
export interface ProductionExecutionAttemptIdentity{attemptId:string;claimId:string;reservationId:string;recordId:string;requestId:string;idempotencyKey:string;executionFingerprint:string;workerId:string;workerSessionId:string;leaseId:string}export interface ProductionExecutionAttemptBinding{claimVersion:number;leaseVersion:number;reservationVersion:number;bindingFingerprint:string}
export interface ProductionExecutionAttemptJournalEntry{entryId:string;attemptId:string;sequence:number;entryType:ProductionExecutionJournalEntryType;recordedAt:string;payload:{code:string;category:string;summary:string};evidence:readonly string[];integrity:{algorithm:"stable-production-id-v1";fingerprint:string}}
export interface ProductionExecutionOutcomeProposal{type:ProductionExecutionOutcomeType;reasonCode:string;category:"result"|"validation"|"provider"|"worker"|"cancelled"|"unknown";summary:string;retryable:boolean;proposedAt:string;evidence:readonly string[];fingerprint:string}
export interface ProductionExecutionDurableAttemptRecord{schemaVersion:typeof productionExecutionDurableAttemptSchemaVersion;storageVersion:typeof productionExecutionDurableAttemptStorageVersion;identity:ProductionExecutionAttemptIdentity;binding:ProductionExecutionAttemptBinding;state:ProductionExecutionAttemptState;attemptVersion:number;openedAt:string;updatedAt:string;journal:readonly ProductionExecutionAttemptJournalEntry[];outcomeProposal?:ProductionExecutionOutcomeProposal;finalizedAt?:string;abandonedAt?:string;evidence:readonly string[];integrity:{algorithm:"stable-production-id-v1";fingerprint:string}}
export interface ProductionExecutionAttemptOpenRequest extends ProductionExecutionAttemptIdentity{expectedClaimVersion:number;expectedAttemptVersion:number;evaluatedAt:string}export interface ProductionExecutionJournalAppendRequest{attemptId:string;workerId:string;workerSessionId:string;leaseId:string;expectedAttemptVersion:number;evaluatedAt:string;entry:Omit<ProductionExecutionAttemptJournalEntry,"integrity">}export interface ProductionExecutionOutcomeProposalRequest{attemptId:string;workerId:string;workerSessionId:string;leaseId:string;expectedClaimVersion:number;expectedAttemptVersion:number;evaluatedAt:string;outcome:Omit<ProductionExecutionOutcomeProposal,"fingerprint">}export interface ProductionExecutionOutcomeFinalizationRequest extends ProductionExecutionOutcomeProposalRequest{}
export interface ProductionExecutionAttemptPolicy{policyVersion:string;reservationTtlSeconds:number;maximumEvidenceItems:number;maximumEvidenceLength:number}
export interface ProductionExecutionAttemptCoordination{snapshotId:string;writeFreePreflight:true;intendedWrites:readonly["attempt-coordination-record"];commitOrder:readonly["attempt-coordination-record"];transactional:false;implicitRollback:false}
export interface ProductionExecutionAttemptResult{schemaVersion:"1";ok:boolean;decision:"opened"|"appended"|"proposed"|"finalized"|"abandoned"|"replayed"|"deny"|"recovery-required"|"indeterminate";reasonCode:ProductionExecutionAttemptReasonCode;attempt?:ProductionExecutionDurableAttemptRecord;coordination:ProductionExecutionAttemptCoordination;partialCommit:boolean;compensationRequired:boolean;evidence:readonly string[];diagnostics?:readonly ProductionExecutionPersistenceDiagnostic[]}
export type ProductionExecutionAttemptRecoveryClassification="no-attempt"|"valid-opened"|"active"|"outcome-proposed"|"finalized-success"|"finalized-failure"|"finalized-cancellation"|"expired-lease"|"inactive-claim"|"missing-linked-claim"|"stale-claim-version"|"stale-lease-binding"|"journal-corruption"|"missing-journal-entry"|"duplicate-entry"|"partial-coordination"|"malformed"|"integrity-mismatch"|"unsupported-version"|"recovery-required"|"compensation-required"|"indeterminate";export interface ProductionExecutionAttemptRecoveryResult{schemaVersion:"1";classification:ProductionExecutionAttemptRecoveryClassification;reasonCode:ProductionExecutionAttemptReasonCode;writeFree:true;recoveryRequired:boolean;attempt?:ProductionExecutionDurableAttemptRecord;evidence:readonly string[]}
