import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";
import held from "./fixtures/ayas-system-audit-held";
import {auditFixture,auditFault,AUDIT_HASH} from "./fixtures/ayas-system-audit-fixture";
import {evaluateAyasSystemClosure} from "../src/lib/ayas/audit/AyasSystemClosureGate";
import {inventoryAyasAuditProtectedRoots} from "../src/lib/ayas/audit/AyasSystemAuditCollector";
const root=fs.mkdtempSync(path.join(os.tmpdir(),"ayas-audit-adversarial-")),before=inventoryAyasAuditProtectedRoots(root);let count=0;
try{
  for(const h of held)assert.equal(evaluateAyasSystemClosure(auditFault(auditFixture(),h.domain,h.fault)).decision,h.expected,h.id);
  const reject=(name:string,raw:unknown)=>{const r=evaluateAyasSystemClosure(raw);assert.equal(r.decision,"BLOCKED",name);assert.equal(r.grantsAuthority,false);assert.ok(!JSON.stringify(r).includes("private-sentinel"),name);count++;};
  const variant=(change:(v:ReturnType<typeof auditFixture>)=>void)=>{const v=auditFixture();change(v);return v;};
  reject("null",null);reject("empty",{});reject("callback",{callback:()=>true});
  let getter=0;const access=auditFixture();Object.defineProperty(access,"head",{get(){getter++;throw Error("must not execute");},enumerable:true});reject("accessor",access);assert.equal(getter,0);
  let trap=0;reject("native proxy",new Proxy(auditFixture(),{ownKeys(){trap++;throw Error("must not execute");}}));assert.equal(trap,0);
  const hidden=auditFixture();Object.defineProperty(hidden,"length",{value:"private-sentinel",enumerable:false});reject("hidden property",hidden);
  const symbol=auditFixture();Object.defineProperty(symbol,Symbol("authority"),{value:true});reject("symbol",symbol);
  reject("extra authority",{...auditFixture(),grantsAuthority:true});reject("raw private body",{...auditFixture(),body:"private-sentinel"});
  reject("unknown domain",variant(v=>{v.evidence[0]!.domain="Z" as never;}));
  reject("unknown severity",variant(v=>{v.evidence[0]!.severity="PERFECT" as never;}));
  reject("unknown state",variant(v=>{v.evidence[0]!.state="APPROVED" as never;}));
  reject("unknown class",variant(v=>{v.evidence[0]!.evidenceClass="MODEL_VERIFIED" as never;}));
  reject("unknown finding code",variant(v=>{v.evidence[0]!.findingCode="private-sentinel" as never;}));
  reject("duplicate check",variant(v=>{v.evidence.push({...v.evidence[0]!});}));
  reject("unknown version",variant(v=>{v.evidence[0]!.checkVersion=2 as never;}));
  reject("source path traversal",variant(v=>{v.evidence[0]!.sourceRef="../private-sentinel";}));
  reject("malformed digest",variant(v=>{v.evidence[0]!.sourceDigest="forged";}));
  reject("PASS without evidence",variant(v=>{v.evidence[0]!.sourceDigest=null;}));
  reject("forged short HEAD",variant(v=>{v.head="1234567";}));
  reject("future evidence",variant(v=>{v.evidence[0]!.observedAt="2026-10-06T10:00:00.000Z";}));
  reject("clock rollback",variant(v=>{v.completedAt="2026-10-04T10:00:00.000Z";}));
  reject("invalid calendar",variant(v=>{v.startedAt="2026-02-30T10:00:00.000Z";}));
  reject("fractional coverage",variant(v=>{v.coverage.executed=1.5;}));
  reject("invented full suite count",variant(v=>{v.coverage.executed=164;}));
  reject("NaN",variant(v=>{v.coverage.executed=NaN;}));
  reject("owner proof does not exempt HEAD",variant(v=>{v.evidence.find(e=>e.checkId==="O_LIVE")!.headIndependent=true;}));
  reject("mandatory scope cannot be NA",variant(v=>{v.evidence[0]!.state="NOT_APPLICABLE";v.evidence[0]!.findingCode="NOT_APPLICABLE_REVIEWED";}));
  reject("background writer is not an audit PASS",variant(v=>{v.mutation.afterDigest="b".repeat(64);v.mutation.attribution="BACKGROUND";v.mutation.writerEvidenceDigest=AUDIT_HASH;}));
  reject("recursive graph",(()=>{const v:Record<string,unknown>={};v.self=v;return v;})());
  assert.equal(count,30);assert.deepEqual(inventoryAyasAuditProtectedRoots(root),before);console.log(JSON.stringify({status:"PASS",heldOut:{passed:held.length,total:held.length},adversarial:{passed:count,total:count},fixture:"FROZEN_HELD_METADATA_CORRUPTION_TEMP",productionMutation:false}));
}finally{assert.equal(path.dirname(fs.realpathSync.native(root)).toLowerCase(),fs.realpathSync.native(os.tmpdir()).toLowerCase());fs.rmSync(root,{recursive:true,force:true});}
