import { pipelineRecoveryStageOrder } from "../src/lib/pipeline/PipelineRecoveryPlanner";
import type { ProductionHealthFinding, ProductionHealthResult } from "../src/types/productionHealth";
import type { ProductionSnapshot, ProductionSnapshotStage, SnapshotValue } from "../src/types/productionSnapshot";
const at = "2026-07-11T12:00:00.000Z";
const known = <T>(value:T):SnapshotValue<T> => ({state:"known",value});
const missing = <T>():SnapshotValue<T> => ({state:"not_recorded"});
export function intelligenceFixture() {
  const finding: ProductionHealthFinding = { code:"failed_stage", severity:"critical", category:"stage", scope:"stage", stage:"script", sources:["manifest","jobs"], message:"Script stage failed.", evidence:{}, detectedAt:at };
  const stages: ProductionSnapshotStage[] = pipelineRecoveryStageOrder.map((stage) => ({ stage, manifestStatus:known(stage === "script" ? "failed" as const : stage === "research" ? "completed" as const : "pending" as const), jobStatus:missing<ProductionSnapshotStage["jobStatus"] extends SnapshotValue<infer T> ? T : never>(), effectiveStatus:stage === "research" ? "completed" as const : stage === "script" ? "failed" as const : "pending" as const, startedAt:missing(), completedAt:missing(), durationMs:missing(), attempts:known(stage === "script" ? 1 : 0), retries:known(0), lastRunType:missing(), dependencyReady:known(stage === "research" || stage === "script"), outputReady:known(stage === "research"), latestJobId:missing(), latestError:stage === "script" ? known("safe failure") : missing(), latestUsage:missing(), consistency:[] }));
  const snapshot: ProductionSnapshot = { schemaVersion:1, generatedAt:at, project:{projectSlug:"intelligence-project",projectStatus:known("script"),isCompleted:known(false),projectUpdatedAt:known(at),manifestProjectStatus:known("script"),completionConsistency:"consistent_incomplete"}, pipeline:{effectiveStatus:"failed",completedStageCount:1,totalStageCount:stages.length,failedStageCount:1,cancelledStageCount:0,queuedStageCount:0,runningStageCount:0,nextRunnableStage:missing(),blockedStage:known("script"),isTerminal:false,hasActiveWork:false}, stages, queue:{derivedFrom:"jobs",queued:[],running:[],failed:["script"],cancelled:[],nextCandidate:missing(),blockedReason:known("script failed"),hasConflict:false,multipleRunningDetected:false}, history:{totalTerminalEvents:1,completedEvents:0,failedEvents:1,cancelledEvents:0,latestEventAt:known(at),averageCompletedDurationMs:missing(),successRate:known(0),perStageSummary:Object.fromEntries(pipelineRecoveryStageOrder.map(stage=>[stage,{stage,completedEvents:0,failedEvents:stage==="script"?1:0,cancelledEvents:0,latestStatus:missing(),latestEventAt:missing()}])) as ProductionSnapshot["history"]["perStageSummary"]}, usage:{totalRequests:0,successfulRequests:0,fallbackRequests:0,failedRequests:0,totalDurationMs:0,providerDistribution:[],modelDistribution:[],availableInputTokens:{value:missing(),recordedRecords:0,totalRecords:0,coverage:0},availableOutputTokens:{value:missing(),recordedRecords:0,totalRecords:0,coverage:0},availableTotalTokens:{value:missing(),recordedRecords:0,totalRecords:0,coverage:0},availableEstimatedCost:{value:missing(),recordedRecords:0,totalRecords:0,coverage:0},tokenCoverage:0,costCoverage:0,latestUsageAt:missing(),latestStatus:missing()}, findings:[], sourceState:{project:{status:"available"},manifest:{status:"available"},jobs:{status:"available"},history:{status:"available"},aiUsage:{status:"available"},stageOutputs:Object.fromEntries(pipelineRecoveryStageOrder.map(stage=>[stage,{status:stage==="research"?"available":"missing"}])) as ProductionSnapshot["sourceState"]["stageOutputs"]} };
  const health: ProductionHealthResult = {schemaVersion:1,evaluatedAt:at,overallSeverity:"critical",status:"critical",findings:[finding],counts:{total:1,info:0,warning:0,critical:1},affectedStages:["script"],sourceConfidence:{level:"complete",availableSourceCount:6,missingSourceCount:0,malformedSourceCount:0,unreadableSourceCount:0,partialSourceCount:0},summary:{headline:"critical",criticalIssueCount:1,warningIssueCount:0,healthyStageCount:1,affectedStageCount:1,hasBlockingIssue:true}};
  return { snapshot, health };
}
