/** Cross-stage assertions and explicit-root TEMP durability. No live account, credential or model. */
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { evaluateAyasRevenueCenterClosure, AYAS_REVENUE_CLOSURE_SCOPES, AYAS_REVENUE_CLOSURE_REGRESSIONS } from "../src/lib/ayas/revenue/activity/AyasRevenueCenterClosure";
import { buildAyasRevenueActivityReport, loadAyasRevenueActivityReport, summarizeAyasRevenueActivity } from "../src/lib/ayas/revenue/activity/AyasRevenueActivityReport";
import { emptyAyasRevenueActivity, planAyasRevenueActivityAppend, snapshotAyasRevenueActivityInput, validateAyasRevenueActivity } from "../src/lib/ayas/revenue/activity/AyasRevenueActivity";
import { AyasRevenueActivityStore } from "../src/lib/ayas/revenue/activity/AyasRevenueActivityStore";
import { buildAyasRevenueContext } from "../src/lib/ayas/revenue/AyasRevenueContext";
import { buildAyasExecutiveBriefing } from "../src/lib/ayas/briefing/AyasExecutiveBriefing";
import { decideAyasRevenueOperation, ayasRevenueModeFor } from "../src/lib/ayas/revenue/AyasRevenueActionPolicy";
import { AYAS_REVENUE_OPERATIONS, AYAS_REVENUE_OPERATION_EFFECT } from "../src/lib/ayas/revenue/AyasRevenuePlatformTypes";
import { decideAyasRevenueSpend } from "../src/lib/ayas/revenue/AyasRevenueSpendPolicy";
import { AYAS_REVENUE_DEFAULT_REINVESTMENT_POLICY } from "../src/lib/ayas/revenue/AyasRevenueReinvestmentPolicy";
import { evaluateAyasRevenueScaling } from "../src/lib/ayas/revenue/scaling/AyasRevenueScaling";
import { classifyAyasRevenueRisk } from "../src/lib/ayas/revenue/security/AyasRevenueRiskClassifier";
import { enterAyasSafeMode } from "../src/lib/ayas/safety/AyasSafeModeStore";
import { fakeRevenueManifest } from "./fixtures/ayas-revenue-fake-adapter";
import { rcActivitySource, rcClosure, rcEvent, rcLedger, rcDigest, rcClone, RC_NOW, RC_AT, RC_HEAD } from "./fixtures/ayas-revenue-closure-fixture";
import { revenueLedgerFixtureFact as fact, revenueLedgerFixtureState as ledger } from "./fixtures/ayas-revenue-ledger-fixture";
import { rmState } from "./fixtures/ayas-revenue-memory-fixture";
import { rsRequest } from "./fixtures/ayas-revenue-scaling-fixture";
const args = process.argv.slice(2), only = args.length === 2 && args[0] === "--case" ? args[1] : null;
assert.ok(args.length === 0 || only !== null);
const rows: { id: string; name: string; ok: boolean; error?: string }[] = []; let number = 0;
async function primary(name: string, fn: () => unknown | Promise<unknown>) {
  const id = "P" + String(++number).padStart(3, "0"); if (only && only !== id) return;
  try { await fn(); rows.push({ id, name, ok: true }); } catch (e) { rows.push({ id, name, ok: false, error: e instanceof Error ? e.message : "ASSERTION" }); }
}
const report = (s: unknown = rcActivitySource(), now = RC_NOW) => buildAyasRevenueActivityReport(s, now);
const closure = (s: unknown = rcClosure()) => evaluateAyasRevenueCenterClosure(s);
const blocked = (s: unknown) => assert.equal(closure(s).status, "BLOCKED");
const parent = fs.realpathSync.native(os.tmpdir()), roots: string[] = [];
const root = () => { const r = fs.mkdtempSync(path.join(parent, "ayas-closure-store-")); roots.push(r); return r; };
async function main() {
  await primary("framework closure retains all six live debts", () => { const c = closure(); assert.equal(c.status, "FRAMEWORK_CLOSED"); assert.equal(c.deferredQualifications.length, 6); assert.equal(c.stage16Complete, false); });
  await primary("no default production activity reader", () => { const r = loadAyasRevenueActivityReport(RC_NOW); assert.equal(r.status, "UNBOUND"); assert.equal(r.realized, null); assert.ok(r.platforms.every(p => p.opportunities === null)); });
  await primary("ledger profit reconciles exactly", () => { const r = report(); assert.equal(r.status, "OBSERVED"); assert.equal(r.realized![0]!.grossRevenueMinor, 1000); assert.equal(r.realized![0]!.contributionProfitMinor, 850); });
  await primary("payout never doubles revenue", () => assert.equal(report().realized![0]!.grossRevenueMinor, 1000));
  await primary("estimates do not enter realized money", () => { const s = rcActivitySource(), e = rcEvent("estimate", { expectedCost: { state: "KNOWN", amount: { valueMinor: 99999, currency: "EUR" } } }); s.activity = rcClone(planAyasRevenueActivityAppend(emptyAyasRevenueActivity(), e, RC_AT).state); s.accounts[0]!.activityHeadDigest = s.activity.records[0]!.recordDigest; const r = report(s); assert.equal(r.estimates.length, 1); assert.equal(r.realized!.length, 1); assert.equal(r.realized![0]!.currency, "USD"); assert.equal(r.realized![0]!.contributionProfitMinor, 850); });
  await primary("missing fees remain unknown profit", () => { const s = rcActivitySource(); s.ledger = rcClone(ledger(fact("missing"))); s.activity = rcClone(emptyAyasRevenueActivity()); s.accounts = []; const r = report(s); assert.equal(r.realized![0]!.contributionProfitMinor, null); });
  await primary("cross currency money stays separate", () => { const s = rcActivitySource(); s.ledger = rcClone(ledger(fact("usd"), fact("eur", "GROSS_REVENUE", 99000, { amount: { valueMinor: 99000, currency: "EUR" } }))); s.activity = rcClone(emptyAyasRevenueActivity()); s.accounts = []; assert.deepEqual(report(s).realized!.map(e => e.currency).sort(), ["EUR", "USD"]); });
  await primary("full history refund retained", () => { const s = rcActivitySource(); s.ledger = rcClone(ledger(fact("g"), fact("f", "PLATFORM_FEE", 100), fact("p", "PAYMENT_PROCESSING_FEE", 50), fact("r", "REFUND", 1200))); s.activity = rcClone(emptyAyasRevenueActivity()); s.accounts = []; assert.equal(report(s).realized![0]!.contributionProfitMinor, -350); });
  await primary("owner queue includes reason effect risk and exact digest", () => { const r = report(); assert.equal(r.approvalQueue.length, 1); const a = r.approvalQueue[0]!; assert.equal(a.reasonCode, "OWNER_GATE"); assert.equal(a.expectedCost.state, "UNKNOWN"); assert.equal(a.requestedDecision, "REVIEW_EXACT_ACTION"); assert.equal(a.actionDigest, rcDigest("action-one")); });
  await primary("connected account requires emitted activity", () => { const s = rcActivitySource(); s.activity = rcClone(emptyAyasRevenueActivity()); s.accounts[0]!.activityHeadDigest = null; assert.equal(report(s).status, "UNAVAILABLE"); });
  await primary("account activity digest drift refuses", () => { const s = rcActivitySource(); s.accounts[0]!.activityHeadDigest = rcDigest("wrong"); assert.equal(report(s).status, "UNAVAILABLE"); });
  await primary("unrepresented activity account refuses", () => { const s = rcActivitySource(); s.accounts = []; assert.equal(report(s).status, "UNAVAILABLE"); });
  await primary("ledger reference drift refuses", () => { const s = rcActivitySource(); s.ledger = rcClone(ledger(fact("other"))); assert.equal(report(s).status, "UNAVAILABLE"); });
  await primary("historical why reconstructs record codes and evidence", () => { const r = report(); assert.equal(r.timeline[0]!.ruleCode, "OWNER_HANDOFF"); assert.equal(r.timeline[0]!.evidenceDigest, rcDigest("evidence-one")); assert.match(summarizeAyasRevenueActivity(rcActivitySource(), RC_NOW).lines.join("\n"), /OWNER_GATE/); });
  await primary("activity is never approval or spend", () => { const r = report(), c = closure(); for (const v of [r, c]) { assert.equal(v.grantsAuthority, false); assert.equal(v.executionAuthority, "NONE"); assert.equal(v.autonomousSpend, 0); } assert.equal(c.ownerPromotion, "REQUIRED_NOT_GRANTED"); });
  await primary("hash-chain alteration refused", () => { const s = rcActivitySource(); s.activity.records[0]!.reasonCode = "OWNER_REQUEST"; assert.throws(() => validateAyasRevenueActivity(s.activity)); });
  await primary("unknown operation refused", () => assert.equal(snapshotAyasRevenueActivityInput({ ...rcEvent(), operation: "RUN_SHELL" }), null));
  await primary("raw private payload refused", () => assert.equal(snapshotAyasRevenueActivityInput({ ...rcEvent(), privateMessage: "private@example.test" }), null));
  await primary("getter refusal has no side effect", () => { let calls = 0; const v = { ...rcEvent() }; Object.defineProperty(v, "reasonCode", { enumerable: true, get: () => { calls++; return "OWNER_GATE"; } }); assert.equal(snapshotAyasRevenueActivityInput(v), null); assert.equal(calls, 0); });
  await primary("native proxy refusal has no reflection", () => { let calls = 0; const v = new Proxy(rcEvent(), { ownKeys() { calls++; return []; } }); assert.equal(snapshotAyasRevenueActivityInput(v), null); assert.equal(calls, 0); });
  await primary("future source observation refused", () => { const s = rcActivitySource(); s.observedAt = "2026-10-03T14:00:00.000Z"; assert.equal(report(s).status, "UNAVAILABLE"); });
  await primary("expired source refused at boundary", () => { const s = rcActivitySource(); s.freshUntil = RC_NOW; assert.equal(report(s).status, "UNAVAILABLE"); });
  await primary("clock cannot backdate observed money", () => assert.equal(report(rcActivitySource(), "2026-10-03T11:00:00.000Z").status, "UNAVAILABLE"));
  await primary("fixture cannot discharge live qualification debt", () => { const s = rcClosure(); s.debts[0] = { ...s.debts[0]!, status: "PASS", evidenceDigest: rcDigest("oauth"), evidenceKind: "DETERMINISTIC_TEST", sourceHead: RC_HEAD }; blocked(s); });
  await primary("no unresolved major can close", () => { const s = rcClosure(); s.findings.unresolvedMajors = 1; blocked(s); });
  await primary("unknown money defaults cannot close", () => { const s = rcClosure(); s.defaults.autonomousSpend = 1; blocked(s); });
  await primary("incomplete debt roster cannot disappear", () => { const s = rcClosure(); s.debts.pop(); blocked(s); });
  await primary("stale Graphify blocks closure", () => { const s = rcClosure(); s.graphify.stale = true; blocked(s); });
  await primary("Graphify integrity fault blocks closure", () => { const s = rcClosure(); s.graphify.integrityViolations = 1; blocked(s); });
  await primary("live label needs correct evidence kind", () => { const s = rcClosure(); s.platformLevels[0]!.level = "LIVE_READ_VALIDATED"; blocked(s); });
  for (const scope of AYAS_REVENUE_CLOSURE_SCOPES) for (const status of ["FAIL", "STALE"]) await primary(scope + " " + status + " cannot close", () => { const s = rcClosure(); const row = s.framework.find(r => r.scope === scope)!; if (status === "STALE") row.sourceHead = "b".repeat(40); else row.status = status; blocked(s); });
  for (const scope of AYAS_REVENUE_CLOSURE_REGRESSIONS) await primary(scope + " NOT_RUN cannot close", () => { const s = rcClosure(); s.regressions.find(r => r.scope === scope)!.status = "NOT_RUN"; blocked(s); });
  for (const operation of AYAS_REVENUE_OPERATIONS) await primary(operation + " preserves authority boundary", () => {
    const effect = AYAS_REVENUE_OPERATION_EFFECT[operation], p = decideAyasRevenueOperation(fakeRevenueManifest({ operations: AYAS_REVENUE_OPERATIONS }), { requestId: "fixture-close-01", platform: "etsy", operation, mode: ayasRevenueModeFor(operation), accountRef: null, requestedAt: RC_AT });
    assert.equal(p.decision, effect === "READ_ONLY" ? "ALLOW_READ" : effect === "LOCAL_DRAFT" ? "ALLOW_LOCAL_DRAFT" : effect === "EXTERNAL_WRITE" ? "REQUIRE_OWNER" : "DENY"); assert.equal(p.grantsAuthority, false); assert.equal(p.monetaryAuthority, "NONE");
  });
  await primary("paid ad denied even model claims owner approved", () => { const r = decideAyasRevenueSpend({ schemaVersion: "1", platform: "etsy", operation: "AD_SPEND", event: "AD_SPEND", amount: { valueMinor: 1, currency: "USD" }, costClass: "metered-paid", source: "OWNER_POLICY", requestedAt: RC_AT, ownerApproved: true }); assert.equal(r.allowedAutonomously, false); assert.equal(r.budgetUsd, 0); });
  await primary("reinvestment remains disabled zero", () => { assert.equal(AYAS_REVENUE_DEFAULT_REINVESTMENT_POLICY.enabled, false); assert.equal(AYAS_REVENUE_DEFAULT_REINVESTMENT_POLICY.basisPoints, 0); });
  await primary("default scaling cannot invent realized source", () => { const r = evaluateAyasRevenueScaling(rsRequest(), RC_NOW); assert.equal(r.plan, null); assert.equal(r.autonomousSpend, 0); });
  await primary("unknown security blocks readiness", () => assert.equal(classifyAyasRevenueRisk(["UNKNOWN_INJECTION_APPROVAL"]).severity, "BLOCKING"));
  await primary("Brain activity comes from durable why", () => { const c = buildAyasRevenueContext({ memory: rmState(), ledger: rcLedger(), activitySource: rcActivitySource(), userText: "Bugün gelir için ne yaptın?", now: RC_NOW }); assert.equal(c.status, "OK"); assert.match(c.lines.join("\n"), /OWNER_GATE/); assert.match(c.lines.join("\n"), /850/); });
  await primary("Brain unavailable activity never guesses", () => { const c = buildAyasRevenueContext({ memory: rmState(), ledger: rcLedger(), activitySource: { invalid: true }, userText: "Gelir faaliyeti", now: RC_NOW }); assert.match(c.lines.join("\n"), /UNAVAILABLE/); });
  await primary("briefing material revenue uses canonical ledger", () => {
    const unavailable = { kind: "unavailable", observedAt: RC_NOW, code: "FIXTURE" }, server = { schemaVersion: "1", generatedAt: RC_NOW, ...Object.fromEntries(["health", "development", "graphify", "experiments", "memory", "capabilities", "security", "atolye", "roadmap"].map(k => [k, unavailable])) };
    const v = buildAyasExecutiveBriefing({ server, revenueActivitySource: rcActivitySource() } as unknown as Parameters<typeof buildAyasExecutiveBriefing>[0]);
    assert.equal(v.sections.find(s => s.domain === "revenue")!.status, "OBSERVED"); assert.ok(v.signals.some(s => s.domain === "revenue" && s.priority === "ACTION_REQUIRED")); assert.equal(v.grantsAuthority, false);
  });
  await primary("no fabricated pending allowance or settlement", () => { const r = report(); assert.equal(r.pendingUnsettled, null); assert.equal(r.currentAllowedProductionAllowance, null); assert.equal(r.productionReinvestmentTransfer, null); });
  await primary("masked account has no private label", () => { const p = report().platforms[0]!; assert.match(p.accountLabel!, /^account-[a-f0-9]{12}$/); assert.equal(p.opportunities, 3); assert.equal(p.activeWork, 0); });
  await primary("activity store missing read creates nothing", () => { const p = root(); assert.equal(new AyasRevenueActivityStore(p).read().revision, 0); assert.equal(fs.existsSync(path.join(p, "data")), false); });
  await primary("durable append replay survives fresh reader", async () => { const p = root(), store = new AyasRevenueActivityStore(p, () => RC_AT); assert.equal((await store.append(rcEvent())).kind, "APPEND"); assert.equal((await store.append(rcEvent())).kind, "REPLAY"); assert.equal(new AyasRevenueActivityStore(p).read().revision, 1); });
  await primary("replay material drift conflicts", async () => { const s = new AyasRevenueActivityStore(root(), () => RC_AT); await s.append(rcEvent()); await assert.rejects(s.append(rcEvent("gate", { reasonCode: "OWNER_REQUEST" }))); assert.equal(s.read().revision, 1); });
  await primary("concurrent records retain full history", async () => { const s = new AyasRevenueActivityStore(root(), () => RC_AT); await Promise.all([s.append(rcEvent("one")), s.append(rcEvent("two"))]); assert.equal(s.read().revision, 2); });
  await primary("SAFE_READ_ONLY blocks local append", async () => { const p = root(); await enterAyasSafeMode({repoRoot:p,env:{},nowMs:()=>Date.parse(RC_AT)}); await assert.rejects(new AyasRevenueActivityStore(p, () => RC_AT).append(rcEvent())); });
  await primary("corrupt file refuses instead of empty", async () => { const p = root(), s = new AyasRevenueActivityStore(p, () => RC_AT); await s.append(rcEvent()); fs.writeFileSync(path.join(p, "data/brain/revenue/activity/history.json"), "{"); assert.throws(() => s.read()); });
  await primary("hard linked history refused", async () => { const p = root(), s = new AyasRevenueActivityStore(p, () => RC_AT); await s.append(rcEvent()); fs.linkSync(path.join(p, "data/brain/revenue/activity/history.json"), path.join(p, "linked.json")); assert.throws(() => s.read()); });
  await primary("symlink ancestor refused", () => { const p = root(), outside = root(); fs.symlinkSync(outside, path.join(p, "data"), process.platform === "win32" ? "junction" : "dir"); assert.throws(() => new AyasRevenueActivityStore(p).read()); fs.rmdirSync(path.join(p, "data")); });
  await primary("recorded clock rollback cannot rewrite history", () => { const a = planAyasRevenueActivityAppend(emptyAyasRevenueActivity(), rcEvent(), RC_NOW); assert.throws(() => planAyasRevenueActivityAppend(a.state, rcEvent("later"), RC_AT)); });
  await primary("queue latest terminal observation closes one exact action", () => { const s = rcActivitySource(); s.observedAt=RC_NOW;s.activity = rcClone(planAyasRevenueActivityAppend(s.activity, rcEvent("done", { phase: "COMPLETED", requestedDecision: null, nextAction: "NONE" }), RC_NOW).state); s.accounts[0]!.activityHeadDigest = s.activity.records.at(-1)!.recordDigest; assert.equal(report(s).approvalQueue.length, 0); assert.equal(report(s).timeline.length, 2); });
  await primary("empty closure cannot invent proof", () => blocked(null));
  await primary("negative zero revision refused", () => assert.throws(() => validateAyasRevenueActivity({ schemaVersion: "1", revision: -0, records: [] })));
  await primary("source never mutates input", () => { const s = rcClosure(), bytes = JSON.stringify(s); closure(s); report(s.activitySource); assert.equal(JSON.stringify(s), bytes); });
  await primary("page has no mutation buttons or homepage dock edits", () => { const s = fs.readFileSync("app/brain/revenue/page.tsx", "utf8"); assert.doesNotMatch(s, /<button|<form|use server|execute|onClick/); assert.match(s, /loadAyasRevenueActivityReport/); });
  await primary("malformed safe mode entry cannot select default checkout", async () => { for (const bad of [null, "positional-root", {}, {repoRoot:"relative"}, {repoRoot:root(),nowMs:"clock"}]) await assert.rejects(enterAyasSafeMode(bad as unknown as Parameters<typeof enterAyasSafeMode>[0]), /AYAS_SAFE_MODE_INPUT_INVALID/); });
  await primary("delayed old cancellation cannot hide newer owner gate",()=>{const s=rcActivitySource();s.observedAt=RC_NOW;s.activity=rcClone(planAyasRevenueActivityAppend(s.activity,rcEvent("older-cancel",{occurredAt:"2026-10-03T11:00:00.000Z",phase:"CANCELLED",requestedDecision:null,nextAction:"NONE",inventory:null}),RC_NOW).state);s.accounts[0]!.activityHeadDigest=s.activity.records.at(-1)!.recordDigest;assert.equal(report(s).approvalQueue.length,1);});
  await primary("historical why filters date without showing future current money",()=>{const r=summarizeAyasRevenueActivity(rcActivitySource(),RC_NOW,undefined,{at:"2026-10-03T11:00:00.000Z",from:null,until:null});assert.ok(!r.lines.some(l=>l.includes("OWNER_GATE")||l.includes("850")));});
  await primary("source snapshot cannot predate its own activity",()=>{const s=rcActivitySource();s.observedAt="2026-10-03T11:00:00.000Z";assert.equal(report(s).status,"UNAVAILABLE");});
  assert.ok(only ? rows.length === 1 : rows.length >= 100);
  console.log(JSON.stringify({ status: rows.every(r => r.ok) ? "PASS" : "FAIL", primary: { passed: rows.filter(r => r.ok).length, total: rows.length }, completePrimary: !only, fixture: "SYNTHETIC_EXPLICIT_TEMP_NO_PRODUCTION_BINDING", results: rows }));
  if (rows.some(r => !r.ok)) process.exitCode = 1;
}
main().catch(e => { console.error(e); process.exitCode = 1; }).finally(() => { for (const p of roots) { assert.equal(path.dirname(fs.realpathSync.native(p)).toLowerCase(), parent.toLowerCase()); assert.ok(path.basename(p).startsWith("ayas-closure-store-")); fs.rmSync(p, { recursive: true, force: true }); } });
