import assert from "node:assert/strict";
import { buildAyasCourseProductionPlan } from "../src/lib/ayas/revenue/content/AyasCourseProductionPlan";
import { evaluateAyasCourseAssetManifest, observeAyasCoursePublication } from "../src/lib/ayas/revenue/content/AyasCourseAssetManifest";
import { digestAyasRevenueData } from "../src/lib/ayas/revenue/AyasRevenueDigest";
import { coursePlan, courseManifest, courseDigest, COURSE_NOW } from "./fixtures/ayas-course-fixture";
type Json = Record<string, any>; // eslint-disable-line @typescript-eslint/no-explicit-any -- adversarial unknown-shape fixture mutation only
const results: { id: string; set: string; ok: boolean; detail: string; failureKind?: string }[] = [];
function run(id: string, set: string, detail: string, fn: () => void) { try { fn(); results.push({ id, set, ok: true, detail }); } catch (e) { results.push({ id, set, ok: false, failureKind: e instanceof assert.AssertionError ? "ASSERTION" : "RUNTIME", detail: detail + ":" + (e instanceof Error ? e.message : "assertion") }); } }
const plan = (change: (p: Json) => void) => { const p: Json = coursePlan(); change(p); return buildAyasCourseProductionPlan(p); };
const lesson = (change: (l: Json, p: Json) => void) => plan(p => change(p.sections[0].lessons[0], p));
const assets = (change: (m: Json) => void, p = coursePlan()) => { const m: Json = courseManifest(p); change(m); return evaluateAyasCourseAssetManifest(p, m, COURSE_NOW); };
const bindReview = (m: Json) => { if (m.ownerQualityReview) m.ownerQualityReview.assetRowsDigest = digestAyasRevenueData(m.lessons); };
run("P01", "primary", "immutable plan and upload handoff remain advisory", () => { const p = buildAyasCourseProductionPlan(coursePlan())!; assert.equal(p.state, "CONTENT_READY"); assert.equal(p.publication, "CLOSED"); assert.equal(p.authority, "NONE"); assert.ok(Object.isFrozen(p.plan.sections[0]!.lessons[0])); const m = evaluateAyasCourseAssetManifest(coursePlan(), courseManifest(), COURSE_NOW)!; assert.equal(m.state, "OWNER_UPLOAD_READY"); assert.equal(m.handoff?.ownerMustUpload, true); assert.equal(m.opensFiles, false); });
run("P02", "primary", "schema exact", () => assert.equal(plan(p => p.extra = true), null));
run("P03", "primary", "neutral local course identifier", () => assert.equal(plan(p => p.courseId = "123456"), null));
run("P04", "primary", "version bounded", () => { assert.equal(plan(p => p.version = 0), null); assert.equal(plan(p => p.version = 10001), null); });
run("P05", "primary", "source evidence mandatory and unique", () => { assert.equal(plan(p => p.sourceEvidenceDigests = []), null); assert.equal(plan(p => p.sourceEvidenceDigests.push(p.sourceEvidenceDigests[0])), null); });
run("P06", "primary", "outcomes unique and bounded", () => assert.equal(plan(p => p.outcomes.push(p.outcomes[0])), null));
run("P07", "primary", "section order consecutive", () => assert.equal(plan(p => p.sections[0].order = 2), null));
run("P08", "primary", "lesson order consecutive", () => assert.equal(lesson(l => l.order = 3), null));
run("P09", "primary", "duplicate lesson refused", () => assert.equal(plan(p => p.sections[0].lessons[1].lessonId = p.sections[0].lessons[0].lessonId), null));
run("P10", "primary", "unknown learning outcome refused", () => assert.equal(lesson(l => l.outcomeIds = ["out_unknown"]), null));
run("P11", "primary", "unmapped outcome remains draft", () => assert.equal(plan(p => p.outcomes.push({ outcomeId: "out_other", description: "Other outcome" }))?.state, "DRAFT"));
run("P12", "primary", "duration bounded", () => { assert.equal(lesson(l => l.durationSeconds = 0), null); assert.equal(lesson(l => l.durationSeconds = 3601), null); });
run("P13", "primary", "missing script draft", () => assert.equal(lesson(l => l.script = null)?.state, "DRAFT"));
run("P14", "primary", "missing visual plan draft", () => assert.equal(lesson(l => l.visualPlan = [])?.state, "DRAFT"));
run("P15", "primary", "missing exercise draft", () => assert.equal(lesson(l => l.exercise = null)?.state, "DRAFT"));
run("P16", "primary", "rights unresolved visible", () => assert.ok(lesson(l => l.rightsEvidenceDigest = null)?.issues.some(i => i.startsWith("RIGHTS_"))));
run("P17", "primary", "generated media policy reviewed", () => assert.ok(lesson(l => l.mediaPolicy = "GENERATED_ALLOWED")?.issues.some(i => i.startsWith("GENERATED_POLICY_"))));
run("P18", "primary", "regulated claims need qualified review", () => { for (const kind of ["MEDICAL", "LEGAL", "FINANCIAL"]) assert.ok(lesson(l => l.claimClass = kind)?.issues.some(i => i.startsWith("CLAIM_"))); });
run("P19", "primary", "contact details refused", () => assert.equal(lesson(l => l.script = "Contact student@example.test"), null));
run("P20", "primary", "untrusted accessors never invoked", () => { let hits = 0; const p = coursePlan(); Object.defineProperty(p, "title", { get() { hits++; return "Other"; }, enumerable: true }); assert.equal(buildAyasCourseProductionPlan(p), null); assert.equal(hits, 0); });
run("P21", "primary", "download resources unique", () => assert.equal(plan(p => p.sections[0].lessons[1].downloads[0].resourceId = "res_notes"), null));
run("P22", "primary", "plan digest covers commercial content/version", () => { const first = buildAyasCourseProductionPlan(coursePlan())!.planDigest; assert.notEqual(plan(p => p.version++)!.planDigest, first); assert.notEqual(lesson(l => l.script += "Changed")!.planDigest, first); });
run("P23", "primary", "manifest plan identity exact", () => assert.equal(assets(m => m.planDigest = courseDigest("wrong")), null));
run("P24", "primary", "missing lesson stops upload", () => { const a = assets(m => { m.lessons.pop(); m.ownerQualityReview = null; })!; assert.equal(a.state, "CONTENT_READY"); assert.equal(a.handoff, null); });
run("P25", "primary", "missing video stops upload", () => assert.equal(assets(m => { m.lessons[0].video = null; m.lessons[0].validation = null; m.ownerQualityReview = null; })?.state, "CONTENT_READY"));
run("P26", "primary", "missing audio stops upload", () => assert.equal(assets(m => { m.lessons[0].audio = null; m.lessons[0].validation = null; m.ownerQualityReview = null; })?.state, "CONTENT_READY"));
run("P27", "primary", "missing captions stops upload", () => assert.equal(assets(m => { m.lessons[0].caption = null; m.lessons[0].validation = null; m.ownerQualityReview = null; })?.state, "CONTENT_READY"));
run("P28", "primary", "unvalidated media waits", () => assert.equal(assets(m => { m.lessons[0].validation = null; m.ownerQualityReview = null; })?.state, "MEDIA_READY"));
run("P29", "primary", "audio quality failure blocks", () => assert.equal(assets(m => { m.lessons[0].validation.audioIntelligible = false; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"));
run("P30", "primary", "caption coverage failure blocks", () => assert.equal(assets(m => { m.lessons[0].validation.captionsComplete = false; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"));
run("P31", "primary", "visual and rights quality failure blocks", () => { for (const field of ["visualQuality", "rightsPass"]) assert.equal(assets(m => { m.lessons[0].validation[field] = false; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"); });
run("P32", "primary", "quality receipt binds exact media", () => assert.equal(assets(m => { m.lessons[0].video.digest = courseDigest("changed"); bindReview(m); }), null));
run("P33", "primary", "script receipt binds exact content", () => assert.equal(assets(m => { m.lessons[0].sourceScriptDigest = courseDigest("wrong"); bindReview(m); }), null));
run("P34", "primary", "relative path traversal refused", () => assert.equal(assets(m => { m.lessons[0].video.pathRef = "courses/../../escape.mp4"; bindReview(m); }), null));
run("P35", "primary", "machine paths refused", () => assert.equal(assets(m => m.lessons[0].video.pathRef = "C:\\Users\\owner\\video.mp4"), null));
run("P36", "primary", "Udemy id cannot become asset directory", () => assert.equal(assets(m => { m.lessons[0].audio.pathRef = "courses/12345/audio.wav"; bindReview(m); }), null));
run("P37", "primary", "foreign manifest lesson refused", () => assert.equal(assets(m => { m.lessons[0].lessonId = "lsn_other"; bindReview(m); }), null));
run("P38", "primary", "duplicate manifest lesson refused", () => assert.equal(assets(m => { m.lessons.push(m.lessons[0]); bindReview(m); }), null));
run("P39", "primary", "download omitted stops upload", () => assert.equal(assets(m => { m.lessons[0].downloads = []; bindReview(m); })?.state, "CONTENT_READY"));
run("P40", "primary", "asset rights must match plan", () => assert.equal(assets(m => { m.lessons[0].rightsEvidenceDigest = courseDigest("wrong"); bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"));
run("P41", "primary", "owner policy review required", () => assert.equal(assets(m => m.ownerQualityReview = null)?.state, "QUALITY_REVIEW_REQUIRED"));
run("P42", "primary", "owner refusal blocks readiness", () => assert.equal(assets(m => m.ownerQualityReview.pass = false)?.state, "QUALITY_REVIEW_REQUIRED"));
run("P43", "primary", "owner review binds exact asset rows", () => assert.equal(assets(m => m.lessons[0].validation.receiptDigest = courseDigest("changed")), null));
run("P44", "primary", "future media and owner review refused", () => { assert.equal(assets(m => { m.lessons[0].validation.reviewedAt = "2026-10-04T12:00:00.000Z"; bindReview(m); }), null); assert.equal(assets(m => m.ownerQualityReview.reviewedAt = "2026-10-04T12:00:00.000Z"), null); });
const evidence = () => ({ source: "OWNER_INPUT", planDigest: buildAyasCourseProductionPlan(coursePlan())!.planDigest, manifestDigest: evaluateAyasCourseAssetManifest(coursePlan(), courseManifest(), COURSE_NOW)!.manifestDigest,
  courseRefDigest: courseDigest("published-course"), observedAt: COURSE_NOW, evidenceDigest: courseDigest("owner-observation") });
run("P45", "primary", "publication absent from readiness", () => assert.equal(evaluateAyasCourseAssetManifest(coursePlan(), courseManifest(), COURSE_NOW)?.publicationEvidence, null));
run("P46", "primary", "explicit owner publication observation", () => { const r = observeAyasCoursePublication(coursePlan(), courseManifest(), evidence(), COURSE_NOW)!; assert.equal(r.state, "OWNER_PUBLISHED_CONFIRMED"); assert.equal((r.publicationEvidence as Json).verification, "OWNER_REPORTED_UNVERIFIED"); assert.equal(r.publication, "CLOSED"); });
run("P47", "primary", "model publication proof refused", () => assert.equal(observeAyasCoursePublication(coursePlan(), courseManifest(), { ...evidence(), source: "MODEL_OUTPUT" }, COURSE_NOW), null));
run("P48", "primary", "publication proof binds exact manifest", () => assert.equal(observeAyasCoursePublication(coursePlan(), courseManifest(), { ...evidence(), manifestDigest: courseDigest("wrong") }, COURSE_NOW), null));
run("P49", "primary", "future publication proof refused", () => assert.equal(observeAyasCoursePublication(coursePlan(), courseManifest(), { ...evidence(), observedAt: "2026-10-04T12:00:00.000Z" }, COURSE_NOW), null));
run("P50", "primary", "missing quality cannot publish", () => { const m: Json = courseManifest(); m.ownerQualityReview = null; assert.equal(observeAyasCoursePublication(coursePlan(), m, evidence(), COURSE_NOW), null); });
run("P51", "primary", "owner review cannot precede media validation", () => assert.equal(assets(m => m.ownerQualityReview.reviewedAt = "2026-10-03T11:00:00.000Z"), null));
run("P52", "primary", "publication cannot precede owner quality review", () => assert.equal(observeAyasCoursePublication(coursePlan(), courseManifest(), { ...evidence(), observedAt: "2026-10-03T11:00:00.000Z" }, COURSE_NOW), null));
run("P53", "primary", "Udemy video course minimum lecture count", () => { const p = coursePlan(); p.sections[0]!.lessons.pop(); const m: Json = courseManifest(p); for (const l of m.lessons) l.validation.videoSeconds = 450; bindReview(m); assert.equal(evaluateAyasCourseAssetManifest(p, m, COURSE_NOW)?.state, "QUALITY_REVIEW_REQUIRED"); });
run("P54", "primary", "measured video duration cannot use plan target", () => assert.equal(assets(m => { m.lessons[0].validation.videoSeconds = 100; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"));
run("P55", "primary", "HD resolution required", () => assert.equal(assets(m => { m.lessons[0].validation.videoWidth = 640; m.lessons[0].validation.videoHeight = 360; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"));
run("P56", "primary", "stereo and synchronized audio required", () => { for (const [key, value] of [["audioChannels", 1], ["audioVideoSync", false]] as const) assert.equal(assets(m => { m.lessons[0].validation[key] = value; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"); });
run("P57", "primary", "dynamic landscape visuals required", () => { assert.equal(assets(m => { m.lessons[0].validation.dynamicVisuals = false; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"); assert.equal(assets(m => { m.lessons[0].validation.videoWidth = 720; m.lessons[0].validation.videoHeight = 1280; bindReview(m); })?.state, "QUALITY_REVIEW_REQUIRED"); });
run("H01", "heldOut", "changed caller cannot mutate prepared plan", () => { const p = coursePlan(), b = buildAyasCourseProductionPlan(p)!; p.title = "Changed"; assert.equal(b.plan.title, "Organize a visual story"); });
run("H02", "heldOut", "empty sections refused", () => assert.equal(plan(p => p.sections = []), null));
run("H03", "heldOut", "noncanonical numeric duration refused", () => assert.equal(lesson(l => l.durationSeconds = Infinity), null));
run("H04", "heldOut", "oversized script refused", () => assert.equal(lesson(l => l.script = "x".repeat(6001)), null));
run("H05", "heldOut", "invalid language refused", () => assert.equal(lesson(l => l.captionLanguage = "../en"), null));
run("H06", "heldOut", "generated policy can be explicitly reviewed", () => assert.equal(lesson(l => { l.mediaPolicy = "GENERATED_ALLOWED"; l.generatedPolicyDigest = courseDigest("generated-policy"); })?.issues.length, 0));
run("H07", "heldOut", "rights uncertainty blocks manifest handoff", () => { const p = coursePlan(); (p.sections[0]!.lessons[0] as Json).rightsEvidenceDigest = null; const m = courseManifest(p); assert.equal(evaluateAyasCourseAssetManifest(p, m, COURSE_NOW)?.state, "QUALITY_REVIEW_REQUIRED"); });
run("H08", "heldOut", "manifest shape exact", () => assert.equal(assets(m => m.autoPublish = true), null));
run("H09", "heldOut", "quality receipt source explicit", () => assert.equal(assets(m => { m.lessons[0].validation.source = "MODEL_OUTPUT"; bindReview(m); }), null));
run("H10", "heldOut", "download unknown id refused", () => assert.equal(assets(m => { m.lessons[0].downloads[0].resourceId = "res_unknown"; bindReview(m); }), null));
run("H11", "heldOut", "publication identity cannot rebind course plan", () => assert.equal(observeAyasCoursePublication(coursePlan(), courseManifest(), { ...evidence(), planDigest: courseDigest("different") }, COURSE_NOW), null));
run("H12", "heldOut", "receipt output has no executable surface", () => { const r = evaluateAyasCourseAssetManifest(coursePlan(), courseManifest(), COURSE_NOW)!; assert.equal(r.authority, "NONE"); assert.equal(r.publication, "CLOSED"); assert.equal(r.opensFiles, false); assert.ok(!JSON.stringify(r).includes("AUTO_PUBLISHED")); });
const primary = results.filter(r => r.set === "primary"), heldOut = results.filter(r => r.set === "heldOut");
console.log(JSON.stringify({ status: results.every(r => r.ok) ? "PASS" : "FAIL", primary: { passed: primary.filter(r => r.ok).length, total: primary.length }, heldOut: { passed: heldOut.filter(r => r.ok).length, total: heldOut.length }, noLiveIO: true, results }));
if (results.some(r => !r.ok)) process.exitCode = 1;
