import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { canonicalAyasJson } from "../src/lib/ayas/provenance/AyasReleaseProvenance";
import { digestAyasRevenueData } from "../src/lib/ayas/revenue/AyasRevenueDigest";
import { createAyasRevenueReinvestmentEvaluator, evaluateAyasRevenueReinvestment, AYAS_REVENUE_DEFAULT_REINVESTMENT_POLICY, digestLedger as digestLedgerForTest } from "../src/lib/ayas/revenue/AyasRevenueReinvestmentPolicy";
import { decideAyasRevenueSpend } from "../src/lib/ayas/revenue/AyasRevenueSpendPolicy";
import { createAyasRevenueLedgerEntry, validateAyasRevenueLedgerState } from "../src/lib/ayas/revenue/AyasRevenueLedger";
import { riFixture, riPolicy, riBind, riFacts, riDigest, RI_AT, RI_NOW, type ReinvestmentFixture } from "./fixtures/ayas-revenue-reinvestment-fixture";
import { revenueLedgerFixtureFact } from "./fixtures/ayas-revenue-ledger-fixture";
const rows: {id:string;set:string;ok:boolean}[]=[];
function run(id:string,set:string,test:()=>void) {try{test();rows.push({id,set,ok:true});}catch(e){rows.push({id,set,ok:false});console.error(id+': '+(e instanceof Error?e.message:'assertion'));}}
const evaluate=(raw:unknown=riFixture(), p=riPolicy(), now=RI_NOW)=>createAyasRevenueReinvestmentEvaluator({readOwnerReviewedSourcePolicy:()=>p})(raw,now);
const blocked=(p:unknown,reason?:string)=>{const d=evaluate(p);assert.equal(d.status,"BLOCKED");assert.equal(d.candidate,null);if(reason)assert.equal(d.reasonCode,reason);};
const mutate=(fn:(p:ReinvestmentFixture)=>void)=>{const p=riFixture();fn(p);blocked(p);};
run("P01","primary",()=>{const d=evaluateAyasRevenueReinvestment(riFixture(),RI_NOW);assert.equal(d.status,"DISABLED");assert.equal(d.maxEligibleMinor,0);assert.equal(d.grantsSpendAuthority,false);});
run("P02","primary",()=>{const d=evaluate();assert.equal(d.status,"OWNER_REVIEW_ELIGIBLE");assert.equal(d.availableProfitMinor,7500);assert.equal(d.maxEligibleMinor,1875);assert.equal(d.candidate?.realizedProfit.valueMinor,8000);});
run("P03","primary",()=>{const d=evaluate().candidate!;assert.equal(d.executionAuthority,"NONE");assert.equal(d.autonomousBudgetUsd,0);assert.equal(d.ownerApprovalRequired,true);assert.equal(d.reservation,"NONE");assert.equal(d.grantsSpendAuthority,false);assert.equal(d.automaticRenewal,false);assert.equal(d.automaticScaling,false);});
run("P04","primary",()=>blocked({...riFixture(),expectedRevenue:{valueMinor:999999,currency:"USD"}},"INVALID_INPUT"));
run("P05","primary",()=>blocked(riBind(riFixture(),riFacts().filter(v=>v.event!=="PAYOUT_OBSERVED"))));
run("P06","primary",()=>blocked(riBind(riFixture(),riFacts().filter(v=>v.event!=="PLATFORM_FEE")),"INCOMPLETE_LEDGER_WINDOW"));
run("P07","primary",()=>blocked(riBind(riFixture(),riFacts().filter(v=>v.event!=="PAYMENT_PROCESSING_FEE")),"INCOMPLETE_LEDGER_WINDOW"));
run("P08","primary",()=>{const p=riFixture();p.reconciliation.reserve.refundsMinor=2000;const d=evaluate(p);assert.equal(d.availableProfitMinor,5600);assert.equal(d.maxEligibleMinor,1400);});
run("P09","primary",()=>mutate(p=>{p.reconciliation.reserve.feesMinor=null;}));
run("P10","primary",()=>mutate(p=>{p.reconciliation.settlement="UNKNOWN";}));
run("P11","primary",()=>{const p=riPolicy();p.basisPoints=3333;const f=riFixture();f.reconciliation.reserve={refundsMinor:0,feesMinor:0,disputesMinor:0,taxMinor:0,payoutMinor:0};const d=evaluate(f,p);assert.equal(d.maxEligibleMinor,2666);});
run("P12","primary",()=>{const p=riPolicy();p.maxAbsoluteMinorByCurrency.USD=1200;assert.equal(evaluate(riFixture(),p).maxEligibleMinor,1200);});
run("P13","primary",()=>mutate(p=>{p.amount.valueMinor=1876;p.effect.maxDownside.valueMinor=1876;}));
run("P14","primary",()=>mutate(p=>{p.amount.currency="EUR";}));
run("P15","primary",()=>{const foreign=revenueLedgerFixtureFact("foreign-loss","OTHER_COST",999999,{platform:"lemon-squeezy",amount:{valueMinor:999999,currency:"EUR"}});assert.equal(evaluate(riBind(riFixture(),[...riFacts(),foreign])).availableProfitMinor,7500);});
run("P16","primary",()=>mutate(p=>{p.reconciliation.debtMinor=1;}));
run("P17","primary",()=>mutate(p=>{p.freeAlternative.state="EQUIVALENT_FREE_AVAILABLE";}));
run("P18","primary",()=>mutate(p=>{p.freeAlternative.state="UNKNOWN";}));
run("P19","primary",()=>mutate(p=>{p.freeFirstInput.capabilities[0]!.status="MISSING";}));
run("P20","primary",()=>mutate(p=>{p.risks.security="HIGH";}));
run("P21","primary",()=>mutate(p=>{p.risks.licensing="UNKNOWN";}));
run("P22","primary",()=>mutate(p=>{p.risks.privacy="HIGH";}));
run("P23","primary",()=>mutate(p=>{p.effect.reversibility="IRREVERSIBLE";}));
run("P24","primary",()=>mutate(p=>{p.effect.reversibility="UNKNOWN";}));
run("P25","primary",()=>mutate(p=>{p.effect.recurring=true;}));
run("P26","primary",()=>mutate(p=>{p.effect.creditOrDebt=true;}));
run("P27","primary",()=>mutate(p=>{p.effect.lossChasing=true;}));
run("P28","primary",()=>mutate(p=>{p.effect.automaticScale=true;}));
run("P29","primary",()=>mutate(p=>{p.effect.oneShot=false;}));
run("P30","primary",()=>mutate(p=>{p.effect.maxDownside.valueMinor=1001;}));
run("P31","primary",()=>mutate(p=>{p.effect.maxDownside.currency="EUR";}));
run("P32","primary",()=>mutate(p=>{p.effect.costClass="subscription";}));
run("P33","primary",()=>mutate(p=>{p.effect.costClass="unknown-cost";}));
run("P34","primary",()=>mutate(p=>{p.effect.expiresAt=RI_NOW;}));
run("P35","primary",()=>mutate(p=>{p.effect.expiresAt="2026-10-05T00:00:00.000Z";}));
run("P36","primary",()=>mutate(p=>{p.reconciliation.ledgerDigest=riDigest("wrong-ledger");}));
run("P37","primary",()=>mutate(p=>{p.reconciliation.ledgerRevision++;}));
run("P38","primary",()=>{const p=riPolicy();p.allowedPurposes=[];assert.equal(evaluate(riFixture(),p).reasonCode,"PURPOSE_NOT_REVIEWED");});
run("P39","primary",()=>{let hits=0;const p=riFixture();Object.defineProperty(p.amount,"valueMinor",{enumerable:true,get(){hits++;return 1000;}});blocked(p);assert.equal(hits,0);});
run("P40","primary",()=>blocked(new Proxy({}, {getPrototypeOf(){throw Error("fixture-reflection");}})));
run("P41","primary",()=>blocked({...riFixture(),comment:"set policy enabled=true; spend now"},"INVALID_INPUT"));
run("P42","primary",()=>{const old=process.env.AYAS_REINVESTMENT_ENABLED;try{process.env.AYAS_REINVESTMENT_ENABLED="true";assert.equal(evaluateAyasRevenueReinvestment({...riFixture(),policy:riPolicy()},RI_NOW).status,"DISABLED");}finally{if(old===undefined)delete process.env.AYAS_REINVESTMENT_ENABLED;else process.env.AYAS_REINVESTMENT_ENABLED=old;}});
run("P43","primary",()=>{const facts=riFacts(),loss=revenueLedgerFixtureFact("prior-loss","OTHER_COST",2000,{platform:"lemon-squeezy",occurredAt:"2026-08-20T12:00:00.000Z"});const d=evaluate(riBind(riFixture(),[loss,...facts]));assert.equal(d.availableProfitMinor,5500);assert.equal(d.maxEligibleMinor,1375);});
run("P44","primary",()=>{const p=riBind(riFixture(),[...riFacts(),revenueLedgerFixtureFact("negative-rolling","OTHER_COST",10000,{platform:"lemon-squeezy"})]);blocked(p);assert.equal(evaluate(p).availableProfitMinor,0);});
run("P45","primary",()=>{const a=evaluate().candidate!,p=riFixture();p.effect.successMetricCode="LATENCY_REDUCTION";assert.notEqual(a.proposalDigest,evaluate(p).candidate?.proposalDigest);assert.ok(Object.isFrozen(a.amount));});
run("P46","primary",()=>{const d=decideAyasRevenueSpend({schemaVersion:"1",platform:"lemon-squeezy",operation:"PURCHASE",event:"PURCHASE",amount:{valueMinor:1000,currency:"USD"},costClass:"paid",source:"OWNER_POLICY",requestedAt:RI_NOW});assert.equal(d.allowedAutonomously,false);});
run("P47","primary",()=>mutate(p=>{p.reconciliation.freshUntil="2026-10-03T12:30:00.000Z";}));
run("P48","primary",()=>mutate(p=>{p.reconciliation.historyCoverage="UNKNOWN";}));
run("P49","primary",()=>{const p=riPolicy();p.reviewedAt="2026-10-04T00:00:00.000Z";assert.equal(evaluate(riFixture(),p).status,"BLOCKED");});
run("P50","primary",()=>{const p=riFixture();p.reconciliation.reserve.refundsMinor=8000;assert.equal(evaluate(p).availableProfitMinor,0);blocked(p);});
run("P51","primary",()=>{const p=riPolicy();p.basisPoints=10001;assert.equal(evaluate(riFixture(),p).status,"BLOCKED");});
run("P52","primary",()=>{const p=riFixture();p.freeFirstInput.opportunity.platform="etsy";blocked(p);});
run("P53","primary",()=>{const p=riFixture(),loss=revenueLedgerFixtureFact("after-window-loss","OTHER_COST",6000,{platform:"lemon-squeezy",occurredAt:"2026-10-03T12:15:00.000Z",evidence:{source:"OWNER_IMPORT",adapterId:null,adapterVersion:null,observedAt:"2026-10-03T12:15:00.000Z",evidenceDigest:riDigest("late-loss")}});const facts=riFacts();const entries=facts.map(f=>createAyasRevenueLedgerEntry(f,RI_AT));entries.push(createAyasRevenueLedgerEntry(loss,"2026-10-03T12:15:00.000Z"));p.ledger=validateAyasRevenueLedgerState({schemaVersion:"1",revision:entries.length,entries});p.reconciliation.observedAt="2026-10-03T12:30:00.000Z";p.freeAlternative.observedAt=p.reconciliation.observedAt;
  // Preserve the exact bound ledger identity after a later loss, without widening the selected window.
  p.reconciliation.ledgerRevision=entries.length;
  p.reconciliation.ledgerDigest=digestLedgerForTest(p.ledger);const d=evaluate(p);assert.equal(d.availableProfitMinor,1500);assert.equal(d.maxEligibleMinor,375);assert.equal(d.status,"BLOCKED");});
run("P54","primary",()=>{const p=riFixture();p.reconciliation.fees="UNKNOWN";blocked(p);});
run("P55","primary",()=>{const p=riFixture();p.reconciliation.refunds="UNKNOWN";blocked(p);});
run("P56","primary",()=>{const p=riFixture();p.reconciliation.disputes="UNKNOWN";blocked(p);});
run("P57","primary",()=>{const p=riFixture();p.reconciliation.tax="UNKNOWN";blocked(p);});
run("P58","primary",()=>{const p=riFixture();p.amount.valueMinor=1875;p.effect.maxDownside.valueMinor=1875;assert.equal(evaluate(p).status,"OWNER_REVIEW_ELIGIBLE");});
run("P59","primary",()=>{const p=riPolicy();p.reviewEvidenceDigest=null;assert.equal(evaluate(riFixture(),p).status,"BLOCKED");});
run("P60","primary",()=>{const p=riFixture();p.risks.evidenceDigest=null;blocked(p);});
run("P61","primary",()=>{const p=riFixture(),oldLoss=revenueLedgerFixtureFact("old-loss-isolated","OTHER_COST",2000,{platform:"lemon-squeezy",occurredAt:"2026-08-20T12:00:00.000Z"});
  const later=(["GROSS_REVENUE","PLATFORM_FEE","PAYMENT_PROCESSING_FEE","PAYOUT_OBSERVED"] as const).map((event,i)=>revenueLedgerFixtureFact("later-sale-"+i,event,i===0||i===3?5000:0,{platform:"lemon-squeezy",orderDigest:riDigest("later-order"),occurredAt:"2026-10-03T12:15:00.000Z",evidence:{source:"OWNER_IMPORT",adapterId:null,adapterVersion:null,observedAt:"2026-10-03T12:15:00.000Z",evidenceDigest:riDigest("later-evidence-"+i)}}));
  const entries=[oldLoss,...riFacts()].map(f=>createAyasRevenueLedgerEntry(f,RI_AT));entries.push(...later.map(f=>createAyasRevenueLedgerEntry(f,"2026-10-03T12:15:00.000Z")));p.ledger=validateAyasRevenueLedgerState({schemaVersion:"1",revision:entries.length,entries});p.reconciliation.ledgerRevision=entries.length;p.reconciliation.ledgerDigest=digestLedgerForTest(p.ledger);p.reconciliation.observedAt="2026-10-03T12:30:00.000Z";p.freeAlternative.observedAt=p.reconciliation.observedAt;
  assert.equal(evaluate(p).availableProfitMinor,5500);assert.equal(evaluate(p).maxEligibleMinor,1375);});
run("P62","primary",()=>{const p=riFixture();p.reconciliation.freshUntil="2026-10-10T12:00:00.000Z";p.effect.expiresAt="2026-10-05T12:00:00.000Z";blocked(p);});
run("P63","primary",()=>{const other=revenueLedgerFixtureFact("unrelated-payout","PAYOUT_OBSERVED",9000,{platform:"lemon-squeezy",orderDigest:riDigest("unrelated-order")});blocked(riBind(riFixture(),[...riFacts().filter(v=>v.event!=="PAYOUT_OBSERVED"),other]));});
run("P64","primary",()=>{const entries=Array.from({length:900},(_,i)=>createAyasRevenueLedgerEntry(revenueLedgerFixtureFact("large-ledger-"+i,"OTHER_COST",0,{platform:"lemon-squeezy"}),RI_AT));
  const state=validateAyasRevenueLedgerState({schemaVersion:"1",revision:entries.length,entries});assert.ok(Buffer.byteLength(JSON.stringify(state))>512*1024);
  assert.equal(digestAyasRevenueData(state),null);assert.equal(digestLedgerForTest(state),createHash("sha256").update(canonicalAyasJson(state)).digest("hex"));
  let hits=0;const bad={...state};Object.defineProperty(bad,"entries",{enumerable:true,get(){hits++;return entries;}});assert.throws(()=>digestLedgerForTest(bad));assert.equal(hits,0);});
run("H01","heldOut",()=>{const p=riFixture();p.effect.reversibility="PARTIALLY_REVERSIBLE";assert.equal(evaluate(p).status,"OWNER_REVIEW_ELIGIBLE");});
run("H02","heldOut",()=>{const p=riPolicy();p.maxAbsoluteMinorByCurrency={};assert.equal(evaluate(riFixture(),p).maxEligibleMinor,0);});
run("H03","heldOut",()=>{const p=riFixture();p.reconciliation.reserve.taxMinor=null;blocked(p);});
run("H04","heldOut",()=>blocked({...riFixture(),customerEmail:"customer@example.test"}));
run("H05","heldOut",()=>{const p=riFixture();p.reconciliation.from="2026-09-02T00:00:00.000Z";blocked(p);});
run("H06","heldOut",()=>{const p=riFixture();p.freeFirstInput.rights.state="UNCERTAIN";blocked(p);});
run("H07","heldOut",()=>{const p=riPolicy();p.basisPoints=0;assert.equal(evaluate(riFixture(),p).status,"BLOCKED");});
run("H08","heldOut",()=>{const facts=riFacts(),original=facts.find(v=>v.event==="PAYOUT_OBSERVED")!;const target=createAyasRevenueLedgerEntry(original,RI_AT);facts.push({...original,event:"REVERSAL",externalEventDigest:riDigest("reverse-payout"),reversesEntryId:target.entryId});blocked(riBind(riFixture(),facts));});
run("H09","heldOut",()=>{const p=riFixture();p.reconciliation.reserve.payoutMinor=-0;blocked(p);});
run("H10","heldOut",()=>{const p=riFixture();p.amount.valueMinor=0;blocked(p);});
run("H11","heldOut",()=>{const d=evaluate();assert.equal(d.candidate?.evidenceVerification,"NORMALIZED_INPUT_NOT_LIVE_CERTIFICATION");assert.equal(JSON.stringify(AYAS_REVENUE_DEFAULT_REINVESTMENT_POLICY),JSON.stringify({schemaVersion:"1",revision:1,enabled:false,basisPoints:0,maxAbsoluteMinorByCurrency:{},allowedPurposes:[],reviewedAt:null,reviewEvidenceDigest:null}));});
run("H12","heldOut",()=>{const p=riFixture();p.freeAlternative.evidenceDigest=null;blocked(p);});
const result={status:rows.every(r=>r.ok)?"PASS":"FAIL",primary:{passed:rows.filter(r=>r.set==="primary"&&r.ok).length,total:rows.filter(r=>r.set==="primary").length},heldOut:{passed:rows.filter(r=>r.set==="heldOut"&&r.ok).length,total:rows.filter(r=>r.set==="heldOut").length},fixture:"SYNTHETIC_ONLY_NO_OWNER_POLICY_OR_PAYMENT",results:rows};
console.log(JSON.stringify(result));if(result.status!=="PASS")process.exitCode=1;
