/** Stage16.6:52 primary +12 held-out synthetic local-only scenarios. */
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createAyasFiverrManualAdapter, AYAS_FIVERR_MANIFEST } from "../src/lib/ayas/revenue/adapters/fiverr/AyasFiverrManualAdapter";
import { buildAyasFiverrDraft, snapshotAyasFiverrValue } from "../src/lib/ayas/revenue/adapters/fiverr/AyasFiverrDrafts";
import { createAyasFiverrOwnerHandoff, observeAyasFiverrOwnerCompletion } from "../src/lib/ayas/revenue/adapters/fiverr/AyasFiverrOwnerHandoff";
import { importAyasFiverrOwnerSnapshot, mapAyasFiverrOwnerEconomics } from "../src/lib/ayas/revenue/adapters/fiverr/AyasFiverrOwnerFacts";
import { createAyasRevenuePlatformRegistry, runAyasRevenueReadOrDraft, AYAS_REVENUE_PRODUCTION_ADAPTERS } from "../src/lib/ayas/revenue/AyasRevenuePlatformRegistry";
import { isAyasRevenuePlatformAdapter } from "../src/lib/ayas/revenue/AyasRevenuePlatformAdapter";
import { createAyasRevenueLedgerEntry, emptyAyasRevenueLedger, planAyasRevenueLedgerAppend } from "../src/lib/ayas/revenue/AyasRevenueLedger";
import { classifyPatchTarget } from "../src/lib/brain/selfheal/BrainPatchSafety";
import { FIVERR_NOW as NOW, FIVERR_ACCOUNT as ACCOUNT, fiverrGig, fiverrMessage, fiverrDelivery, fiverrSnapshot, fiverrEconomics, fiverrMoney, fiverrDigest } from "./fixtures/ayas-revenue-fiverr-fixture";
const selected = process.env.AYAS_REVENUE_FIVERR_MUTATION_CASE;
if (selected) { const cwd = fs.realpathSync.native(process.cwd()); assert.equal(path.dirname(cwd).toLowerCase(), fs.realpathSync.native(os.tmpdir()).toLowerCase()); assert.ok(path.basename(cwd).startsWith("ayas-revenue-fiverr-audit-")); assert.ok(!fs.existsSync(path.join(cwd, ".git"))); assert.match(selected, /^[PH]\d{2}$/); }
let n = 0;
const req = (operation = "LISTING_DRAFT", payload: unknown = fiverrGig(), extra: Record<string, unknown> = {}) => ({ requestId: `fiverr-req-${++n}-main`, platform: "fiverr", operation,
  mode: ["LISTING_DRAFT", "MESSAGE_DRAFT", "DELIVERABLE_DRAFT"].includes(operation) ? "DRAFT" : "READ", accountRef: null, payload, requestedAt: NOW, ...extra });
function setup() { const adapter = createAyasFiverrManualAdapter(() => NOW); return { adapter, registry: createAyasRevenuePlatformRegistry([adapter]) }; }
const go = (r = req()) => runAyasRevenueReadOrDraft(setup().registry, r, { now: () => NOW });
const resultData = (r: Awaited<ReturnType<typeof go>>) => r.result!.data as { prepared: { draft: Record<string, unknown>; draftDigest: string; publication: string; local: boolean; issues: string[] }; handoff: ReturnType<typeof createAyasFiverrOwnerHandoff> };
const gig = (overrides: Record<string, unknown> = {}) => buildAyasFiverrDraft("LISTING_DRAFT", fiverrGig(overrides), NOW);
const snapshot = (r: unknown) => importAyasFiverrOwnerSnapshot(r, ACCOUNT, NOW);
const economics = (o: Record<string, unknown> = {}) => mapAyasFiverrOwnerEconomics(fiverrEconomics(o), ACCOUNT, NOW);
const handoff = () => createAyasFiverrOwnerHandoff(gig(), NOW)!;
const observation = (h = handoff(), extra: Record<string, unknown> = {}) => ({ source: "OWNER_INPUT", handoffId: h.handoffId, exactDraftDigest: h.exactDraftDigest, observedAt: NOW, externalReferenceDigest: fiverrDigest("owner-action-reference"), ...extra });
async function closed(r: ReturnType<typeof req>) { const outcome = await go(r); if (outcome.result === null) { assert.equal(outcome.plan.executable, false); assert.equal(outcome.plan.reason, "REQUEST_INVALID"); } else assert.equal(outcome.result.status, "BLOCKED"); }
const results: { id: string; set: string; ok: boolean; detail: string }[] = [];
async function test(id: string, detail: string, run: () => unknown | Promise<unknown>) { if (selected && selected !== id) return; try { await run(); results.push({ id, set: id.startsWith("P") ? "primary" : "held-out", ok: true, detail }); }
  catch (error) { if (selected) throw error; results.push({ id, set: id.startsWith("P") ? "primary" : "held-out", ok: false, detail: String(error) }); } }
async function main() {
  await test("P01", "manual draft-only standard preserved", () => { const s = setup(); assert.ok(isAyasRevenuePlatformAdapter(s.adapter)); assert.deepEqual(s.adapter.manifest.supportedOperations, ["LISTING_DRAFT", "MESSAGE_DRAFT", "DELIVERABLE_DRAFT"]);
    assert.equal(s.adapter.manifest.transport, "MANUAL_HANDOFF"); assert.equal(s.adapter.manifest.credentialHandling, "NONE"); assert.equal(s.adapter.manifest.costClass, "local-zero-cost"); });
  await test("P02", "production registry empty and no executor", () => { assert.equal(AYAS_REVENUE_PRODUCTION_ADAPTERS.length, 0); assert.deepEqual(Object.keys(setup().adapter).sort(), ["draft", "manifest", "read"]); assert.equal(AYAS_FIVERR_MANIFEST.financialOperationsAutonomous, false); });
  await test("P03", "gig draft and handoff are local, never published", async () => { const r = await go(); assert.equal(r.result!.status, "OK"); const d = resultData(r); assert.equal(d.prepared.publication, "CLOSED"); assert.equal(d.prepared.local, true); assert.equal(d.handoff!.completedEvidence, null); });
  await test("P04", "ordered increasing tiers accepted", () => { const p = fiverrGig(); p.packages.push({ ...p.packages[0]!, tier: "STANDARD", price: fiverrMoney(2500) }); assert.notEqual(gig({ packages: p.packages }), null); });
  await test("P05", "USD minimum and integer money enforced", () => { for (const price of [fiverrMoney(499), fiverrMoney(500, "EUR"), fiverrMoney(1500.5)]) { const p = fiverrGig(); p.packages[0]!.price = price; assert.equal(gig({ packages: p.packages }), null); } });
  await test("P06", "duplicate or skipped tiers refused", () => { const p = fiverrGig(); p.packages.push({ ...p.packages[0]! }); assert.equal(gig({ packages: p.packages }), null); assert.equal(gig({ packages: [{ ...p.packages[0]!, tier: "PREMIUM" }] }), null); });
  await test("P07", "bounded delivery and revisions", () => { for (const changed of [{ deliveryDays: 0 }, { deliveryDays: 31 }, { revisions: 0 }, { revisions: 11 }]) assert.equal(gig({ packages: [{ ...fiverrGig().packages[0]!, ...changed }] }), null); });
  await test("P08", "gig text bounds match conservative local limits", () => { for (const changed of [{ title: "x".repeat(81) }, { description: "x".repeat(1201) }, { categoryCode: "../unsafe" }]) assert.equal(gig(changed), null); });
  await test("P09", "media and rights gaps visible", () => { const r = gig({ mediaDigests: [], rightsEvidenceDigest: null, offerRevision: null }) as { issues: unknown };
    assert.deepEqual(r.issues, ["MEDIA_MISSING", "RIGHTS_EVIDENCE_MISSING", "FULFILLMENT_OFFER_PROOF_MISSING"]); assert.equal(gig({ mediaDigests: ["bad"] }), null); });
  await test("P10", "FAQ and requirement bounds", () => { assert.equal(gig({ faq: Array.from({ length: 11 }, () => ({ question: "Question", answer: "Answer" })) }), null); assert.equal(gig({ requirements: ["Dimensions", "Dimensions"] }), null); });
  await test("P11", "tags and media uniqueness", () => { assert.equal(gig({ tags: ["map", "map"] }), null); assert.equal(gig({ tags: ["a", "b", "c", "d", "e", "f"] }), null); assert.equal(gig({ mediaDigests: [fiverrDigest("a"), fiverrDigest("a")] }), null); });
  await test("P12", "gig owner-approved or completion claims cannot widen schema", () => { for (const extra of [{ ownerApproved: true }, { published: true }, { cookie: "synthetic-value" }]) assert.equal(gig(extra), null); });
  await test("P13", "message is a reply draft with opaque references", async () => { const r = await go(req("MESSAGE_DRAFT", fiverrMessage())); assert.equal(r.result!.status, "OK"); assert.equal(resultData(r).handoff!.operation, "MESSAGE_SEND"); assert.equal(resultData(r).handoff!.completedEvidence, null); });
  await test("P14", "cold outreach purpose unsupported", () => assert.equal(buildAyasFiverrDraft("MESSAGE_DRAFT", fiverrMessage({ purpose: "COLD_OUTREACH" }), NOW), null));
  await test("P15", "conversation must be digest not recipient identity", () => assert.equal(buildAyasFiverrDraft("MESSAGE_DRAFT", fiverrMessage({ conversationDigest: "client-name" }), NOW), null));
  await test("P16", "order-related replies require order digest", () => assert.equal(buildAyasFiverrDraft("MESSAGE_DRAFT", fiverrMessage({ orderDigest: null }), NOW), null));
  await test("P17", "private contact and off-platform links refused", async () => { for (const text of ["Please contact private@example.test", "Please visit https://example.test"]) await closed(req("MESSAGE_DRAFT", fiverrMessage({ text }))); });
  await test("P18", "delivery reuses shared quality gate", async () => { const r = await go(req("DELIVERABLE_DRAFT", fiverrDelivery())); assert.equal(r.result!.status, "OK"); assert.equal(resultData(r).handoff!.operation, "DELIVERABLE_SUBMIT"); assert.equal(resultData(r).prepared.draft.completion, "NOT_OBSERVED"); });
  await test("P19", "missing requirements cannot prepare delivery", () => { const p = fiverrDelivery(); p.fulfillment.requirements[0]!.state = "MISSING"; assert.equal(buildAyasFiverrDraft("DELIVERABLE_DRAFT", p, NOW), null); });
  await test("P20", "failed QA or late owner-review state cannot prepare delivery", () => { const p = fiverrDelivery(); p.fulfillment.qa[0]!.state = "FAIL"; assert.equal(buildAyasFiverrDraft("DELIVERABLE_DRAFT", p, NOW), null);
    assert.equal(buildAyasFiverrDraft("DELIVERABLE_DRAFT", fiverrDelivery(), "2026-10-03T18:00:00.000Z"), null); });
  await test("P21", "coherent other platform delivery refused", () => assert.equal(buildAyasFiverrDraft("DELIVERABLE_DRAFT", fiverrDelivery("etsy"), NOW), null));
  await test("P22", "unknown rights cannot prepare delivery", () => { const p = fiverrDelivery(); p.fulfillment.artifacts[0]!.rightsState = "UNKNOWN"; assert.equal(buildAyasFiverrDraft("DELIVERABLE_DRAFT", p, NOW), null); });
  await test("P23", "exact delivery hashes enter manifest and draft digest", () => { const a = fiverrDelivery(), b = fiverrDelivery(); b.message = "Updated prepared files for your review.";
    const da = buildAyasFiverrDraft("DELIVERABLE_DRAFT", a, NOW) as { draftDigest: string; draft: { manifest: { items: { artifactDigest: string }[] } } }, db = buildAyasFiverrDraft("DELIVERABLE_DRAFT", b, NOW) as { draftDigest: string };
    assert.notEqual(da.draftDigest, db.draftDigest); assert.deepEqual(da.draft.manifest.items.map(x => x.artifactDigest).sort(), a.fulfillment.artifacts.map(x => x.artifactDigest).sort()); });
  await test("P24", "draft/handoff never infers owner completion", () => { const h = handoff(); assert.equal(h.completionVerification, "NOT_OBSERVED"); assert.equal(h.ownerMustPerform, true); assert.equal(h.authority, "NONE"); });
  await test("P25", "direct adapter reads honestly unavailable", async () => { const s = setup(); for (const operation of ["ACCOUNT_STATUS_READ", "ANALYTICS_READ", "ORDER_LIST_READ"]) { const r = await s.adapter.read(req(operation, undefined) as never) as { status: string; errorCode: string }; assert.equal(r.status, "UNAVAILABLE"); assert.equal(r.errorCode, "AYAS_REVENUE_FIVERR_UNAVAILABLE_OFFICIAL_TRANSPORT"); } });
  await test("P26", "registry does not dispatch external actions", async () => { for (const operation of ["LISTING_CREATE", "LISTING_UPDATE", "MESSAGE_SEND", "ORDER_ACCEPT", "DELIVERABLE_SUBMIT", "FUNDS_WITHDRAW", "PURCHASE"]) {
    const r = await go(req(operation, undefined, { mode: "EXECUTE" })); assert.equal(r.plan.executable, false); assert.ok(r.result === null || r.result.status === "BLOCKED"); } });
  await test("P27", "no browser network cookie or automatic worker machinery", () => { const dir = path.join(process.cwd(), "src/lib/ayas/revenue/adapters/fiverr"); const source = fs.readdirSync(dir).filter(f => f.endsWith(".ts")).map(f => fs.readFileSync(path.join(dir, f), "utf8")).join("\n");
    assert.doesNotMatch(source, /\bfetch\s*\(|playwright|selenium|puppeteer|node:(?:fs|https?|child_process)|process\.env|setInterval|writeFile|appendFile/i); });
  await test("P28", "handoff operation code-owned, exact digest and no completion", () => { const h = handoff(); assert.equal(h.operation, "LISTING_CREATE"); assert.equal(h.exactDraftDigest, (gig() as { draftDigest: string }).draftDigest); assert.equal(h.monetaryImpact, "UNKNOWN"); assert.ok(h.checklist.includes("OWNER_PUBLISH_ON_FIVERR")); });
  await test("P29", "tampered draft digest refused", () => { const d = structuredClone(gig()) as Record<string, unknown>; d.draftDigest = fiverrDigest("forged"); assert.equal(createAyasFiverrOwnerHandoff(d, NOW), null); });
  await test("P30", "explicit observation remains owner report not certification", () => { const h = handoff(), observed = observeAyasFiverrOwnerCompletion(h, observation(h), NOW)!; assert.equal(observed.completionVerification, "OWNER_REPORTED_UNVERIFIED"); assert.equal(observed.authority, "NONE"); assert.equal(h.completedEvidence, null); assert.notEqual(observed.completedEvidence, null); });
  await test("P31", "completion binds exact draft", () => { const h = handoff(); assert.equal(observeAyasFiverrOwnerCompletion(h, observation(h, { exactDraftDigest: fiverrDigest("wrong") }), NOW), null); });
  await test("P32", "completion binds handoff identity", () => { const h = handoff(); assert.equal(observeAyasFiverrOwnerCompletion(h, observation(h, { handoffId: "wrong" }), NOW), null); });
  await test("P33", "completion cannot be before handoff or in future", () => { const h = handoff(); for (const observedAt of ["2026-10-03T14:00:00.000Z", "2026-10-04T15:00:00.000Z"]) assert.equal(observeAyasFiverrOwnerCompletion(h, observation(h, { observedAt }), NOW), null); });
  await test("P34", "completion not replayed or overwritten", () => { const h = handoff(), done = observeAyasFiverrOwnerCompletion(h, observation(h), NOW)!; assert.equal(observeAyasFiverrOwnerCompletion(done, observation(done), NOW), null); });
  await test("P35", "handoff monetary impact cannot be forged", () => { const h = handoff(); assert.equal(observeAyasFiverrOwnerCompletion({ ...h, monetaryImpact: "NONE" }, observation(h), NOW), null); });
  await test("P36", "account import is explicit owner snapshot", () => { const r = snapshot(fiverrSnapshot()) as Record<string, unknown>; assert.equal(r.verification, "UNVERIFIED_OWNER_REPORT"); assert.equal(r.authority, "NONE"); assert.equal(r.source, "OWNER_INPUT"); });
  await test("P37", "bounded analytics imported locally", () => assert.notEqual(snapshot(fiverrSnapshot("ANALYTICS", { periodStart: "2026-10-01T00:00:00.000Z", periodEnd: "2026-10-03T14:00:00.000Z", impressions: 100, clicks: 10, ordersCompleted: 2 })), null));
  await test("P38", "orders are reported observations", () => assert.notEqual(snapshot(fiverrSnapshot("ORDERS", [{ orderDigest: fiverrDigest("order"), state: "COMPLETED_OBSERVED" }])), null));
  await test("P39", "HTML screenshots secret or private fields refused", () => { for (const fields of [{ html: "<div>page</div>" }, { cookie: "synthetic-value" }, { email: "private@example.test" }]) assert.equal(snapshot(fiverrSnapshot(undefined, undefined, fields)), null); });
  await test("P40", "snapshot freshness and account identity enforced", () => { for (const fields of [{ observedAt: "2026-10-01T15:00:00.000Z" }, { accountRef: "another-account" }, { observedAt: "2026-10-04T15:00:00.000Z" }]) assert.equal(snapshot(fiverrSnapshot(undefined, undefined, fields)), null); });
  await test("P41", "analytics counts/timeline fail closed", () => { const base = { periodStart: "2026-10-01T00:00:00.000Z", periodEnd: "2026-10-03T14:00:00.000Z", impressions: 100, clicks: 10, ordersCompleted: 2 };
    for (const fields of [{ clicks: -1 }, { periodEnd: base.periodStart }, { periodStart: "2026-08-01T00:00:00.000Z" }, { periodEnd: "2026-10-03T16:00:00.000Z" }]) assert.equal(snapshot(fiverrSnapshot("ANALYTICS", { ...base, ...fields })), null);
    assert.equal(snapshot(fiverrSnapshot("ANALYTICS", { ...base, periodEnd: "2026-10-03T14:30:00.000Z" }, { observedAt: "2026-10-03T14:00:00.000Z" })), null); });
  await test("P42", "duplicate orders and unknown states refused", () => { const o = { orderDigest: fiverrDigest("order"), state: "IN_PROGRESS" }; assert.equal(snapshot(fiverrSnapshot("ORDERS", [o, o])), null); assert.equal(snapshot(fiverrSnapshot("ORDERS", [{ ...o, state: "SEND_NOW" }])), null); });
  await test("P43", "owner gross fee payout map separately to valid ledger inputs", () => { const m = economics(); assert.deepEqual(m.inputs.map(i => i.event), ["GROSS_REVENUE", "PLATFORM_FEE", "PAYOUT_OBSERVED"]);
    for (const i of m.inputs) { assert.equal(i.evidence.source, "OWNER_IMPORT"); assert.equal(i.evidence.adapterId, null); assert.doesNotThrow(() => createAyasRevenueLedgerEntry(i, NOW)); } assert.equal(m.appendsLedger, false); });
  await test("P44", "unknown fee remains unknown despite published 80 percent rule", () => { const m = economics({ fee: null }); assert.ok(!m.inputs.some(i => i.event === "PLATFORM_FEE")); assert.ok(m.unknown.includes("PLATFORM_FEE_UNKNOWN")); });
  await test("P45", "in progress order does not realize gross revenue", () => { const m = economics({ orderState: "IN_PROGRESS", completedAt: null, payoutState: "PENDING_CLEARANCE", cashMovementAt: null }); assert.equal(m.inputs.length, 0); assert.ok(m.unknown.includes("ORDER_NOT_COMPLETED_NO_REALIZED_REVENUE")); });
  await test("P46", "available/clearance balance is not observed withdrawal", () => { for (const payoutState of ["AVAILABLE", "PENDING_CLEARANCE", "NOT_OBSERVED"]) assert.ok(!economics({ payoutState, cashMovementAt: null }).inputs.some(i => i.event === "PAYOUT_OBSERVED")); });
  await test("P47", "currency mismatches refused", () => assert.deepEqual(economics({ fee: fiverrMoney(300, "EUR") }).unknown, ["INVALID_OWNER_ECONOMICS"]));
  await test("P48", "unsafe negative and unbounded amounts refused", () => { for (const amount of [-1, Number.MAX_SAFE_INTEGER, 1.5, -0]) assert.deepEqual(economics({ gross: fiverrMoney(amount) }).unknown, ["INVALID_OWNER_ECONOMICS"]); });
  await test("P49", "event identity is idempotent and evidence conflicts stay visible", () => { const m = economics(), entries = m.inputs.map(i => createAyasRevenueLedgerEntry(i, NOW)), state = { ...emptyAyasRevenueLedger(), revision: 3, entries };
    for (const entry of entries) assert.equal(planAyasRevenueLedgerAppend(state, entry).kind, "REPLAY");
    const changed = economics({ evidenceDigest: fiverrDigest("different-evidence") }); assert.throws(() => planAyasRevenueLedgerAppend(state, createAyasRevenueLedgerEntry(changed.inputs[0]!, NOW)), /CONFLICT/); });
  await test("P50", "owner economic schema/identity/timestamps fail closed", () => { for (const fields of [{ ownerApproved: true }, { accountRef: "wrong" }, { source: "MODEL" }, { completedAt: "2026-10-04T14:00:00.000Z" },
    { cashMovementAt: "2026-10-03T13:00:00.000Z" }]) assert.deepEqual(economics(fields).unknown, ["INVALID_OWNER_ECONOMICS"]); });
  await test("P51", "accessors not invoked and snapshots do not alias", () => { let calls = 0; const p = fiverrGig(); Object.defineProperty(p, "title", { enumerable: true, get() { calls++; return "Map title"; } }); assert.equal(buildAyasFiverrDraft("LISTING_DRAFT", p, NOW), null); assert.equal(calls, 0);
    const raw = fiverrSnapshot(), copy = snapshot(raw) as { data: { state: string } }; raw.data = { state: "RESTRICTED" }; assert.equal(copy.data.state, "ACTIVE"); assert.ok(Object.isFrozen(copy.data)); });
  await test("P52", "source/evaluator/manual documentation protected", () => { for (const file of ["src/lib/ayas/revenue/adapters/fiverr/AyasFiverrManualAdapter.ts", "scripts/smoke-ayas-revenue-fiverr-adapter.ts", "scripts/smoke-ayas-revenue-fiverr-adapter-mutations.ts", "scripts/fixtures/ayas-revenue-fiverr-fixture.ts", "docs/AYAS_REVENUE_FIVERR_ADAPTER.md"]) assert.equal(classifyPatchTarget(file).level, "FORBIDDEN_AUTONOMOUS"); });
  await test("H01", "three tiers with increasing explicit scenarios", () => { const base = fiverrGig().packages[0]!; assert.notEqual(gig({ packages: [base, { ...base, tier: "STANDARD", price: fiverrMoney(3000), deliveryDays: 4 }, { ...base, tier: "PREMIUM", price: fiverrMoney(5000), deliveryDays: 5 }] }), null); });
  await test("H02", "missing optional FAQ and media still only a draft", () => { const r = gig({ faq: [], mediaDigests: [] }) as { publication: string; issues: string[] }; assert.equal(r.publication, "CLOSED"); assert.ok(r.issues.includes("MEDIA_MISSING")); });
  await test("H03", "requirements question may precede an order but needs conversation", () => assert.notEqual(buildAyasFiverrDraft("MESSAGE_DRAFT", fiverrMessage({ purpose: "REQUIREMENTS_QUESTION", orderDigest: null }), NOW), null));
  await test("H04", "Unicode local draft supported", () => assert.notEqual(gig({ title: "Şehir haritası tasarlayacağım", description: "İstenen boyut ve biçimde bir şehir haritası." }), null));
  await test("H05", "future cash observation rejected", () => assert.deepEqual(economics({ cashMovementAt: "2026-10-04T14:00:00.000Z" }).unknown, ["INVALID_OWNER_ECONOMICS"]));
  await test("H06", "cancelled owner order has no realized gross", () => assert.ok(!economics({ orderState: "CANCELLED_OBSERVED", completedAt: null, payoutState: "NOT_OBSERVED", cashMovementAt: null }).inputs.some(i => i.event === "GROSS_REVENUE")));
  await test("H07", "cash observation needs amount and time", () => { for (const fields of [{ payout: null }, { cashMovementAt: null }]) assert.deepEqual(economics(fields).unknown, ["INVALID_OWNER_ECONOMICS"]); });
  await test("H08", "unknown gross and fee do not contaminate known cash observation", () => { const r = economics({ gross: null, fee: null }); assert.deepEqual(r.inputs.map(i => i.event), ["PAYOUT_OBSERVED"]); assert.deepEqual(r.unknown, ["GROSS_REVENUE_UNKNOWN", "PLATFORM_FEE_UNKNOWN"]); });
  await test("H09", "already handed-off order not presented as fresh delivery", () => { const p = fiverrDelivery(); p.fulfillment.handoff.state = "HANDED_OFF"; p.fulfillment.handoff.handedOffAt = NOW; p.fulfillment.handoff.manifestDigest = fiverrDigest("wrong-manifest"); p.fulfillment.handoff.evidenceDigest = fiverrDigest("owner-handoff"); assert.equal(buildAyasFiverrDraft("DELIVERABLE_DRAFT", p, NOW), null); });
  await test("H10", "all gig commercial changes alter digest", () => { const a = gig() as { draftDigest: string }, p = fiverrGig(); p.packages[0]!.price = fiverrMoney(2000); assert.notEqual((gig({ packages: p.packages }) as { draftDigest: string }).draftDigest, a.draftDigest); });
  await test("H11", "nested array getter and symbols refused", () => { let calls = 0; const a = ["map"]; Object.defineProperty(a, "0", { get() { calls++; return "map"; } }); assert.equal(gig({ tags: a }), null); assert.equal(calls, 0); assert.equal(snapshotAyasFiverrValue({ [Symbol("hidden")]: true }), null); });
  await test("H12", "missing external reference is unverified owner report only", () => { const h = handoff(), r = observeAyasFiverrOwnerCompletion(h, observation(h, { externalReferenceDigest: null }), NOW)!; assert.equal(r.completionVerification, "OWNER_REPORTED_UNVERIFIED"); assert.equal(r.completedEvidence!.externalReferenceDigest, null); });
  if (!selected) { assert.equal(results.filter(r => r.set === "primary").length, 52); assert.equal(results.filter(r => r.set === "held-out").length, 12); } else assert.equal(results.length, 1);
  console.log(JSON.stringify({ status: results.every(r => r.ok) ? "PASS" : "FAIL", primary: { passed: results.filter(r => r.set === "primary" && r.ok).length, total: results.filter(r => r.set === "primary").length },
    heldOut: { passed: results.filter(r => r.set === "held-out" && r.ok).length, total: results.filter(r => r.set === "held-out").length }, noLiveIO: true, authority: "NONE", results }, null, 2)); if (results.some(r => !r.ok)) process.exitCode = 1;
}
void main();
