/** Deterministic source/ledger assertions; synthetic metadata, no account, network or executor. */
import assert from "node:assert/strict";
import fs from "node:fs";
import ts from "typescript";
import { createAyasRevenueScalingEvaluator, evaluateAyasRevenueScaling } from "../src/lib/ayas/revenue/scaling/AyasRevenueScaling";
import { snapshotAyasRevenueScalingRequest } from "../src/lib/ayas/revenue/scaling/AyasRevenueScalingPolicy";
import { evaluateAyasRevenuePilot } from "../src/lib/ayas/revenue/pilot/AyasRevenuePilotEvaluation";
import { validateAyasRevenueLedgerState, type AyasRevenueLedgerEntry } from "../src/lib/ayas/revenue/AyasRevenueLedger";
import { rpDigest, rpLedgerFact } from "./fixtures/ayas-revenue-pilot-fixture";
import { rsSource, rsRequest, rsEvaluator, rsRebind, rsPaid, rsPilot, RS_NOW, RS_UNTIL, type RsSource } from "./fixtures/ayas-revenue-scaling-fixture";

const args=process.argv.slice(2), only=args.length===2&&args[0]==="--case"?args[1]:null;
assert.ok(args.length===0||only!==null,"INVALID_ARGS");
const results:{id:string;name:string;ok:boolean;error?:string}[]=[];
const test=(id:string,name:string,fn:()=>void)=>{if(only&&id!==only)return;try{fn();results.push({id,name,ok:true});}catch(e){results.push({id,name,ok:false,error:e instanceof Error?e.message:"FAILED"});}};
const run=(s:unknown=rsSource(),q:unknown=rsRequest(),now=RS_NOW)=>rsEvaluator(s)(q,now);
const refusal=(s:unknown,q:unknown,status:string,reason?:string)=>{const d=run(s,q);assert.equal(d.status,status);if(reason)assert.equal(d.reasonCode,reason);assert.equal(d.plan,null);assert.equal(d.executionAuthority,"NONE");assert.equal(d.autonomousSpend,0);};
const append=(s:RsSource,e:AyasRevenueLedgerEntry)=>{s.ledger=validateAyasRevenueLedgerState({schemaVersion:"1",revision:s.ledger.revision+1,entries:[...s.ledger.entries,e]});rsRebind(s);};

test("P01","positive repeated observed money creates owner review plan",()=>{const d=run();assert.equal(d.status,"OWNER_REVIEW_ELIGIBLE");assert.equal(d.plan!.realizedProfitEvidence.valueMinor,1700);assert.equal(d.plan!.evidenceLevel,"REPEATED_RESULT");});
test("P02","production reader remains unbound",()=>assert.equal(evaluateAyasRevenueScaling(rsRequest(),RS_NOW).reasonCode,"CURRENT_SOURCE_UNBOUND_OR_INVALID"));
test("P03","request cannot supply profit",()=>refusal(rsSource(),{...rsRequest(),expectedProfit:999999},"NOT_ELIGIBLE"));
test("P04","request cannot supply a verdict",()=>refusal(rsSource(),{...rsRequest(),pilotVerdict:"PROMISING"},"NOT_ELIGIBLE"));
test("P05","single pilot cannot support material scale",()=>refusal(rsSource(1),rsRequest(),"MORE_EVIDENCE_REQUIRED","REPEATABILITY_REQUIRED"));
test("P06","single pilot permits only next bounded volume repetition",()=>{const q=rsRequest();q.intent="BOUNDED_REPETITION";const d=run(rsSource(1),q);assert.equal(d.reasonCode,"BOUNDED_REPETITION_ONLY");assert.equal(d.plan!.evidenceLevel,"SINGLE_PILOT");});
test("P07","broader channel requires three windows",()=>{const q=rsRequest();q.intent="BROADER_CHANNEL";refusal(rsSource(),q,"MORE_EVIDENCE_REQUIRED","REPEATABILITY_REQUIRED");});
test("P08","three separate windows permit broader review",()=>{const q=rsRequest();q.intent="BROADER_CHANNEL";assert.equal(run(rsSource(3),q).plan!.evidenceLevel,"MULTI_WINDOW_STABLE");});
test("P09","two times ceiling inclusive",()=>{const q=rsRequest();q.proposedLevel=20;assert.equal(run(rsSource(),q).status,"OWNER_REVIEW_ELIGIBLE");});
test("P10","more than two times refused",()=>refusal(rsSource(),{...rsRequest(),proposedLevel:21},"NOT_ELIGIBLE"));
test("P11","zero current level cannot invent ratio",()=>refusal(rsSource(),{...rsRequest(),currentLevel:0},"NOT_ELIGIBLE"));
test("P12","fractional level rejected",()=>refusal(rsSource(),{...rsRequest(),proposedLevel:15.5},"NOT_ELIGIBLE"));
test("P13","negative zero rejected",()=>refusal(rsSource(),{...rsRequest(),currentLevel:-0},"NOT_ELIGIBLE"));
test("P14","multiple dimension array rejected",()=>refusal(rsSource(),{...rsRequest(),scalingDimension:["VOLUME","LISTINGS"]},"NOT_ELIGIBLE"));
test("P15","new platform always needs fresh validation pilot",()=>{const q=rsRequest();q.scalingDimension="PLATFORM_EXPANSION";const d=run(rsSource(),q);assert.equal(d.recommendation,"NEW_PLATFORM_VALIDATION_PILOT");assert.equal(d.plan,null);});
test("P16","same offer full sibling ledger conservatively needs exact attribution",()=>{const s=rsSource(),b=s.pilots[0]!;assert.equal(evaluateAyasRevenuePilot(b.store,b.reconciliations[0]!.planDigest,s.ledger,b.reconciliations[0],RS_NOW).verdict,"INCONCLUSIVE");assert.equal(run(s).status,"OWNER_REVIEW_ELIGIBLE");});
test("P17","unknown full history fails closed",()=>{const s=rsSource();s.coverage.state="UNKNOWN";refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED","HISTORY_COVERAGE_UNQUALIFIED");});
test("P18","omitted store cannot retain complete roster",()=>{const s=rsSource();s.pilots.pop();refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED","HISTORY_COVERAGE_UNQUALIFIED");});
test("P19","duplicate pilot cannot count twice",()=>{const s=rsSource();s.pilots[1]=s.pilots[0]!;refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED","PILOT_SCOPE_OR_HISTORY_MISMATCH");});
test("P20","stale coverage rejected",()=>{const s=rsSource();s.coverage.freshUntil="2026-10-04T12:59:00.000Z";refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED");});
test("P21","future coverage rejected",()=>{const s=rsSource();s.coverage.observedAt=RS_UNTIL;refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED");});
test("P22","coverage cannot claim unbounded freshness",()=>{const s=rsSource();s.coverage.freshUntil="2026-12-01T12:00:00.000Z";refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED");});
test("P23","full ledger revision mismatch rejected",()=>{const s=rsSource();s.coverage.ledgerRevision++;refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED");});
test("P24","pilot reconciliation full ledger mismatch rejected",()=>{const s=rsSource();s.pilots[0]!.reconciliations[0]!.ledgerDigest=rpDigest("wrong");refusal(s,rsRequest(),"ECONOMICS_BLOCKED","PILOT_FULL_LEDGER_BINDING_REQUIRED");});
test("P25","unresolved refunds reject qualified profit",()=>{const s=rsSource();s.pilots[0]!.reconciliations[0]!.refunds="UNKNOWN";refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P26","unknown fees never count as zero",()=>{const s=rsSource();s.pilots[0]!.reconciliations[0]!.fees="UNKNOWN";refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P27","late refund erasing pilot retained",()=>{const s=rsSource();append(s,rpLedgerFact("scale-late-refund","REFUND",1000,{orderDigest:rpDigest("scale-order-0"),occurredAt:RS_NOW}));refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P28","late known fee cannot be omitted",()=>{const s=rsSource();append(s,rpLedgerFact("scale-late-fee","PLATFORM_FEE",1000,{orderDigest:rpDigest("scale-order-0"),occurredAt:RS_NOW}));refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P29","unallocated offer cost cannot be assigned to sibling",()=>{const s=rsSource();append(s,rpLedgerFact("scale-unallocated-fee","PLATFORM_FEE",1,{orderDigest:null,occurredAt:RS_NOW}));refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P30","prior loss outside selected windows retained",()=>{const s=rsSource();append(s,rpLedgerFact("scale-prior-loss","OTHER_COST",1,{orderDigest:null,occurredAt:"2026-09-30T12:00:00.000Z"}));refusal(s,rsRequest(),"ECONOMICS_BLOCKED","PRIOR_LOSS_RETAINED");});
test("P31","unexpected nonpassive cost stops even positive profit",()=>{const s=rsSource();append(s,rpLedgerFact("scale-ad","AD_SPEND",1,{orderDigest:rpDigest("scale-order-0"),occurredAt:RS_NOW}));refusal(s,rsRequest(),"SECURITY_BLOCKED");});
test("P32","global reversal of sale retained",()=>{const s=rsSource(),sale=s.ledger.entries[0]!;append(s,rpLedgerFact("scale-reverse","REVERSAL",1000,{orderDigest:sale.orderDigest,occurredAt:RS_NOW,reversesEntryId:sale.entryId}));refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P33","repeated window cannot hide changed primary metric",()=>{const s=rsSource(),p=rsPilot(1,{successMetric:{kind:"PAID_ORDERS",target:1}});s.pilots[1]!.store=p.store;s.pilots[1]!.reconciliations[0]!.planDigest=p.p.planDigest;rsRebind(s);refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED","METRIC_DRIFT_OR_OVERLAPPING_WINDOWS");});
test("P34","metric not achieved blocks",()=>{const s=rsSource(),p=rsPilot(1,{successMetric:{kind:"SALES",target:2}});s.pilots[1]!.store=p.store;s.pilots[1]!.reconciliations[0]!.planDigest=p.p.planDigest;rsRebind(s);refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P35","current security high blocks",()=>{const s=rsSource();s.readiness.security="HIGH";refusal(s,rsRequest(),"SECURITY_BLOCKED");});
test("P36","unknown rights blocks",()=>{const s=rsSource();s.readiness.rights="UNKNOWN";refusal(s,rsRequest(),"SECURITY_BLOCKED");});
test("P37","account restriction blocks",()=>{const s=rsSource();s.readiness.accountStanding="RESTRICTED";refusal(s,rsRequest(),"SECURITY_BLOCKED");});
test("P38","quality failure blocks",()=>{const s=rsSource();s.readiness.deliveryQuality="FAILED";refusal(s,rsRequest(),"CAPACITY_BLOCKED");});
test("P39","unmeasured support blocks",()=>{const s=rsSource();s.readiness.supportMeasured=false;refusal(s,rsRequest(),"CAPACITY_BLOCKED");});
test("P40","support backlog above capacity blocks",()=>{const s=rsSource();s.readiness.supportBacklog=11;refusal(s,rsRequest(),"CAPACITY_BLOCKED");});
test("P41","proposed level exceeds measured capacity blocks",()=>{const s=rsSource();s.readiness.maxLevel=14;refusal(s,rsRequest(),"CAPACITY_BLOCKED");});
test("P42","rollback backlog cannot exceed measured capacity",()=>{const q=rsRequest();q.rollback.maxSupportBacklog=11;refusal(rsSource(),q,"CAPACITY_BLOCKED");});
test("P43","refund deterioration exceeds declared bound",()=>{const s=rsSource();s.readiness.refundRevenueBps=1001;refusal(s,rsRequest(),"ECONOMICS_BLOCKED");});
test("P44","no rollback criterion omitted",()=>{const q=rsRequest();q.rollback.codes.pop();refusal(rsSource(),q,"NOT_ELIGIBLE");});
test("P45","duplicate rollback criterion rejected",()=>{const q=rsRequest();q.rollback.codes[0]=q.rollback.codes[1]!;refusal(rsSource(),q,"NOT_ELIGIBLE");});
test("P46","free-first review incomplete blocks",()=>{const s=rsSource();s.readiness.freeFirstReview="UNKNOWN";refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED");});
test("P47","free-first demand cannot be model opinion",()=>{const s=rsSource();s.freeFirstInput.evidence=s.freeFirstInput.evidence.filter(e=>e.kind!=="PUBLIC_DEMAND_SIGNAL");refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED");});
test("P48","paid scaling default reinvestment disabled",()=>{const {s,q}=rsPaid();refusal(s,q,"ECONOMICS_BLOCKED","REINVESTMENT_POLICY_OR_CEILING_BLOCKED");});
test("P49","reviewed same-ledger ceiling permits paid owner review only",()=>{const {s,q,policy}=rsPaid();const d=rsEvaluator(s,policy)(q,RS_NOW);assert.equal(d.status,"OWNER_REVIEW_ELIGIBLE");assert.ok(d.plan!.reinvestmentProposalDigest);assert.equal(d.grantsSpendAuthority,false);});
test("P50","paid budget above source ceiling rejected",()=>{const {s,q,policy}=rsPaid();policy.maxAbsoluteMinorByCurrency.USD=149;assert.equal(rsEvaluator(s,policy)(q,RS_NOW).status,"ECONOMICS_BLOCKED");});
test("P51","paid amount cannot bind different ledger",()=>{const {s,q}=rsPaid();(s.reinvestmentInput as {ledger:unknown}).ledger={schemaVersion:"1",revision:0,entries:[]};refusal(s,q,"ECONOMICS_BLOCKED","EXACT_REINVESTMENT_BINDING_REQUIRED");});
test("P52","cross currency request refused",()=>refusal(rsSource(),{...rsRequest(),currency:"EUR"},"ECONOMICS_BLOCKED"));
test("P53","loss chasing effect rejected by16.9",()=>{const {s,q,policy}=rsPaid();(s.reinvestmentInput as {effect:{lossChasing:boolean}}).effect.lossChasing=true;assert.equal(rsEvaluator(s,policy)(q,RS_NOW).status,"ECONOMICS_BLOCKED");});
test("P54","debt financing rejected by16.9",()=>{const {s,q,policy}=rsPaid();(s.reinvestmentInput as {effect:{creditOrDebt:boolean}}).effect.creditOrDebt=true;assert.equal(rsEvaluator(s,policy)(q,RS_NOW).status,"ECONOMICS_BLOCKED");});
test("P55","price experiment exact current fact and separate measurement",()=>{const s=rsSource(),q=rsRequest();q.scalingDimension="PRICE_EXPERIMENT";q.priceExperiment={currentMinor:10,proposedMinor:15,currency:"USD"};s.readiness.dimension=q.scalingDimension;s.readiness.priceFact={currency:"USD",valueMinor:10,evidenceDigest:rpDigest("price-fact")};const p=run(s,q).plan!;assert.ok(p);assert.equal(p.afterChangeMeasurement,"SEPARATE_WINDOW_REQUIRED");});
test("P56","price fact cannot be inferred from proposed amount",()=>{const s=rsSource(),q=rsRequest();q.scalingDimension="PRICE_EXPERIMENT";q.priceExperiment={currentMinor:10,proposedMinor:15,currency:"USD"};s.readiness.dimension=q.scalingDimension;refusal(s,q,"MORE_EVIDENCE_REQUIRED","CURRENT_PRICE_FACT_REQUIRED");});
test("P57","approval authority cannot be injected",()=>refusal(rsSource(),{...rsRequest(),ownerApproved:true},"NOT_ELIGIBLE"));
test("P58","executable request getter refused before invocation",()=>{let reads=0;const q=rsRequest();Object.defineProperty(q,"currentLevel",{enumerable:true,get(){reads++;return 10;}});refusal(rsSource(),q,"NOT_ELIGIBLE");assert.equal(reads,0);});
test("P59","request proxy refused with zero traps",()=>{let reads=0;refusal(rsSource(),new Proxy(rsRequest(),{get(){reads++;return 1;},ownKeys(){reads++;return [];}}),"NOT_ELIGIBLE");assert.equal(reads,0);});
test("P60","source proxy refused with zero traps",()=>{let reads=0;refusal(new Proxy(rsSource(),{get(){reads++;return 1;},ownKeys(){reads++;return [];}}),rsRequest(),"MORE_EVIDENCE_REQUIRED");assert.equal(reads,0);});
test("P61","immutable deterministic request and evidence",()=>{const s=rsSource(),q=rsRequest(),before=JSON.stringify({s,q});const a=run(s,q),b=run(s,q);assert.deepEqual(a,b);assert.equal(JSON.stringify({s,q}),before);assert.ok(Object.isFrozen(a.plan!.rollback.codes));});
test("P62","plan carries only zero authority and owner rollback",()=>{const d=run(),p=d.plan!;assert.equal(p.ownerApprovalRequired,true);assert.equal(p.executionAuthority,"NONE");assert.equal(p.grantsSpendAuthority,false);assert.equal(p.autonomousSpend,0);assert.equal(p.rollbackAction,"OWNER_CONTROLLED_ONLY");assert.equal(p.qualification,"NORMALIZED_SOURCE_NOT_LIVE_CERTIFICATION");assert.equal(p.expiresAt,RS_UNTIL);});
test("P63","source callback failure fail closed",()=>assert.equal(createAyasRevenueScalingEvaluator({readCurrentEvidence:()=>{throw Error("secret-body");}})(rsRequest(),RS_NOW).reasonCode,"INVALID_EVIDENCE_OR_SOURCE"));
test("P64","readiness stale blocks",()=>{const s=rsSource();s.readiness.freshUntil="2026-10-04T12:59:00.000Z";refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED");});
test("P65","source modules no transport storage environment or consumers",()=>{for(const name of ["AyasRevenueScaling.ts","AyasRevenueScalingPolicy.ts","AyasRevenueScalingPlan.ts"]){const source=fs.readFileSync("src/lib/ayas/revenue/scaling/"+name,"utf8"),ast=ts.createSourceFile(name,source,ts.ScriptTarget.Latest,true);const walk=(node:ts.Node)=>{if(ts.isImportDeclaration(node)){assert.ok(ts.isStringLiteral(node.moduleSpecifier));assert.ok(!/node:(?:fs|child_process|http|https|net)|Store$|Adapter$/.test(node.moduleSpecifier.text));}if(ts.isPropertyAccessExpression(node))assert.ok(!(ts.isIdentifier(node.expression)&&node.expression.text==="process"&&node.name.text==="env"));if(ts.isCallExpression(node)&&ts.isIdentifier(node.expression))assert.notEqual(node.expression.text,"fetch");ts.forEachChild(node,walk);};walk(ast);}assert.equal(snapshotAyasRevenueScalingRequest({...rsRequest(),command:"pay"}),null);});
test("P66","paid dimension bound matches the requested money",()=>{const {s,q}=rsPaid();q.requiredBudget!.valueMinor=151;q.maxDownside!.valueMinor=151;refusal(s,q,"NOT_ELIGIBLE");});
test("P67","plan expiry cannot outlive paid candidate",()=>{const {s,q,policy}=rsPaid();const at="2026-10-04T14:00:00.000Z";(s.reinvestmentInput as {effect:{expiresAt:string}}).effect.expiresAt=at;assert.equal(rsEvaluator(s,policy)(q,RS_NOW).plan!.expiresAt,at);});
test("P68","unfinished current pilot remains incomplete",()=>{const s=rsSource();s.pilots[1]!.store={...s.pilots[1]!.store,revision:4,events:s.pilots[1]!.store.events.slice(0,4)};rsRebind(s);refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED","CURRENT_PILOT_NOT_COMPLETED");});
test("P69","unknown observation receipts cannot be extra proof",()=>{const s=rsSource();s.pilots[0]!.reconciliations.push({...s.pilots[0]!.reconciliations[0]!});refusal(s,rsRequest(),"MORE_EVIDENCE_REQUIRED","ALL_PILOT_REVISIONS_REQUIRED");});
test("P70","source option getter refused before invocation",()=>{let reads=0;const options={};Object.defineProperty(options,"readCurrentEvidence",{enumerable:true,get(){reads++;return ()=>rsSource();}});assert.throws(()=>createAyasRevenueScalingEvaluator(options),/INVALID_SOURCE_OPTIONS/);assert.equal(reads,0);});
test("P71","zero rollback metric floor cannot disable deterioration",()=>{const q=rsRequest();q.rollback.metricFloorBps=0;refusal(rsSource(),q,"NOT_ELIGIBLE");});
test("P72","unattributable account cost cannot disappear outside offer scope",()=>{const s=rsSource();append(s,rpLedgerFact("scale-unattributable","PLATFORM_FEE",1,{orderDigest:null,offerDigest:null,occurredAt:RS_NOW}));refusal(s,rsRequest(),"ECONOMICS_BLOCKED","UNATTRIBUTABLE_ACCOUNT_COST");});
test("P73","rollback metric floor binds exact observed windows and counts",()=>{const p=run().plan!;assert.equal(p.baselineMetrics.length,2);assert.equal(p.baselineMetrics[0]!.numerator,1);assert.equal(p.metricFloorMeaning,"FRACTION_OF_EACH_SOURCE_WINDOW_BASELINE");assert.equal(p.baselineMetrics[0]!.planDigest,p.sourcePlanDigests[0]);});
assert.equal(results.length,only?1:73);const failed=results.filter(r=>!r.ok);console.log(JSON.stringify({status:failed.length?"FAIL":"PASS",primary:{pass:results.length-failed.length,total:results.length},completePrimary:only===null,liveQualification:"NOT_RUN",network:"NONE",results}));if(failed.length)process.exitCode=1;
