/**
 * Documentary media effort — Faz 3 (ADR-020): real video ingestion + segment
 * rendering + the deterministic per-scene media ladder.
 *
 * NO real network and NO real paid API. The only real dependency is the local
 * ffmpeg/ffprobe (same binaries the scene-video renderer already uses); every
 * "download" is a fixture that hands back bytes generated by ffmpeg's `testsrc`.
 *
 * Scenarios:
 *   A admissible real video candidate            -> ingest PASS
 *   B restricted licence                         -> FAIL-CLOSED, no download
 *   C unknown licence (even if flagged admissible)-> FAIL-CLOSED, no download
 *   D missing sourceUrl                          -> reject, no download
 *   E missing mediaUrl                           -> reject, no download
 *   F non-video Content-Type                     -> reject after download
 *   G corrupt / non-video bytes                  -> reject at source probe
 *   H invalid segment (reversed + exceeds source)-> reject
 *   I valid segment                              -> deterministic MP4 on disk
 *   J checksum is the sha256 of the source bytes and is stable across runs
 *   K provenance (source/media URL, licence, attribution, rights) preserved
 *   L 16 scenes: 2 real video + 10 real photo + 4 AI            -> PASS
 *   M 16 scenes: 12 real media + 4 AI                            -> PASS
 *   N 16 scenes: 11 real media + 5 AI  -> VISUAL_AI_IMAGE_BUDGET_EXCEEDED
 *   O same input twice -> identical selection plan + asset identity
 *   P one video candidate, 16 hungry scenes -> assigned to exactly one scene
 *   Q existing 5be83a84 artifacts (16-PNG combined sha256) unchanged
 */
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { emitSmokeResult } from "./lib/SmokeResult";
import { withCanonicalSmokeRuntime } from "./lib/CanonicalSmokeRuntime";
import { ProjectManager } from "../src/lib/projects/ProjectManager";
import { VideoStorage } from "../src/lib/assets/storage/VideoStorage";
import {
  deriveVideoAssetIdentity,
  ingestVideoCandidate,
  ingestedVideoToSceneVideoSuccess,
  validateSegment,
  validateVideoCandidateForIngestion,
  videoIngestionPolicy,
  type VideoDownloader,
  type VideoIngestionResult,
} from "../src/lib/assets/VideoMediaIngestion";
import {
  selectSceneMedia,
  summarizeSceneMediaPlan,
} from "../src/lib/assets/SceneMediaSelection";
import { VisualMediaAiBudgetExceededError } from "../src/lib/assets/VisualMediaAdmissionPolicy";
import {
  getFFmpegSceneVideoConfig,
  type FFmpegSceneVideoConfig,
} from "../src/lib/video/providers/VideoProviderConfig";
import type {
  ProcessRunResult,
  VideoAssemblyProcessRunner,
} from "../src/lib/assembly/providers/FFmpegVideoAssemblyProvider";
import type { RuntimeStorageContext } from "../src/lib/runtime/RuntimeStoragePaths";
import type { MediaType, MediaRightsStatus } from "../src/types/asset";
import type { ResearchMediaCandidate } from "../src/types/research";
import type { VisualScene } from "../src/types/visual";

const NOW = "2026-08-29T00:00:00.000Z";
const FIVE_BE_DIR =
  "data/projects/fatih-sultan-mehmet-ve-i-stanbul-un-fethi-5be83a84-3d83-49f3-8ef2-854543359ca1";
const FIVE_BE_COMBINED_PNG_SHA256 =
  "cc204e21ad110f0d6f145b2e6eb2318e77647aa30ef0eaa81ef789475686ab49";

let count = 0;
async function scenario(name: string, fn: () => void | Promise<void>) {
  await fn();
  count += 1;
  if (process.env.SMOKE_TRACE === "1") console.log(`PASS ${count}: ${name}`);
}

// --------------------------------------------------------------------------- fixtures

class ActualProcessRunner implements VideoAssemblyProcessRunner {
  readonly diagnostics: string[] = [];

  async run(
    executable: string,
    args: readonly string[],
    options: { timeoutMs: number; maxOutputBytes: number },
  ): Promise<ProcessRunResult> {
    const result = spawnSync(executable, [...args], {
      encoding: "utf8",
      maxBuffer: options.maxOutputBytes,
      shell: false,
      timeout: options.timeoutMs,
      windowsHide: true,
    });
    this.diagnostics.push(result.stderr ?? "");
    return {
      exitCode: result.status,
      signal: result.signal as NodeJS.Signals | null,
      stdout: result.stdout ?? "",
      timedOut: Boolean(
        result.error && "code" in result.error && result.error.code === "ETIMEDOUT",
      ),
      failed: Boolean(result.error),
    };
  }
}

function fixtureDownloader(bytes: Buffer, contentType?: string): {
  impl: VideoDownloader;
  calls: string[];
} {
  const calls: string[] = [];
  return {
    calls,
    impl: {
      async download(url: string) {
        calls.push(url);
        return { bytes, contentType };
      },
    },
  };
}

function makeFixtureClip(ffmpegPath: string, seconds: number): Buffer {
  const out = path.join(os.tmpdir(), `atolye-faz3-fixture-${randomUUID()}.mp4`);
  const result = spawnSync(
    ffmpegPath,
    [
      "-hide_banner", "-loglevel", "error", "-nostdin", "-y",
      "-f", "lavfi",
      "-i", `testsrc=duration=${seconds}:size=480x360:rate=30`,
      "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
      "-t", String(seconds),
      out,
    ],
    { timeout: 60_000, windowsHide: true },
  );
  if (result.status !== 0) {
    throw new Error(`fixture ffmpeg failed: ${result.stderr?.toString() ?? "unknown"}`);
  }
  const bytes = fs.readFileSync(out);
  fs.rmSync(out, { force: true });
  return bytes;
}

function videoCandidate(over: Partial<ResearchMediaCandidate> = {}): ResearchMediaCandidate {
  return {
    id: over.id ?? "wikimedia-commons:faz3-video-fixture",
    mediaType: "video",
    title: over.title ?? "Fall of Constantinople 1453 archival footage",
    provider: "wikimedia-commons",
    sourceUrl:
      "sourceUrl" in over
        ? (over.sourceUrl as string)
        : "https://commons.wikimedia.org/wiki/File:Fall_of_Constantinople.webm",
    mediaUrl:
      "mediaUrl" in over
        ? over.mediaUrl
        : "https://upload.wikimedia.org/wikipedia/commons/1/1a/Fall_of_Constantinople.mp4",
    license: "license" in over ? over.license : "CC BY-SA 4.0",
    attribution: over.attribution ?? "Historical Archive / Wikimedia Commons",
    rightsStatus: over.rightsStatus ?? "open-license",
    admissible: over.admissible ?? true,
    width: over.width ?? 480,
    height: over.height ?? 360,
    durationSeconds: over.durationSeconds,
    segmentStartSeconds: over.segmentStartSeconds,
    segmentEndSeconds: over.segmentEndSeconds,
    queryTerms: over.queryTerms ?? ["Fall of Constantinople"],
    association: over.association ?? "event",
    confidence: over.confidence ?? 0.9,
    discoveredAt: NOW,
  };
}

function selectionScene(sceneId: number, keywords: string[]): VisualScene {
  return {
    sceneId,
    visualPrompt: keywords.join(" "),
    animationPrompt: "slow push in",
    style: "documentary",
    searchKeywords: keywords,
  };
}

let candidateSeq = 0;
function selectionCandidate(
  mediaType: MediaType,
  terms: string[],
  opts: { admissible?: boolean; rightsStatus?: MediaRightsStatus; license?: string } = {},
): ResearchMediaCandidate {
  candidateSeq += 1;
  const id = `wikimedia-commons:sel-${String(candidateSeq).padStart(3, "0")}`;
  return {
    id,
    mediaType,
    title: terms.join(" "),
    provider: "wikimedia-commons",
    sourceUrl: `https://commons.wikimedia.org/wiki/File:${id}.jpg`,
    mediaUrl: `https://upload.wikimedia.org/wikipedia/commons/${id}.${mediaType === "video" ? "mp4" : "jpg"}`,
    license: opts.license ?? "CC BY-SA 4.0",
    attribution: "Archive / Wikimedia Commons",
    rightsStatus: opts.rightsStatus ?? "open-license",
    admissible: opts.admissible ?? true,
    queryTerms: terms,
    association: "event",
    confidence: 0.8,
    discoveredAt: NOW,
  };
}

// --------------------------------------------------------------------------- run

let ctx: RuntimeStorageContext;
let slug: string;
let projectId: string;
let config: FFmpegSceneVideoConfig;
let clip8s: Buffer;

async function ingest(
  candidate: ResearchMediaCandidate,
  downloader: VideoDownloader,
  sceneId?: number,
): Promise<VideoIngestionResult> {
  return ingestVideoCandidate({
    candidate,
    projectSlug: slug,
    runtimeStorageContext: ctx,
    sceneId,
    downloader,
    runner: new ActualProcessRunner(),
    loadConfig: () => config,
    now: () => NOW,
  });
}

async function run() {
  config = getFFmpegSceneVideoConfig();
  clip8s = makeFixtureClip(config.ffmpegPath, 8);
  const project = await ProjectManager.createProject(`faz3 video ingestion ${randomUUID().slice(0, 8)}`);
  slug = project.slug;
  projectId = project.id;
  void projectId;

  await scenario("policy constants are frozen and sane", () => {
    assert.throws(() => {
      (videoIngestionPolicy as { minSegmentSeconds: number }).minSegmentSeconds = 99;
    });
    assert.ok(videoIngestionPolicy.minSegmentSeconds >= 1);
    assert.ok(videoIngestionPolicy.maxSegmentSeconds > videoIngestionPolicy.minSegmentSeconds);
    assert.ok(videoIngestionPolicy.allowedMediaHostSuffixes.includes("upload.wikimedia.org"));
  });

  // A ---------------------------------------------------------------------
  await scenario("A: admissible real video candidate -> ingest PASS", async () => {
    const dl = fixtureDownloader(clip8s, "video/mp4");
    const result = await ingest(videoCandidate(), dl.impl, 1);
    assert.equal(result.success, true, result.success ? "" : result.detail);
    if (!result.success) return;
    assert.equal(dl.calls.length, 1);
    assert.equal(result.asset.mediaOrigin, "real");
    assert.equal(result.asset.mediaType, "video");
    assert.equal(result.asset.mimeType, "video/mp4");
    assert.equal(result.asset.width, 1920);
    assert.equal(result.asset.height, 1080);
    assert.equal(result.asset.frameRate, 30);
    assert.ok(Math.abs(result.asset.durationSeconds - 8) <= 0.75);
    // the rendered file exists and is a valid MP4 under the project video dir
    const stored = VideoStorage.inspectStoredMp4(slug, result.asset.filePath, config.maxOutputBytes, ctx);
    assert.equal(stored.byteLength, result.asset.byteLength);
    // normalises to the common scene-video contract
    const sceneVideo = ingestedVideoToSceneVideoSuccess(result.asset, { sceneId: 1 });
    assert.equal(sceneVideo.mimeType, "video/mp4");
    assert.equal(sceneVideo.status, "generated");
    assert.equal(sceneVideo.generationMode, "production");
  });

  // B ---------------------------------------------------------------------
  await scenario("B: restricted licence -> FAIL-CLOSED before any download", async () => {
    const dl = fixtureDownloader(clip8s, "video/mp4");
    const result = await ingest(
      videoCandidate({ license: "CC BY-NC 4.0", rightsStatus: "restricted", admissible: false }),
      dl.impl,
    );
    assert.equal(result.success, false);
    if (result.success) return;
    assert.equal(result.reason, "rights-not-admissible");
    assert.equal(dl.calls.length, 0);
  });

  // C ---------------------------------------------------------------------
  await scenario("C: unknown licence (even if flagged admissible) -> FAIL-CLOSED", async () => {
    const dl = fixtureDownloader(clip8s, "video/mp4");
    const result = await ingest(
      videoCandidate({ license: "Some Private Museum Terms", rightsStatus: "unknown", admissible: true }),
      dl.impl,
    );
    assert.equal(result.success, false);
    if (result.success) return;
    assert.equal(result.reason, "rights-not-admissible");
    assert.equal(dl.calls.length, 0);
  });

  // D ---------------------------------------------------------------------
  await scenario("D: missing sourceUrl -> reject, no download", async () => {
    const dl = fixtureDownloader(clip8s, "video/mp4");
    const result = await ingest(videoCandidate({ sourceUrl: "" }), dl.impl);
    assert.equal(result.success, false);
    if (result.success) return;
    assert.equal(result.reason, "missing-source-url");
    assert.equal(dl.calls.length, 0);
  });

  // E ---------------------------------------------------------------------
  await scenario("E: missing / non-https mediaUrl -> reject, no download", async () => {
    const dl = fixtureDownloader(clip8s, "video/mp4");
    const missing = await ingest(videoCandidate({ mediaUrl: undefined }), dl.impl);
    assert.equal(missing.success, false);
    if (!missing.success) assert.equal(missing.reason, "missing-media-url");

    const insecure = await ingest(
      videoCandidate({ mediaUrl: "http://upload.wikimedia.org/x.mp4" }),
      dl.impl,
    );
    assert.equal(insecure.success, false);
    if (!insecure.success) assert.equal(insecure.reason, "media-url-not-https");

    const badHost = await ingest(
      videoCandidate({ mediaUrl: "https://randomcdn.example.com/x.mp4" }),
      dl.impl,
    );
    assert.equal(badHost.success, false);
    if (!badHost.success) assert.equal(badHost.reason, "media-host-not-allowed");

    assert.equal(dl.calls.length, 0);
  });

  // F ---------------------------------------------------------------------
  await scenario("F: non-video Content-Type -> reject after download", async () => {
    const dl = fixtureDownloader(clip8s, "text/html; charset=utf-8");
    const result = await ingest(videoCandidate(), dl.impl);
    assert.equal(result.success, false);
    if (result.success) return;
    assert.equal(result.reason, "mime-not-video");
    assert.equal(dl.calls.length, 1);
  });

  // G ---------------------------------------------------------------------
  await scenario("G: corrupt / non-video bytes -> reject at source probe", async () => {
    const dl = fixtureDownloader(Buffer.from("this is definitely not an mp4 container"), "video/mp4");
    const result = await ingest(videoCandidate(), dl.impl);
    assert.equal(result.success, false);
    if (result.success) return;
    assert.ok(
      ["source-probe-failed", "source-container-not-allowed", "source-codec-not-allowed"].includes(
        result.reason,
      ),
      result.reason,
    );
  });

  // H ---------------------------------------------------------------------
  await scenario("H: invalid segment (reversed, and exceeding source) -> reject", async () => {
    const dlReversed = fixtureDownloader(clip8s, "video/mp4");
    const reversed = await ingest(
      videoCandidate({ segmentStartSeconds: 5, segmentEndSeconds: 3 }),
      dlReversed.impl,
    );
    assert.equal(reversed.success, false);
    if (!reversed.success) assert.equal(reversed.reason, "invalid-segment");
    assert.equal(dlReversed.calls.length, 0, "reversed segment must be rejected before download");

    const dlExceeds = fixtureDownloader(clip8s, "video/mp4");
    const exceeds = await ingest(
      videoCandidate({ segmentStartSeconds: 1, segmentEndSeconds: 30 }),
      dlExceeds.impl,
    );
    assert.equal(exceeds.success, false);
    if (!exceeds.success) assert.equal(exceeds.reason, "segment-exceeds-source");

    // pure validators agree
    assert.equal(validateSegment({ segmentStartSeconds: 5, segmentEndSeconds: 3 }).ok, false);
    assert.equal(
      validateSegment({ segmentStartSeconds: 0, segmentEndSeconds: 3 }, 2).ok,
      false,
    );
  });

  // I ---------------------------------------------------------------------
  await scenario("I: valid segment -> deterministic MP4 on disk", async () => {
    const dl = fixtureDownloader(clip8s, "video/mp4");
    const candidate = videoCandidate({
      id: "wikimedia-commons:faz3-segment",
      segmentStartSeconds: 2,
      segmentEndSeconds: 5,
    });
    const result = await ingest(candidate, dl.impl, 4);
    assert.equal(result.success, true, result.success ? "" : result.detail);
    if (!result.success) return;
    assert.equal(result.asset.segmentStartSeconds, 2);
    assert.equal(result.asset.segmentEndSeconds, 5);
    assert.ok(Math.abs(result.asset.durationSeconds - 3) <= 0.75, `duration ${result.asset.durationSeconds}`);
    assert.equal(result.asset.id, deriveVideoAssetIdentity(candidate));
    const stored = VideoStorage.inspectStoredMp4(slug, result.asset.filePath, config.maxOutputBytes, ctx);
    assert.ok(stored.byteLength > 0);
  });

  // J ---------------------------------------------------------------------
  await scenario("J: checksum is sha256 of source bytes and stable across runs", async () => {
    const expected = createHash("sha256").update(clip8s).digest("hex");
    const first = await ingest(videoCandidate({ id: "wikimedia-commons:faz3-checksum" }), fixtureDownloader(clip8s, "video/mp4").impl, 5);
    const second = await ingest(videoCandidate({ id: "wikimedia-commons:faz3-checksum" }), fixtureDownloader(clip8s, "video/mp4").impl, 6);
    assert.equal(first.success && second.success, true);
    if (!first.success || !second.success) return;
    assert.equal(first.asset.checksum, expected);
    assert.equal(second.asset.checksum, expected);
    assert.equal(first.asset.id, second.asset.id);
  });

  // K ---------------------------------------------------------------------
  await scenario("K: provenance preserved (source/media URL, licence, attribution, rights)", async () => {
    const candidate = videoCandidate({
      id: "wikimedia-commons:faz3-provenance",
      license: "CC BY 4.0",
      attribution: "Bibliothèque nationale de France / Wikimedia Commons",
    });
    const result = await ingest(candidate, fixtureDownloader(clip8s, "video/mp4").impl, 7);
    assert.equal(result.success, true, result.success ? "" : result.detail);
    if (!result.success) return;
    assert.equal(result.asset.sourceUrl, candidate.sourceUrl);
    assert.equal(result.asset.mediaUrl, candidate.mediaUrl);
    assert.equal(result.asset.license, "CC BY 4.0");
    assert.equal(result.asset.attribution, "Bibliothèque nationale de France / Wikimedia Commons");
    assert.equal(result.asset.rightsStatus, "open-license");
    assert.equal(result.asset.sourceName, "wikimedia-commons");
    assert.equal(result.asset.provider, "wikimedia-commons");
    assert.equal(typeof result.asset.discoveredAt, "string");
    assert.equal(result.asset.sourceDurationSeconds > 0, true);
    // pure preflight agrees
    const pf = validateVideoCandidateForIngestion(candidate);
    assert.equal(pf.ok, true);
  });

  // L ---------------------------------------------------------------------
  await scenario("L: 16 scenes -> 2 real video + 10 real photo + 4 AI", () => {
    const videoTerms = [["archival newsreel footage"], ["documentary reenactment clip"]];
    const photoTerms = [
      ["romanus gate breach"], ["golden horn harbour"], ["bosphorus strait fortress"],
      ["ottoman bombard cannon"], ["genoese galata tower"], ["orthodox liturgy hagia"],
      ["byzantine wall mosaic"], ["janissary infantry corps"], ["siege ladder assault"],
      ["harbour boom chain"],
    ];
    const candidates = [
      ...videoTerms.map((t) => selectionCandidate("video", t)),
      ...photoTerms.map((t) => selectionCandidate("photo", t)),
    ];
    const scenes: VisualScene[] = [];
    videoTerms.forEach((t, i) => scenes.push(selectionScene(i + 1, t)));
    photoTerms.forEach((t, i) => scenes.push(selectionScene(i + 3, t)));
    for (let s = 13; s <= 16; s += 1) scenes.push(selectionScene(s, [`isolated abstract moment ${s}`]));

    const plan = selectSceneMedia({ scenes, candidates });
    assert.equal(plan.realVideoScenes, 2);
    assert.equal(plan.realPhotoScenes, 10);
    assert.equal(plan.aiImageScenes, 4);
    assert.equal(plan.assignments.length, 16);
    assert.equal(new Set(plan.usedCandidateIds).size, 12);
    assert.equal(summarizeSceneMediaPlan(plan).withinAiBudget, true);
  });

  // M ---------------------------------------------------------------------
  await scenario("M: 16 scenes -> 12 real media + 4 AI (PASS at the cap)", () => {
    const terms = Array.from({ length: 12 }, (_, i) => [`distinct subject alpha${i}`, `distinct subject beta${i}`]);
    const candidates = terms.map((t) => selectionCandidate("photo", t));
    const scenes = [
      ...terms.map((t, i) => selectionScene(i + 1, t)),
      ...Array.from({ length: 4 }, (_, i) => selectionScene(i + 13, [`unmatched void ${i}`])),
    ];
    const plan = selectSceneMedia({ scenes, candidates });
    assert.equal(plan.realPhotoScenes, 12);
    assert.equal(plan.realVideoScenes, 0);
    assert.equal(plan.aiImageScenes, 4);
    assert.equal(summarizeSceneMediaPlan(plan).withinAiBudget, true);
  });

  // N ---------------------------------------------------------------------
  await scenario("N: 16 scenes -> 11 real media + 5 AI => VISUAL_AI_IMAGE_BUDGET_EXCEEDED", () => {
    const terms = Array.from({ length: 11 }, (_, i) => [`unique topic one${i}`, `unique topic two${i}`]);
    const candidates = terms.map((t) => selectionCandidate("photo", t));
    const scenes = [
      ...terms.map((t, i) => selectionScene(i + 1, t)),
      ...Array.from({ length: 5 }, (_, i) => selectionScene(i + 12, [`no match here ${i}`])),
    ];
    assert.throws(
      () => selectSceneMedia({ scenes, candidates }),
      (error: unknown) =>
        error instanceof VisualMediaAiBudgetExceededError &&
        error.maxAiImages === 4 &&
        error.sceneId === 16,
    );
  });

  // O ---------------------------------------------------------------------
  await scenario("O: same input twice -> identical selection plan + asset identity", async () => {
    const terms = Array.from({ length: 6 }, (_, i) => [`repeatable subject ${i} one`, `repeatable subject ${i} two`]);
    const candidates = terms.map((t) => selectionCandidate("photo", t));
    const scenes = [
      ...terms.map((t, i) => selectionScene(i + 1, t)),
      ...Array.from({ length: 10 }, (_, i) => selectionScene(i + 7, [`filler ${i}`])),
    ];
    const shape = (p: ReturnType<typeof selectSceneMedia>) =>
      p.assignments.map((a) => [a.sceneId, a.kind, a.candidate?.id ?? null]);
    assert.deepEqual(
      shape(selectSceneMedia({ scenes, candidates, maxAiImages: Number.POSITIVE_INFINITY })),
      shape(selectSceneMedia({ scenes, candidates, maxAiImages: Number.POSITIVE_INFINITY })),
    );
    const candidate = videoCandidate({ id: "wikimedia-commons:faz3-determinism", segmentStartSeconds: 1, segmentEndSeconds: 4 });
    assert.equal(deriveVideoAssetIdentity(candidate), deriveVideoAssetIdentity(candidate));
    const a = await ingest(candidate, fixtureDownloader(clip8s, "video/mp4").impl, 8);
    const b = await ingest(candidate, fixtureDownloader(clip8s, "video/mp4").impl, 9);
    assert.equal(a.success && b.success && a.asset.id === b.asset.id, true);
  });

  // P ---------------------------------------------------------------------
  await scenario("P: cross-scene video reuse is forbidden", () => {
    const candidates = [selectionCandidate("video", ["archival newsreel footage"])];
    const scenes = Array.from({ length: 16 }, (_, i) =>
      selectionScene(i + 1, ["archival newsreel footage"]),
    );
    const plan = selectSceneMedia({ scenes, candidates, maxAiImages: Number.POSITIVE_INFINITY });
    assert.equal(plan.realVideoScenes, 1);
    assert.equal(plan.usedCandidateIds.length, 1);
    assert.equal(plan.aiImageScenes, 15);
    const videoAssignments = plan.assignments.filter((a) => a.kind === "real-video");
    assert.equal(videoAssignments.length, 1);
  });

  // Q ---------------------------------------------------------------------
  await scenario("Q: existing 5be83a84 artifacts unchanged", () => {
    const imagesDir = path.join(process.cwd(), FIVE_BE_DIR, "assets", "images");
    const pngs = fs
      .readdirSync(imagesDir)
      .filter((f) => f.toLowerCase().endsWith(".png"))
      .sort();
    assert.equal(pngs.length, 16);
    const hash = createHash("sha256");
    for (const file of pngs) hash.update(fs.readFileSync(path.join(imagesDir, file)));
    assert.equal(hash.digest("hex"), FIVE_BE_COMBINED_PNG_SHA256);

    // no tracked drift under data/projects from any Faz-3 change
    const diff = spawnSync("git", ["diff", "--name-only", "HEAD", "--", "data/projects"], {
      cwd: process.cwd(),
      encoding: "utf8",
      windowsHide: true,
    });
    const drifted = (diff.stdout ?? "")
      .split(/\r?\n/)
      .filter((line) => line.trim() && !line.includes("data/projects/unknown/ai-usage.json"));
    assert.deepEqual(drifted, [], `unexpected tracked drift: ${drifted.join(", ")}`);
  });

  console.log(`Faz 3 video media ingestion smoke: PASS (${count} scenarios)`);
  emitSmokeResult("faz3-video-media-ingestion", count);
}

async function main() {
  const ffmpegPath = process.env.FFMPEG_EXECUTABLE?.trim() || process.env.FFMPEG_PATH;
  const ffprobePath = process.env.FFPROBE_EXECUTABLE?.trim() || process.env.FFPROBE_PATH;
  if (!ffmpegPath || !ffprobePath) {
    throw new Error("Faz 3 smoke requires FFMPEG_PATH / FFPROBE_PATH (or *_EXECUTABLE) to be set.");
  }
  await withCanonicalSmokeRuntime(
    {
      name: "faz3-video-media-ingestion",
      operationType: "faz3-video-ingestion-smoke",
      environment: {
        VIDEO_PROVIDER: undefined,
        FFMPEG_PATH: ffmpegPath,
        FFPROBE_PATH: ffprobePath,
        FFMPEG_EXECUTABLE: undefined,
        FFPROBE_EXECUTABLE: undefined,
      },
    },
    async (runtime) => {
      ctx = runtime.runtimeStorageContext;
      assert.notEqual(
        path.resolve(ctx.projectsRoot),
        path.resolve(process.cwd(), "data", "projects"),
        "Faz 3 smoke fixture root must not resolve to repository data/projects.",
      );
      await run();
    },
  );
}

void main();
