import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { buildProductionExecutionIdempotencyIdentity, defaultProductionExecutionIdempotencyPolicy } from "../src/lib/production/ProductionExecutionIdempotency";
import { buildProductionExecutionTransactionPlan, defaultProductionExecutionTransactionPolicy } from "../src/lib/production/ProductionExecutionTransaction";
import { buildProductionOperationJournalEvent, defaultProductionOperationJournalPolicy } from "../src/lib/production/ProductionOperationJournal";
import { ProductionExecutionFilePersistenceAdapter, type TrustedProductionExecutionPersistenceFileOperations } from "../src/lib/production/ProductionExecutionPersistence";
import { defaultProductionControlledExecutionGatewayPolicy } from "../src/lib/production/ProductionControlledExecutionGateway";
import type { ProductionExecutionAuthorizationResult } from "../src/types/productionExecutionAuthorization";
import type { ProductionExecutionConfirmationValidationResult } from "../src/types/productionExecutionConfirmation";
import type { ProductionExecutionIdempotencyPolicy, ProductionExecutionIdempotencyRecord, ProductionExecutionIdempotencyReservationRequest } from "../src/types/productionExecutionIdempotency";
import type { ProductionExecutionMutationIntent, ProductionExecutionTransactionPlan } from "../src/types/productionExecutionTransaction";
import type { ProductionOperationJournalEvent } from "../src/types/productionOperationJournal";

const now="2026-07-12T12:00:00.000Z",operation="pipeline.stage.retry.preview";
const idempotencyPolicy:ProductionExecutionIdempotencyPolicy={...defaultProductionExecutionIdempotencyPolicy,enabled:true,policyVersion:"idempotency-policy-v1"};
const authorization:ProductionExecutionAuthorizationResult={schemaVersion:"1",decisionId:"authorization-1",decision:"allow",authorized:true,reasonCode:"AUTHORIZED",reason:"safe",evaluatedAt:now,requestId:"request-1",idempotencyKey:"execution-1",executionFingerprint:"snapshot-1",actorId:"actor-1",actorType:"user",projectSlug:"project-1",operation,action:"retry-stage",stage:"script",requiredCapabilities:[],grantedCapabilities:[],missingCapabilities:[],policyVersion:"authorization-policy-v1",risk:"high",requiresConfirmation:true,requiredConfirmationLevel:"high",evidence:[]};
const confirmation:ProductionExecutionConfirmationValidationResult={schemaVersion:"1",decision:"valid",valid:true,reasonCode:"CONFIRMATION_VALID",reason:"safe",evaluatedAt:now,confirmationId:"confirmation-1",confirmationRequestId:"confirmation-request-1",authorizationDecisionId:"authorization-1",requestId:"request-1",idempotencyKey:"execution-1",actorId:"actor-1",projectSlug:"project-1",operation,action:"retry-stage",stage:"script",riskLevel:"high",requiredConfirmationLevel:"high",providedConfirmationLevel:"high",bindingMatches:true,bindingFingerprint:"confirmation-binding-1",expired:false,singleUse:true,consumed:false,policyVersion:"authorization-policy-v1",evidence:[]};
const builtIdentity=buildProductionExecutionIdempotencyIdentity({authorization,confirmation},{evaluatedAt:now,policy:idempotencyPolicy});
assert.equal(builtIdentity.ok,true);const identity=builtIdentity.identity!;
const idempotency:ProductionExecutionIdempotencyRecord={schemaVersion:"1",recordId:"record-1",identityFingerprint:identity.identityFingerprint,idempotencyKey:identity.idempotencyKey,requestId:identity.requestId,executionFingerprint:identity.executionFingerprint,bindingFingerprint:identity.bindingFingerprint,actorId:identity.actorId,projectSlug:identity.projectSlug,operation:identity.operation,action:identity.action,stage:identity.stage,authorizationDecisionId:identity.authorizationDecisionId,confirmationRequestId:identity.confirmationRequestId,confirmationId:identity.confirmationId,policyVersion:identity.policyVersion,riskLevel:identity.riskLevel,state:"reserved",attempt:1,maxAttempts:3,createdAt:now,updatedAt:now,reservedAt:now,evidence:[],integrity:{algorithm:"stable-production-id-v1",fingerprint:identity.identityFingerprint,version:1}};
const reservation:ProductionExecutionIdempotencyReservationRequest={schemaVersion:"1",identity,authorization,confirmation,requestedAt:now,expectedInitialState:"reserved",attempt:1,maxAttempts:3,reservationTtlSeconds:idempotencyPolicy.reservationTtlSeconds,policyContext:{source:"server",environment:"test"},metadata:{source:"server"}};
const resource:ProductionExecutionMutationIntent={resourceType:"json",logicalResourceId:"output",relativeTarget:"data/output.json",expectedCurrentFingerprint:"old",proposedFingerprint:"new",writeMode:"replace",contentKind:"json",requiredValidation:["schema"],manifestDependency:true,sensitive:false,allowed:true};
const transactionFor=(record:ProductionExecutionIdempotencyRecord=idempotency,mutation:ProductionExecutionMutationIntent=resource)=>buildProductionExecutionTransactionPlan({record,authorizationValid:true,confirmationValid:true,reservationValid:true,resources:[mutation]},{plannedAt:now,policy:{...defaultProductionExecutionTransactionPolicy,enabled:true}}).plan!;
const transaction=transactionFor();
const otherTransaction=transactionFor(idempotency,{...resource,proposedFingerprint:"other"});
const journalPolicy={...defaultProductionOperationJournalPolicy,enabled:true};
const journal:ProductionOperationJournalEvent[]=["operation-reserved","operation-prepared","operation-queued","operation-started","operation-succeeded"].map((eventType,index)=>buildProductionOperationJournalEvent({sequence:index+1,eventType,occurredAt:new Date(Date.parse(now)+index*1000).toISOString(),operationId:transaction.operationId,transactionId:transaction.transactionId,idempotencyRecordId:idempotency.recordId,requestId:identity.requestId,idempotencyKey:identity.idempotencyKey,actorId:identity.actorId,projectSlug:identity.projectSlug,operation:identity.operation,action:identity.action,stage:identity.stage,attempt:1,evidence:["safe"],correlation:{correlationId:"correlation-1",authorizationDecisionId:identity.authorizationDecisionId,confirmationId:identity.confirmationId,executionFingerprint:identity.executionFingerprint,bindingFingerprint:identity.bindingFingerprint,policyVersion:identity.policyVersion}},{policy:journalPolicy}).event!);

let scenarios=0;async function scenario(name:string,run:()=>void|Promise<void>){await run();scenarios++;void name}
async function main(){const root=await fs.mkdtemp(path.join(os.tmpdir(),"atolye-production-persistence-"));try{
 const adapter=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:root});
 for(const [kind,key,value] of [["transaction","transaction-1",transaction],["journal","journal-1",journal],["idempotency","record-1",idempotency],["reservation","reservation-1",reservation]] as const)await scenario(`create/read ${kind}`,async()=>{const write=await adapter.write(kind,key,value);assert.equal(write.status,"created");const read=await adapter.read(kind,key);assert.equal(read.status,"found");if(read.status==="found")assert.deepEqual(read.value,value)});
 await scenario("idempotent replay",async()=>assert.equal((await adapter.write("idempotency","record-1",structuredClone(idempotency))).status,"idempotent-replay"));
 await scenario("key-order replay",async()=>{const reordered={...idempotency,integrity:{version:1,fingerprint:identity.identityFingerprint,algorithm:"stable-production-id-v1" as const}};assert.equal((await adapter.write("idempotency","record-1",reordered)).status,"idempotent-replay")});
 await scenario("conflict",async()=>assertFailure(await adapter.write("idempotency","record-1",{...idempotency,state:"prepared"}),"PERSISTENCE_EXISTING_RECORD_CONFLICT"));
 for(const [name,kind,value] of [["transaction","transaction",{...transaction,operationId:""}],["journal","journal",[{...journal[0],eventId:""}]],["idempotency","idempotency",{...idempotency,actorId:""}],["reservation","reservation",{...reservation,authorization:{...authorization,decisionId:""}}]] as const)await scenario(`malformed ${name}`,async()=>assertFailure(await adapter.write(kind,`bad-${name}`,value as never),"PERSISTENCE_INVALID_INPUT"));
 await scenario("bad transaction steps",async()=>assertFailure(await adapter.write("transaction","bad-steps",{...transaction,steps:[]} as ProductionExecutionTransactionPlan),"PERSISTENCE_INVALID_INPUT"));
 await scenario("bad transaction binding",async()=>assertFailure(await adapter.write("transaction","bad-binding",{...transaction,projectSlug:"../bad"}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("bad transaction integrity",async()=>assertFailure(await adapter.write("transaction","bad-integrity",{...transaction,integrity:{...transaction.integrity,fingerprint:""}}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("tampered transaction fingerprint",async()=>assertFailure(await adapter.write("transaction","tampered-fingerprint",{...transaction,integrity:{...transaction.integrity,fingerprint:"non-empty-tampered"}}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("stale transaction id integrity",async()=>assertFailure(await adapter.write("transaction","stale-transaction-id",{...transaction,transactionId:"changed-transaction"}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("stale operation id integrity",async()=>assertFailure(await adapter.write("transaction","stale-operation-id",{...transaction,operationId:"changed-operation"}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("stale transaction binding integrity",async()=>assertFailure(await adapter.write("transaction","stale-binding",{...transaction,executionFingerprint:"changed-execution-fingerprint"}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("stale transaction step integrity",async()=>assertFailure(await adapter.write("transaction","stale-step",{...transaction,steps:transaction.steps.map((step,index)=>index===0?{...step,expectedOutcome:"changed-outcome"}:step)}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("copied transaction integrity",async()=>assertFailure(await adapter.write("transaction","copied-integrity",{...transaction,integrity:otherTransaction.integrity}),"PERSISTENCE_INVALID_INPUT"));
 for(const [name,record] of [["actor",{...idempotency,actorId:"actor-2"}],["project",{...idempotency,projectSlug:"project-2"}],["action",{...idempotency,action:"resume-stage"}],["stage",{...idempotency,stage:"visuals"}],["binding",{...idempotency,bindingFingerprint:"binding-2"}]] as const)await scenario(`stale idempotency ${name} integrity`,async()=>assertFailure(await adapter.write("idempotency",`stale-${name}`,record),"PERSISTENCE_INVALID_INPUT"));
 const alternateAuthorization={...authorization,actorId:"actor-2"};const alternateConfirmation={...confirmation,actorId:"actor-2",bindingFingerprint:"alternate-binding"};const alternateIdentity=buildProductionExecutionIdempotencyIdentity({authorization:alternateAuthorization,confirmation:alternateConfirmation},{evaluatedAt:now,policy:idempotencyPolicy}).identity!;
 await scenario("copied idempotency fingerprint",async()=>assertFailure(await adapter.write("idempotency","copied-idempotency",{...idempotency,identityFingerprint:alternateIdentity.identityFingerprint,integrity:{...idempotency.integrity,fingerprint:alternateIdentity.identityFingerprint}}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("bad reservation confirmation",async()=>assertFailure(await adapter.write("reservation","bad-confirmation",{...reservation,confirmation:{...confirmation,bindingFingerprint:""}}),"PERSISTENCE_INVALID_INPUT"));
 await scenario("unsupported schema",async()=>assertFailure(await adapter.write("transaction","schema",{...transaction,schemaVersion:"2"} as never),"PERSISTENCE_SCHEMA_UNSUPPORTED"));
 await scenario("corrupt json",async()=>{await fs.mkdir(path.join(root,"transactions"),{recursive:true});await fs.writeFile(path.join(root,"transactions","corrupt.json"),"{","utf8");assertReadFailure(await adapter.read("transaction","corrupt"),"PERSISTENCE_RECORD_CORRUPT")});
 await scenario("corrupt parsed record",async()=>{await fs.writeFile(path.join(root,"transactions","corrupt-shape.json"),'{"schemaVersion":"1","transactionId":"x"}',"utf8");assertReadFailure(await adapter.read("transaction","corrupt-shape"),"PERSISTENCE_RECORD_CORRUPT")});
 await scenario("corrupt transaction integrity record",async()=>{await fs.writeFile(path.join(root,"transactions","corrupt-integrity.json"),JSON.stringify({...transaction,integrity:{...transaction.integrity,fingerprint:"non-empty-tampered"}}),"utf8");assertReadFailure(await adapter.read("transaction","corrupt-integrity"),"PERSISTENCE_RECORD_CORRUPT")});
 await scenario("corrupt idempotency integrity record",async()=>{await fs.mkdir(path.join(root,"idempotency"),{recursive:true});await fs.writeFile(path.join(root,"idempotency","corrupt-integrity.json"),JSON.stringify({...idempotency,actorId:"actor-2"}),"utf8");assertReadFailure(await adapter.read("idempotency","corrupt-integrity"),"PERSISTENCE_RECORD_CORRUPT")});

 const pathKeys=["../escape","..\\escape","/absolute","c:\\absolute","a/b","a\\b","%2e%2e",".","..",".leading","trailing."," leading","trailing ","con","nul","com1","lpt9","Uppercase"];
 for(const key of pathKeys)await scenario(`reject key ${key}`,async()=>assertFailure(await adapter.write("transaction",key,transaction),"PERSISTENCE_INVALID_INPUT"));

 await scenario("missing directory",async()=>{const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:path.join(root,"missing"),createRootDirectory:false});assertFailure(await x.write("transaction","missing",transaction),"PERSISTENCE_DIRECTORY_MISSING")});
 await scenario("directory permission",async()=>{const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:path.join(root,"denied"),createRootDirectory:false,trustedFileOperations:operations({access:async()=>{throw codeError("EACCES")}})});assertFailure(await x.write("transaction","denied",transaction),"PERSISTENCE_READ_FAILED")});
 await scenario("read permission",async()=>{const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:root,trustedFileOperations:operations({readFile:async()=>{throw codeError("EACCES")}})});assertReadFailure(await x.read("transaction","transaction-1"),"PERSISTENCE_READ_FAILED")});
 await scenario("temp write failure",async()=>{const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:path.join(root,"write-fail"),trustedFileOperations:operations({writeFile:async()=>{throw codeError("EIO")}})});assertFailure(await x.write("transaction","write-fail",transaction),"PERSISTENCE_TEMP_WRITE_FAILED")});
 await scenario("temp read failure",async()=>{const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:path.join(root,"read-fail"),trustedFileOperations:operations({readFile:async(file,encoding)=>file.endsWith(".tmp")?Promise.reject(codeError("EIO")):fs.readFile(file,encoding)})});assertFailure(await x.write("transaction","read-fail",transaction),"PERSISTENCE_TEMP_VALIDATION_FAILED")});
 await scenario("temp validation failure",async()=>{const dir=path.join(root,"validation-fail");const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir,trustedFileOperations:operations({readFile:async(file,encoding)=>file.endsWith(".tmp")?"{}":fs.readFile(file,encoding)})});assertFailure(await x.write("transaction","validation-fail",transaction),"PERSISTENCE_TEMP_VALIDATION_FAILED");assert.equal((await fs.readdir(path.join(dir,"transactions"))).some(f=>f.endsWith(".tmp")),false)});
 await scenario("commit failure",async()=>{const dir=path.join(root,"commit-fail");const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir,trustedFileOperations:operations({link:async()=>{throw codeError("EIO")}})});assertFailure(await x.write("transaction","commit-fail",transaction),"PERSISTENCE_COMMIT_FAILED");assert.equal((await fs.readdir(path.join(dir,"transactions"))).some(f=>f.endsWith(".tmp")),false)});
 await scenario("cleanup diagnostic",async()=>{const dir=path.join(root,"cleanup-fail");const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir,trustedFileOperations:operations({unlink:async()=>{throw codeError("EACCES")}})});const result=await x.write("transaction","cleanup-fail",transaction);assert.equal(result.status,"created");assert.equal(result.diagnostics?.[0]?.operation,"cleanup");assert.equal(result.diagnostics?.[0]?.tempArtifactPossible,true)});

 await scenario("parallel replay",async()=>{const dir=path.join(root,"parallel-replay");const a=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir});const results=await Promise.all([a.write("transaction","parallel",transaction),a.write("transaction","parallel",structuredClone(transaction))]);assert.deepEqual(results.map(r=>r.status).sort(),["created","idempotent-replay"])});
 await scenario("parallel conflict",async()=>{const dir=path.join(root,"parallel-conflict");const a=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir});const results=await Promise.all([a.write("transaction","parallel",transaction),a.write("transaction","parallel",otherTransaction)]);assert.equal(results.filter(r=>r.status==="created").length,1);assert.equal(results.filter(r=>!r.ok&&r.errorCode==="PERSISTENCE_EXISTING_RECORD_CONFLICT").length,1);const read=await a.read("transaction","parallel");assert.equal(read.status,"found")});
 await scenario("unique temp attempts",async()=>{const paths:string[]=[];let id=0;const dir=path.join(root,"unique-temp");const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir,trustedAttemptIdFactory:()=>`attempt-${++id}`,trustedFileOperations:operations({writeFile:async(file,data,opts)=>{paths.push(file);return fs.writeFile(file,data,opts)}})});await Promise.all([x.write("transaction","one",transaction),x.write("transaction","two",otherTransaction)]);assert.equal(new Set(paths).size,2)});
 await scenario("attempt id collision preserves owner",async()=>{const dir=path.join(root,"attempt-collision");let writes=0,unlinks=0;let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve});const ops=operations({writeFile:async(file,data,opts)=>{writes++;if(writes===1){await fs.writeFile(file,data,opts);await gate;return}return fs.writeFile(file,data,opts)},unlink:async file=>{unlinks++;return fs.unlink(file)}});const first=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir,trustedAttemptIdFactory:()=>"same-attempt",trustedFileOperations:ops});const second=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir,trustedAttemptIdFactory:()=>"same-attempt",trustedFileOperations:ops});const firstWrite=first.write("transaction","collision",transaction);while(writes<1)await new Promise(resolve=>setImmediate(resolve));const secondResult=await second.write("transaction","collision",transaction);assertFailure(secondResult,"PERSISTENCE_TEMP_WRITE_FAILED");assert.equal(unlinks,0);release();const firstResult=await firstWrite;assert.equal(firstResult.status,"created");assert.equal(unlinks,1);const read=await first.read("transaction","collision");assert.equal(read.status,"found")});
 await scenario("existing target preserved",async()=>{const dir=path.join(root,"preserve");const original=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir});assert.equal((await original.write("transaction","target",transaction)).status,"created");let firstTargetRead=true;const targetSuffix=path.join("transactions","target.json");const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir,trustedFileOperations:operations({readFile:async(file,encoding)=>{if(firstTargetRead&&file.endsWith(targetSuffix)){firstTargetRead=false;throw codeError("ENOENT")}return fs.readFile(file,encoding)},link:async()=>{throw codeError("EIO")}})});assertFailure(await x.write("transaction","target",otherTransaction),"PERSISTENCE_COMMIT_FAILED");const read=await original.read("transaction","target");assert.equal(read.status,"found");if(read.status==="found")assert.equal(read.value.transactionId,transaction.transactionId)});

 await scenario("circular serialization",async()=>{const circular:Record<string,unknown>={...transaction};circular.self=circular;assertFailure(await adapter.write("transaction","circular",circular as never),"PERSISTENCE_SERIALIZATION_FAILED")});
 await scenario("bigint serialization",async()=>assertFailure(await adapter.write("transaction","bigint",{...transaction,extra:BigInt(1)} as never),"PERSISTENCE_SERIALIZATION_FAILED"));
 await scenario("non-finite serialization",async()=>assertFailure(await adapter.write("transaction","non-finite",{...transaction,extra:Number.POSITIVE_INFINITY} as never),"PERSISTENCE_SERIALIZATION_FAILED"));
 await scenario("special prototype serialization",async()=>{const value=Object.assign(Object.create({inherited:true}),transaction);assertFailure(await adapter.write("transaction","prototype",value),"PERSISTENCE_SERIALIZATION_FAILED")});
 await scenario("undefined optional",async()=>{const dir=path.join(root,"undefined");const x=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:dir});const {stage:unusedStage,...withoutStage}=transaction;void unusedStage;assert.equal((await x.write("transaction","undefined",{...withoutStage,stage:undefined})).status,"created");assert.equal((await x.write("transaction","undefined",withoutStage)).status,"idempotent-replay")});

 await scenario("gateway remains closed",()=>{assert.equal(defaultProductionControlledExecutionGatewayPolicy.enabled,false);assert.equal(defaultProductionControlledExecutionGatewayPolicy.mode,"preview-only");assert.equal(defaultProductionControlledExecutionGatewayPolicy.allowDispatch,false);assert.equal(defaultProductionControlledExecutionGatewayPolicy.allowExecution,false)});
 await scenario("defensive direct-write boundary",async()=>{const files=(await fs.readdir("src/lib/production")).filter(f=>f.endsWith(".ts")&&f!=="ProductionExecutionPersistence.ts");for(const file of files){const source=await fs.readFile(path.join("src/lib/production",file),"utf8");assert.ok(!/(?:from\s*["'](?:node:)?fs(?:\/promises)?["']|require\(["'](?:node:)?fs|\b(?:writeFile|writeFileSync|appendFile|appendFileSync|rename|renameSync|mkdir|mkdirSync|unlink|unlinkSync)\s*\(|FileStorage\s*\.\s*(?:saveJson|remove)\s*\()/i.test(source),`defensive direct-write boundary: ${file}`)}const persistence=await fs.readFile("src/lib/production/ProductionExecutionPersistence.ts","utf8");assert.ok(!/fetch\(|axios|enqueue\(|dispatch\(|child_process|worker_threads|NextResponse|POST\(/i.test(persistence));const route=await fs.readFile("app/api/production/health/[slug]/route.ts","utf8");assert.ok(!/POST|execute/i.test(route));const page=await fs.readFile("app/project/[slug]/page.tsx","utf8");assert.ok(!/ProductionControlledExecutionGateway|Execute Production|Start Execution/.test(page))});
 console.log(`Sprint 98.0 production execution persistence adapter smoke: PASS (${scenarios} scenarios)`);
}finally{await fs.rm(root,{recursive:true,force:true})}}

function assertFailure(result:{ok:boolean;errorCode?:string},code:string){assert.equal(result.ok,false);if(!result.ok)assert.equal(result.errorCode,code)}
function assertReadFailure(result:{ok:boolean;status:string;errorCode?:string},code:string){assert.equal(result.status,"failed");if(!result.ok)assert.equal(result.errorCode,code)}
function codeError(code:string){return Object.assign(new Error("injected"),{code})}
function operations(overrides:Partial<TrustedProductionExecutionPersistenceFileOperations>):TrustedProductionExecutionPersistenceFileOperations{return{access:fs.access,mkdir:fs.mkdir,readFile:fs.readFile,readdir:fs.readdir,writeFile:fs.writeFile,link:fs.link,unlink:fs.unlink,...overrides} as TrustedProductionExecutionPersistenceFileOperations}
void main();
