/** Supplemental TEMP controls. Old audit graders and the 166-suite manifest stay frozen. */
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {pathToFileURL} from "node:url";
import {auditDigest,createLocalAyasAuditCollector,inventoryAyasAuditProtectedRoots} from "../src/lib/ayas/audit/AyasSystemAuditCollector";
import {auditGraphFixture,AUDIT_HEAD} from "./fixtures/ayas-system-audit-fixture";

const repo=process.cwd(),parent=fs.realpathSync.native(os.tmpdir()),mode="STREAMING_LOCAL_HASH_ONLY" as const;
const heldFile="scripts/fixtures/ayas-system-audit-protection-held.json",heldHash="dbc02353c8022cfd3fd51462ebbe07d830f79bc84cb10ab13bdd45eb9d4dc323";
assert.equal(auditDigest(fs.readFileSync(path.join(repo,heldFile))),heldHash,"HELD_BYTES_CHANGED");
const args=process.argv.slice(2),only=args[0]==="--case"&&args.length===2?args[1]:null,mutations=args.length===1&&args[0]==="--mutations";
if(args.length&&!only&&!mutations||only&&!/^(?:P(?:0[1-9]|1[0-4])|H0[1-6])$/.test(only))throw Error("PROTECTION_TEST_ARGUMENT_INVALID");
const rows:{id:string;ok:boolean}[]=[];
function cleanup(root:string){assert.equal(path.dirname(fs.realpathSync.native(root)).toLowerCase(),parent.toLowerCase());assert(path.basename(root).startsWith("ayas-audit-protection-"));assert(!fs.lstatSync(root).isSymbolicLink());fs.rmSync(root,{recursive:true,force:true});}
function fixture(){const root=fs.mkdtempSync(path.join(parent,"ayas-audit-protection-"));fs.mkdirSync(path.join(root,"data/brain"),{recursive:true});return root;}
function sparse(file:string,size:number){const fd=fs.openSync(file,"w");try{fs.ftruncateSync(fd,size);}finally{fs.closeSync(fd);}}
async function scenario(id:string,fn:(root:string)=>void|Promise<void>){if(only&&id!==only)return;const root=fixture();try{await fn(root);rows.push({id,ok:true});}catch(e){rows.push({id,ok:false});console.log(JSON.stringify({status:"FAIL",results:rows}));throw e;}finally{const link=path.join(root,"data/brain/link");if(fs.existsSync(link)&&fs.lstatSync(link).isSymbolicLink()){if(process.platform==="win32")fs.rmdirSync(link);else fs.unlinkSync(link);}cleanup(root);}}
function noOpen(root:string,file:string){const open=fs.openSync;let attempts=0;fs.openSync=((...args:Parameters<typeof fs.openSync>)=>{if(String(args[0])===file){attempts++;throw Error("CANARY_MUST_NOT_OPEN");}return open(...args);}) as typeof fs.openSync;try{const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(attempts,0);return v;}finally{fs.openSync=open;}}

async function baseline(){
  await scenario("P01",()=>assert.throws(()=>inventoryAyasAuditProtectedRoots("relative",mode),/AUDIT_ROOT_INVALID/));
  await scenario("P02",root=>assert.throws(()=>inventoryAyasAuditProtectedRoots(root,"unknown" as never),/AUDIT_INVENTORY_MODE_INVALID/));
  await scenario("P03",root=>{const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,true);assert.equal(v.complete,false);assert.equal(v.externalRuntimeQualified,false);assert.equal(v.bytesHashed,0);});
  await scenario("P04",root=>{fs.writeFileSync(path.join(root,"data/brain/record.json"),'{}');const a=inventoryAyasAuditProtectedRoots(root),b=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(a.digest,b.digest);assert.equal(b.bytesHashed,2);assert.equal(a.complete,true);assert.equal(b.complete,false);});
  await scenario("P05",root=>{fs.writeFileSync(path.join(root,"data/brain/record.json"),'synthetic');const a=inventoryAyasAuditProtectedRoots(root,mode),b=inventoryAyasAuditProtectedRoots(root,mode);assert.deepEqual(a,b);});
  await scenario("P06",root=>{const f=path.join(root,"data/brain/.env.local");fs.writeFileSync(f,'synthetic canary');const v=noOpen(root,f);assert.equal(v.exclusions?.credentialFiles,1);assert.equal(v.localComplete,false);});
  await scenario("P07",root=>{const f=path.join(root,"data/brain/a.json");fs.writeFileSync(f,'{}');fs.linkSync(f,path.join(root,"data/brain/b.json"));const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,false);assert.equal(v.exclusions?.linkOrSpecialEntries,2);assert.equal(v.bytesHashed,0);});
  await scenario("P08",root=>{let at=path.join(root,"data/brain");for(let i=0;i<22;i++)at=path.join(at,'nested');fs.mkdirSync(at,{recursive:true});fs.writeFileSync(path.join(at,'record.json'),'{}');const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,false);assert((v.exclusions?.depthOrFileLimitStops??0)>0);});
  await scenario("P09",root=>{fs.writeFileSync(path.join(root,"data/brain/record.json"),'before');const a=inventoryAyasAuditProtectedRoots(root,mode);fs.writeFileSync(path.join(root,"data/brain/record.json"),'after');assert.notEqual(a.digest,inventoryAyasAuditProtectedRoots(root,mode).digest);});
  await scenario("P10",root=>{sparse(path.join(root,"data/brain/media.bin"),1024*1024);const read=fs.readSync;let largest=0;fs.readSync=((...a:unknown[])=>{largest=Math.max(largest,Number(a[3]));return (read as (...p:unknown[])=>number)(...a);}) as typeof fs.readSync;try{const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,true);assert(largest>0&&largest<=256*1024);}finally{fs.readSync=read;}});
  await scenario("P11",root=>{const deps=createLocalAyasAuditCollector(root,{repository:()=>({head:AUDIT_HEAD,branch:'codex/fixture'}),graph:async()=>auditGraphFixture()});assert.throws(()=>deps.readSource('arbitrary-file'),/AUDIT_SOURCE_NOT_REGISTERED/);sparse(path.join(root,'package.json'),4*1024*1024+1);assert.equal(deps.readSource('package.json'),null);});
  await scenario("P12",root=>{const f=path.join(root,'package.json');fs.writeFileSync(f,'{}');const deps=createLocalAyasAuditCollector(root,{repository:()=>({head:AUDIT_HEAD,branch:'codex/fixture'}),graph:async()=>auditGraphFixture()});assert.equal(Buffer.from(deps.readSource('package.json')!).toString(),'{}');});
  await scenario("P13",root=>{for(let i=0;i<65;i++)sparse(path.join(root,`data/brain/cap-${String(i).padStart(2,'0')}.bin`),(i<64?16:1)*1024*1024);const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,false);assert.equal(v.exclusions?.sizeOrByteBudgetFiles,1);assert.equal(v.bytesHashed,1024*1024*1024);});
  await scenario("P14",root=>{fs.writeFileSync(path.join(root,'data/brain/record.json'),'{}');const now=Date.now;let ticks=0;Date.now=()=>++ticks*200000;try{const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,false);assert.equal(v.bytesHashed,0);assert.equal(v.exclusions?.unreadableRoots,1);}finally{Date.now=now;}});
  await scenario("H01",root=>{const f=path.join(root,"data/brain/media.bin");sparse(f,16*1024*1024+1);const v=noOpen(root,f);assert.equal(v.localComplete,false);assert.equal(v.exclusions?.sizeOrByteBudgetFiles,1);});
  await scenario("H02",root=>{const f=path.join(root,"data/brain/token-canary.json");fs.writeFileSync(f,'synthetic canary');const v=noOpen(root,f);assert.equal(v.localComplete,false);assert.equal(v.exclusions?.credentialFiles,1);});
  await scenario("H03",root=>{const target=fs.mkdtempSync(path.join(parent,'ayas-audit-protection-'));try{fs.writeFileSync(path.join(target,'canary.json'),'synthetic');fs.symlinkSync(target,path.join(root,'data/brain/link'),process.platform==='win32'?'junction':'dir');const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,false);assert.equal(v.exclusions?.linkOrSpecialEntries,1);assert.equal(v.bytesHashed,0);}finally{const link=path.join(root,'data/brain/link');if(process.platform==='win32')fs.rmdirSync(link);else fs.unlinkSync(link);cleanup(target);}});
  await scenario("H04",root=>{for(let i=0;i<9;i++)sparse(path.join(root,`data/brain/media-${i}.bin`),(i<8?16:1)*1024*1024);const old=inventoryAyasAuditProtectedRoots(root),v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(old.complete,false);assert.equal(old.exclusions?.sizeOrByteBudgetFiles,1);assert.equal(v.localComplete,true);assert.equal(v.exclusions?.sizeOrByteBudgetFiles,0);assert.equal(v.bytesHashed,129*1024*1024);assert.equal(v.complete,false);assert.equal(v.externalRuntimeQualified,false);});
  await scenario("H05",root=>{const file=path.join(root,'data/brain/record.json');fs.writeFileSync(file,'{}');const open=fs.openSync,read=fs.readSync;let changed=false,reads=0;fs.openSync=((...a:Parameters<typeof fs.openSync>)=>{const fd=open(...a);if(String(a[0])===file&&!changed){changed=true;const write=open(file,'r+');try{fs.ftruncateSync(write,1024);}finally{fs.closeSync(write);}}return fd;}) as typeof fs.openSync;fs.readSync=((...a:unknown[])=>{reads++;return (read as (...p:unknown[])=>number)(...a);}) as typeof fs.readSync;try{const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,false);assert.equal(reads,0,'changed file must be refused BEFORE body read');}finally{fs.openSync=open;fs.readSync=read;}});
  await scenario("H06",root=>{const file=path.join(root,'data/brain/record.json');fs.writeFileSync(file,'{}');const read=fs.readSync;let changed=false;fs.readSync=((...a:unknown[])=>{const n=(read as (...p:unknown[])=>number)(...a);if(!changed){changed=true;fs.appendFileSync(file,'x');}return n;}) as typeof fs.readSync;try{const v=inventoryAyasAuditProtectedRoots(root,mode);assert.equal(v.localComplete,false);assert.equal(v.exclusions?.unreadableRoots,1);}finally{fs.readSync=read;}});
}

async function main(){await baseline();if(!mutations){console.log(JSON.stringify({status:'PASS',primary:rows.filter(r=>r.id.startsWith('P')).length,held:rows.filter(r=>r.id.startsWith('H')).length,heldSha256:heldHash,fixture:'TEMP_HASH_ONLY_NO_AUTHORITY_OR_CREDENTIAL_BODY',results:rows}));return;}
  const temp=fs.mkdtempSync(path.join(parent,'ayas-audit-protection-')),copied=new Set<string>();
  function copy(file:string){if(copied.has(file))return;copied.add(file);const target=path.join(temp,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(path.join(repo,file),target);if(!/\.tsx?$/.test(file))return;for(const m of fs.readFileSync(target,'utf8').matchAll(/(?:from\s*|import\s*\(?\s*)['"](\.[^'"]+)['"]/g)){const base=path.resolve(path.dirname(path.join(repo,file)),m[1]!);const found=[base,base+'.ts',base+'.tsx',base+'.json'].find(f=>fs.existsSync(f)&&fs.statSync(f).isFile());if(found){const rel=path.relative(repo,found);assert(!rel.startsWith('..')&&!path.isAbsolute(rel));copy(rel);}}}
  const controls=[['credential opening','if(credential||s.size>','if(false||s.size>','H02'],['opened file growth','if(!sameAuditFile(stat,opened))','if(false)','H05'],['mutation during read','if(!sameAuditFile(opened,fs.fstatSync(fd))||!ancestry(root,file)||!sameAuditFile(opened,fs.lstatSync(file)))','if(false)','H06'],['local promoted to full coverage','complete:streaming?false:complete','complete','H04'],['operator byte budget doubled','(streaming?1024:128)','(streaming?2048:128)','P13'],['operator time bound removed','streaming&&Date.now()>deadline','false','P14']] as const;
  try{copy('scripts/smoke-ayas-system-audit-protection.ts');copy(heldFile);const file=path.join(temp,'src/lib/ayas/audit/AyasSystemAuditCollector.ts'),original=fs.readFileSync(file,'utf8'),env:NodeJS.ProcessEnv={NODE_ENV:'test'};for(const k of ['SystemRoot','WINDIR','COMSPEC','PATH','PATHEXT','TEMP','TMP','USERPROFILE','APPDATA','LOCALAPPDATA'])if(process.env[k])env[k]=process.env[k];
    for(const [name,before,after,id]of controls){assert.equal(original.split(before).length-1,1);fs.writeFileSync(file,original.replace(before,()=>after));const r=spawnSync(process.execPath,['--import',pathToFileURL(require.resolve('tsx')).href,'scripts/smoke-ayas-system-audit-protection.ts','--case',id],{cwd:temp,env,encoding:'utf8',windowsHide:true,timeout:60000,maxBuffer:2e6});assert.equal(r.status,1,name);assert.match(r.stderr,/AssertionError|ERR_ASSERTION/);assert.doesNotMatch(r.stderr,/SyntaxError|TransformError|ERR_MODULE_NOT_FOUND|Cannot find module|is not defined|is not a function/);assert.deepEqual(JSON.parse(r.stdout.trim()).results,[{id,ok:false}]);fs.writeFileSync(file,original);}
    console.log(JSON.stringify({status:'PASS',primary:14,held:6,sourceMutationsCaught:controls.length,heldSha256:heldHash,scope:'GITLESS_TEMP_ASSERTION_CAUGHT_NO_AUTHORITY'}));
  }finally{cleanup(temp);}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
