import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { createAyasApprovalInboxStore } from "../src/lib/brain/autonomy/AyasApprovalInboxStore";
import { revalidateAyasExecution, AyasExecutionRevalidationError } from "../src/lib/brain/autonomy/AyasExecutionRevalidation";
import { canonicalizeAyasExactFiles, createAyasMutationBoundary, AyasMutationScopeError } from "../src/lib/brain/autonomy/AyasMutationScope";
import { classifyAyasRestartRecovery } from "../src/lib/brain/autonomy/AyasExecutionRecoveryPolicy";
import { ayasExecutionJournalSchemaVersion, type AyasExecutionJournalEntry, type AyasExecutionJournalPhase } from "../src/lib/brain/autonomy/AyasExecutionJournal";

let count = 0;
async function scenario(name: string, fn: () => unknown | Promise<unknown>) { await fn(); count += 1; if (process.env.SMOKE_TRACE === "1") console.log(`PASS ${count}: ${name}`); }
const temp = (label: string) => fs.mkdtempSync(path.join(os.tmpdir(), `ayas-m4-${label}-`));
const git = (root: string, ...args: string[]) => execFileSync("git", ["-C", root, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
function repo(files: Record<string, string> = { "allowed.txt": "base\n" }) { const root = temp("repo"); git(root, "init", "-q"); git(root, "config", "user.email", "smoke@example.invalid"); git(root, "config", "user.name", "Smoke"); for (const [file, text] of Object.entries(files)) { fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true }); fs.writeFileSync(path.join(root, file), text); } git(root, "add", "."); git(root, "commit", "-qm", "base"); return root; }
const health = (action: "ALLOW" | "THROTTLE" | "PAUSE" | "STOP OWN WORKLOAD" | "BLOCK NEW HEAVY WORK") => ({ action, reasonCode: action, mayStart: action === "ALLOW" || action === "THROTTLE", telemetry: { observedAt: new Date(0).toISOString(), processRssMb: 0, unavailable: [] } }) as never;
function authorized(root: string) { const inbox = createAyasApprovalInboxStore({ rootDir: temp("inbox") }); const baseHead = git(root, "rev-parse", "HEAD"); const proposal = inbox.createProposal({ createdAt: new Date(0).toISOString(), baseBranch: "test", baseHead, objective: "fixture", currentProblem: "fixture gap", selectionReason: "bounded evidence", expectedUserBenefit: "regression protection", expectedBehaviorChange: "one controlled fixture change", unchangedBehavior: "production stays unchanged", riskIfNotDone: "gap remains", technicalRisk: "low", productionImpact: "none", rationale: "fixture", evidence: ["fixture evidence"], graphifyEvidence: ["fixture graph"], candidateRank: 1, risk: "low", safetyClassification: "SAFE", exactFiles: ["allowed.txt"], expectedDiffScope: "fixture", testsPlanned: ["fixture smoke"], estimatedCost: "zero-cost" }); inbox.decide(proposal.proposalId, "APPROVE", new Date(1).toISOString()); const reservation = inbox.reserveApproval(proposal.proposalId, proposal.proposalHash, baseHead, proposal.exactFiles, new Date(2).toISOString()); return { inbox, binding: { proposalId: proposal.proposalId, proposalHash: proposal.proposalHash, baseHead, exactFiles: proposal.exactFiles, ...reservation } }; }
const journal = (phase: AyasExecutionJournalPhase): AyasExecutionJournalEntry => ({ schemaVersion: ayasExecutionJournalSchemaVersion, executionId: "ayas-exec-fixture", proposalId: "p", proposalHash: "h", baseHead: "b", exactFiles: ["allowed.txt"], phase, startedAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() });

async function main() {
  { const root = repo(); const a = authorized(root); const deps = { repoRoot: root, inbox: a.inbox, readMachineHealth: async () => health("ALLOW") };
    await scenario("1 correct HEAD accepted", () => revalidateAyasExecution(a.binding, deps));
    await scenario("2 stale HEAD rejected", () => assert.rejects(() => revalidateAyasExecution({ ...a.binding, baseHead: "stale" }, deps), (e: unknown) => e instanceof AyasExecutionRevalidationError && e.code === "HEAD_MISMATCH"));
    await scenario("3 dirty repo rejected", async () => { fs.writeFileSync(path.join(root, "dirty.txt"), "x"); await assert.rejects(() => revalidateAyasExecution(a.binding, deps), (e: unknown) => e instanceof AyasExecutionRevalidationError && e.code === "REPOSITORY_DIRTY"); fs.rmSync(path.join(root, "dirty.txt")); });
    await scenario("4 Machine Health PAUSE rejected", () => assert.rejects(() => revalidateAyasExecution(a.binding, { ...deps, readMachineHealth: async () => health("PAUSE") }), /Machine Health/));
    await scenario("5 Machine Health STOP rejected", () => assert.rejects(() => revalidateAyasExecution(a.binding, { ...deps, readMachineHealth: async () => health("STOP OWN WORKLOAD") }), /Machine Health/));
    await scenario("6 proposal hash mismatch rejected", () => assert.rejects(() => revalidateAyasExecution({ ...a.binding, proposalHash: "wrong" }, deps), /proposal binding/));
    await scenario("7 exactFiles mismatch rejected", () => assert.rejects(() => revalidateAyasExecution({ ...a.binding, exactFiles: ["other.txt"] }, deps), /exact-file scope/));
    await scenario("8 invalid reservation rejected", () => assert.rejects(() => revalidateAyasExecution({ ...a.binding, reservationId: "wrong" }, deps), /reservation/));
    await scenario("9 state change between two validations detected", async () => { let reads = 0; const changing = { ...deps, readRepository: async () => ({ head: a.binding.baseHead, clean: ++reads === 1 }) }; await revalidateAyasExecution(a.binding, changing); await assert.rejects(() => revalidateAyasExecution(a.binding, changing), /not clean/); });
    await scenario("10 callback count zero on failed second validation", async () => { let callbacks = 0; await assert.rejects(async () => { await revalidateAyasExecution(a.binding, deps); await revalidateAyasExecution(a.binding, { ...deps, readMachineHealth: async () => health("PAUSE") }); callbacks += 1; }); assert.equal(callbacks, 0); });
  }
  await scenario("11 authorized single-file change accepted", async () => { const r = repo(); const b = await createAyasMutationBoundary(r, ["allowed.txt"]); fs.writeFileSync(path.join(r, "allowed.txt"), "new\n"); assert.deepEqual((await b.verify()).changedFiles, ["allowed.txt"]); });
  await scenario("12 authorized multi-file change accepted", async () => { const r = repo({ "a.txt": "a", "b.txt": "b" }); const b = await createAyasMutationBoundary(r, ["a.txt", "b.txt"]); fs.writeFileSync(path.join(r, "a.txt"), "A"); fs.writeFileSync(path.join(r, "b.txt"), "B"); assert.equal((await b.verify()).changedFiles.length, 2); });
  await scenario("13 unexpected extra file rejected", async () => { const r = repo(); const b = await createAyasMutationBoundary(r, ["allowed.txt"]); fs.writeFileSync(path.join(r, "extra.txt"), "x"); await assert.rejects(() => b.verify(), (e: unknown) => e instanceof AyasMutationScopeError && e.code === "UNAUTHORIZED_MUTATION"); });
  await scenario("14 unauthorized untracked file detected", async () => { const r = repo(); const b = await createAyasMutationBoundary(r, ["allowed.txt"]); fs.writeFileSync(path.join(r, "hidden.bin"), "x"); await assert.rejects(() => b.verify(), /exceeded exactFiles/); });
  await scenario("15 delete detected", async () => { const r = repo(); const b = await createAyasMutationBoundary(r, ["allowed.txt"]); fs.rmSync(path.join(r, "allowed.txt")); assert.deepEqual((await b.verify()).changedFiles, ["allowed.txt"]); });
  await scenario("16 rename requires both identities", async () => { const r = repo(); const b = await createAyasMutationBoundary(r, ["allowed.txt", "renamed.txt"]); fs.renameSync(path.join(r, "allowed.txt"), path.join(r, "renamed.txt")); assert.deepEqual(await b.verify().then(x => x.changedFiles), ["allowed.txt", "renamed.txt"]); });
  await scenario("17 outside-root path rejected", () => { const r = repo(); assert.throws(() => canonicalizeAyasExactFiles(r, [path.resolve(r, "allowed.txt")]), /invalid/); });
  await scenario("18 normalized traversal alias rejected", () => { const r = repo(); assert.throws(() => canonicalizeAyasExactFiles(r, ["sub/../../outside.txt"]), /escapes/); });
  await scenario("19 Windows separators and case canonicalize deterministically", () => { const r = repo(); assert.equal(canonicalizeAyasExactFiles(r, [".\\allowed.txt", "allowed.txt"]).length, 1); });
  await scenario("20 callback report cannot conceal actual extra mutation", async () => { const r = repo(); const b = await createAyasMutationBoundary(r, ["allowed.txt"]); fs.writeFileSync(path.join(r, "extra.txt"), "x"); const selfReport: string[] = []; assert.deepEqual(selfReport, []); await assert.rejects(() => b.verify(), /exceeded exactFiles/); });
  const cases: readonly [string, AyasExecutionJournalPhase | undefined, string, boolean][] = [["21 reserved restart", "AUTHORIZATION_RESERVED", "RESERVED_ONLY", true], ["22 armed restart", "GATE_ARMED", "PRE_MUTATION_GATE", true], ["23 ready restart", "GATE_READY", "PRE_MUTATION_GATE", true], ["24 open restart", "GATE_OPEN", "PRE_MUTATION_GATE", true], ["25 executing never replays", "EXECUTING", "MUTATION_UNCERTAIN", true], ["26 mutation completed never replays", "MUTATION_COMPLETED", "MUTATION_COMPLETED_UNFINALIZED", true], ["27 failed remains terminal", "FAILED", "FAILED", true], ["28 successful result completed", "RESULT_RECORDED", "COMPLETED", false], ["29 uncertain requires review", "PARTIAL_UNKNOWN", "MUTATION_UNCERTAIN", true], ["30 classifier is pure and mutation-free", undefined, "NEVER_STARTED", false]];
  for (const [name, phase, expected, review] of cases) await scenario(name, () => { const before = phase ? journal(phase) : undefined; const frozen = before ? JSON.stringify(before) : ""; const result = classifyAyasRestartRecovery(before); assert.equal(result.classification, expected); assert.equal(result.humanReviewRequired, review); assert.equal(result.autoReplayAllowed, false); assert.equal(before ? JSON.stringify(before) : "", frozen); });
  console.log(`AYAS M4 execution revalidation/scope/recovery smoke: PASS (${count} scenarios)`); console.log(JSON.stringify({ status: "PASS", suite: "ayas-execution-revalidation-scope-recovery", scenarios: count }));
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
