import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { ProductionExecutionCoordinator } from "../src/lib/production/ProductionExecutionCoordinator";
import { ProductionExecutionLifecycle } from "../src/lib/production/ProductionExecutionLifecycle";
import { ProductionExecutionRecoveryBootstrap, type ProductionExecutionRecoveryPlannerPort } from "../src/lib/production/ProductionExecutionRecoveryBootstrap";
import { AdapterBackedProductionExecutionClaimService, defaultProductionExecutionClaimPolicy } from "../src/lib/production/ProductionExecutionDurableClaim";
import { AdapterBackedProductionExecutionDurableLeaseService, defaultProductionExecutionDurableLeasePolicy } from "../src/lib/production/ProductionExecutionDurableLease";
import { AdapterBackedProductionExecutionDurableStorage, defaultProductionExecutionDurableStoragePolicy } from "../src/lib/production/ProductionExecutionDurableStorage";
import { defaultProductionExecutionAttemptPolicy } from "../src/lib/production/ProductionExecutionDurableAttempt";
import { buildProductionExecutionIdempotencyIdentity, defaultProductionExecutionIdempotencyPolicy } from "../src/lib/production/ProductionExecutionIdempotency";
import { ProductionExecutionFilePersistenceAdapter } from "../src/lib/production/ProductionExecutionPersistence";
import type { ProductionExecutionCoordinatorRequest } from "../src/types/productionExecutionCoordinator";
import type { ProductionExecutionAuthorizationResult } from "../src/types/productionExecutionAuthorization";
import type { ProductionExecutionConfirmationValidationResult } from "../src/types/productionExecutionConfirmation";
import type { ProductionExecutionDurableWorkerIdentity, ProductionExecutionWorkerSessionIdentity } from "../src/types/productionExecutionDurableLease";
import type { ProductionExecutionIdempotencyRecord, ProductionExecutionIdempotencyReservationRequest } from "../src/types/productionExecutionIdempotency";

const t0="2026-07-13T08:00:00.000Z",t1="2026-07-13T08:01:00.000Z",t2="2026-07-13T08:02:00.000Z",t3="2026-07-13T08:03:00.000Z",t4="2026-07-13T08:04:00.000Z",t5="2026-07-13T08:05:00.000Z",operation="pipeline.stage.retry.preview";
const idPolicy={...defaultProductionExecutionIdempotencyPolicy,enabled:true,reservationTtlSeconds:600},storagePolicy={...defaultProductionExecutionDurableStoragePolicy,enabled:true,reservationTtlSeconds:600,idempotencyPolicy:idPolicy},leasePolicy={...defaultProductionExecutionDurableLeasePolicy,reservationTtlSeconds:600,maximumLeaseDurationSeconds:600},claimPolicy={...defaultProductionExecutionClaimPolicy,reservationTtlSeconds:600},attemptPolicy={...defaultProductionExecutionAttemptPolicy,reservationTtlSeconds:600};
const authorization:ProductionExecutionAuthorizationResult={schemaVersion:"1",decisionId:"authorization-1",decision:"allow",authorized:true,reasonCode:"AUTHORIZED",reason:"safe",evaluatedAt:t0,requestId:"request-1",idempotencyKey:"execution-1",executionFingerprint:"snapshot-1",actorId:"actor-1",actorType:"user",projectSlug:"project-1",operation,action:"retry-stage",stage:"script",requiredCapabilities:[],grantedCapabilities:[],missingCapabilities:[],policyVersion:"authorization-policy-v1",risk:"high",requiresConfirmation:true,requiredConfirmationLevel:"high",evidence:[]};
const confirmation:ProductionExecutionConfirmationValidationResult={schemaVersion:"1",decision:"valid",valid:true,reasonCode:"CONFIRMATION_VALID",reason:"safe",evaluatedAt:t0,confirmationId:"confirmation-1",confirmationRequestId:"confirmation-request-1",authorizationDecisionId:"authorization-1",requestId:"request-1",idempotencyKey:"execution-1",actorId:"actor-1",projectSlug:"project-1",operation,action:"retry-stage",stage:"script",riskLevel:"high",requiredConfirmationLevel:"high",providedConfirmationLevel:"high",bindingMatches:true,bindingFingerprint:"confirmation-binding-1",expired:false,singleUse:true,consumed:false,policyVersion:"authorization-policy-v1",evidence:[]};
const identity=buildProductionExecutionIdempotencyIdentity({authorization,confirmation},{evaluatedAt:t0,policy:idPolicy}).identity!;
const worker:ProductionExecutionDurableWorkerIdentity={schemaVersion:"1",workerId:"worker-1",workerType:"server",operationScope:[operation],identitySource:"trusted-server"},session:ProductionExecutionWorkerSessionIdentity={schemaVersion:"1",workerSessionId:"session-1",workerId:"worker-1",startedAt:t0,identitySource:"trusted-server"};
const coordinatorRequest:ProductionExecutionCoordinatorRequest={claim:{claimId:"claim-1",recordId:"record-1",reservationId:identity.identityFingerprint,requestId:"request-1",idempotencyKey:"execution-1",executionFingerprint:"snapshot-1",workerId:"worker-1",workerSessionId:"session-1",leaseId:"lease-1",expectedReservationVersion:1,expectedIdempotencyVersion:2,expectedLeaseVersion:1,expectedClaimVersion:0,evaluatedAt:t2},attempt:{attemptId:"attempt-1",claimId:"claim-1",reservationId:identity.identityFingerprint,recordId:"record-1",requestId:"request-1",idempotencyKey:"execution-1",executionFingerprint:"snapshot-1",workerId:"worker-1",workerSessionId:"session-1",leaseId:"lease-1",expectedClaimVersion:1,expectedAttemptVersion:0,evaluatedAt:t2}};
const planner:ProductionExecutionRecoveryPlannerPort={async createJobRetryPlan(projectSlug,stage){return{projectSlug,type:"retry",startStage:stage,stagesToRun:[stage],blocked:false,dependencies:[],createdAt:t0}}};

async function setup(root:string,name:string){const directory=path.join(root,name),adapter=new ProductionExecutionFilePersistenceAdapter({trustedRootDirectory:directory,trustedAttemptIdFactory:()=>"fixed"}),storage=new AdapterBackedProductionExecutionDurableStorage(adapter),leases=new AdapterBackedProductionExecutionDurableLeaseService(adapter),claims=new AdapterBackedProductionExecutionClaimService(adapter);const reservation:ProductionExecutionIdempotencyReservationRequest={schemaVersion:"1",identity,authorization,confirmation,requestedAt:t0,expectedInitialState:"reserved",attempt:1,maxAttempts:3,reservationTtlSeconds:600,policyContext:{source:"server",environment:"test"},metadata:{source:"server"}},record:ProductionExecutionIdempotencyRecord={schemaVersion:"1",recordId:"record-1",identityFingerprint:identity.identityFingerprint,idempotencyKey:identity.idempotencyKey,requestId:identity.requestId,executionFingerprint:identity.executionFingerprint,bindingFingerprint:identity.bindingFingerprint,actorId:identity.actorId,projectSlug:identity.projectSlug,operation:identity.operation,action:identity.action,stage:identity.stage,authorizationDecisionId:identity.authorizationDecisionId,confirmationRequestId:identity.confirmationRequestId,confirmationId:identity.confirmationId,policyVersion:identity.policyVersion,riskLevel:identity.riskLevel,state:"reserved",attempt:1,maxAttempts:3,createdAt:t0,updatedAt:t0,reservedAt:t0,evidence:[],integrity:{algorithm:"stable-production-id-v1",fingerprint:identity.identityFingerprint,version:1}};await storage.createReservation(reservation,{evaluatedAt:t1,policy:storagePolicy});await storage.createRecord(record,{evaluatedAt:t1,policy:storagePolicy});await leases.acquire({recordId:"record-1",expectedVersion:1,evaluatedAt:t1,worker,session,leaseId:"lease-1",acquiredAt:t1,heartbeatAt:t1,expiresAt:t4},leasePolicy);await claims.acquireExecutionClaim(coordinatorRequest.claim,claimPolicy);const coordinator=new ProductionExecutionCoordinator(adapter),lifecycle=new ProductionExecutionLifecycle(adapter);await coordinator.coordinate(coordinatorRequest,{claim:claimPolicy,attempt:attemptPolicy});return{directory,adapter,lifecycle,bootstrap:new ProductionExecutionRecoveryBootstrap(adapter,planner)}}
const mutation=(transition:"running"|"completed",version:number,eventId:string)=>({attemptId:"attempt-1",claimId:"claim-1",workerId:"worker-1",workerSessionId:"session-1",leaseId:"lease-1",expectedAttemptVersion:version,eventId,transition,evaluatedAt:t3,metadata:{code:`RECOVERY_${transition.toUpperCase()}`,summary:`Attempt ${transition}.`,evidence:[`recovery:${transition}`]}});
async function snapshot(directory:string){const output:string[]=[];async function walk(current:string){let entries;try{entries=await fs.readdir(current,{withFileTypes:true})}catch{return}for(const entry of entries){const full=path.join(current,entry.name);if(entry.isDirectory())await walk(full);else output.push(`${path.relative(directory,full)}:${await fs.readFile(full,"utf8")}`)}}await walk(directory);return output.sort()}

async function main(){const root=await fs.mkdtemp(path.join(os.tmpdir(),"atolye-recovery-bootstrap-"));let count=0;const scenario=async(name:string,run:()=>unknown|Promise<unknown>)=>{await run();count++;void name};try{
  const active=await setup(root,"active"),activeResult=await active.bootstrap.bootstrapRecovery({evaluatedAt:t3}),activeAttempt=activeResult.attempts[0];
  await scenario("active attempt classified",()=>{assert.equal(activeAttempt.primaryClassification,"active");assert.ok(activeAttempt.classifications.includes("active"))});
  await scenario("replayable attempt validated",()=>{assert.ok(activeAttempt.classifications.includes("replayable"));assert.equal(activeAttempt.journalValid,true);assert.equal(activeAttempt.versionChainValid,true)});
  await scenario("recovery planner output consistent",()=>{assert.equal(activeResult.plannerPlans[0]?.projectSlug,"project-1");assert.equal(activeResult.plannerPlans[0]?.stage,"script");assert.equal(activeResult.plannerPlans[0]?.type,"retry")});
  const before=await snapshot(active.directory),replay=await active.bootstrap.bootstrapRecovery({evaluatedAt:t3});
  await scenario("exact bootstrap replay write free",async()=>{assert.equal(replay.writeFree,true);assert.deepEqual(await snapshot(active.directory),before)});
  await scenario("deterministic bootstrap result",()=>assert.deepEqual(replay,activeResult));

  const running=await setup(root,"running");await running.lifecycle.mutate(mutation("running",1,"event-running"),{attempt:attemptPolicy});const runningResult=await running.bootstrap.bootstrapRecovery({evaluatedAt:t3}),runningAttempt=runningResult.attempts[0];
  await scenario("running attempt classified",()=>{assert.equal(runningAttempt.primaryClassification,"running");assert.ok(runningAttempt.classifications.includes("running"));assert.equal(runningAttempt.action,"wait-for-owner")});
  await scenario("journal sequence validated",()=>assert.equal(runningAttempt.journalSequence,2));
  await scenario("attempt version preserved",()=>assert.equal(runningAttempt.attemptVersion,2));

  const terminal=await setup(root,"terminal");await terminal.lifecycle.mutate(mutation("running",1,"event-running"),{attempt:attemptPolicy});await terminal.lifecycle.mutate(mutation("completed",2,"event-completed"),{attempt:attemptPolicy});const terminalResult=await terminal.bootstrap.bootstrapRecovery({evaluatedAt:t5}),terminalAttempt=terminalResult.attempts[0];
  await fs.rm(path.join(terminal.directory,"attempts","attempt-1-v1.json"));const brokenTerminal=await terminal.bootstrap.bootstrapRecovery({evaluatedAt:t5});
  await scenario("terminal attempt not replanned",()=>{assert.equal(terminalAttempt.primaryClassification,"terminal");assert.equal(terminalAttempt.recoveryCandidate,false);assert.equal(terminalResult.plannerPlans.length,0);assert.equal(brokenTerminal.attempts[0]?.terminal,true);assert.equal(brokenTerminal.attempts[0]?.recoveryCandidate,false);assert.equal(brokenTerminal.plannerPlans.length,0)});

  const expired=await setup(root,"expired");await expired.lifecycle.mutate(mutation("running",1,"event-running"),{attempt:attemptPolicy});const expiredResult=await expired.bootstrap.bootstrapRecovery({evaluatedAt:t5}),expiredAttempt=expiredResult.attempts[0];
  await scenario("expired lease recovery candidate",()=>{assert.equal(expiredAttempt.primaryClassification,"expired-lease");assert.equal(expiredAttempt.recoveryCandidate,true);assert.equal(expiredAttempt.action,"recover-expired-lease")});

  const orphan=await setup(root,"orphan");await fs.rm(path.join(orphan.directory,"claims"),{recursive:true,force:true});const orphanResult=await orphan.bootstrap.bootstrapRecovery({evaluatedAt:t3});
  await scenario("orphaned attempt marked",()=>{assert.equal(orphanResult.attempts[0]?.primaryClassification,"orphaned");assert.equal(orphanResult.attempts[0]?.action,"manual-recovery")});

  const broken=await setup(root,"broken");await broken.lifecycle.mutate(mutation("running",1,"event-running"),{attempt:attemptPolicy});await fs.rm(path.join(broken.directory,"attempts","attempt-1-v1.json"));const brokenResult=await broken.bootstrap.bootstrapRecovery({evaluatedAt:t3});
  await scenario("version chain gap rejected",()=>{assert.equal(brokenResult.attempts[0]?.primaryClassification,"orphaned");assert.equal(brokenResult.attempts[0]?.versionChainValid,false)});
  await scenario("pipeline behavior remains planner-only",async()=>{const source=await fs.readFile("src/lib/production/ProductionExecutionRecoveryBootstrap.ts","utf8");assert.ok(!/configureDurableExecution|runStage\(|enqueue\(|NextResponse|POST\(/.test(source))});
  await scenario("no new persistence format",async()=>{const source=await fs.readFile("src/types/productionExecutionPersistence.ts","utf8");assert.ok(!/bootstrap/.test(source));assert.deepEqual(await snapshot(active.directory),before)});
  await scenario("safe bootstrap output",async()=>{const unsafePlanner:ProductionExecutionRecoveryPlannerPort={async createJobRetryPlan(projectSlug,stage){return{projectSlug,type:"retry",startStage:stage,stagesToRun:[stage],blocked:true,reason:"secret token stack C:\\private",dependencies:[{stage,status:"failed",completed:false,fileReady:false,ready:false,reason:"secret dependency stack"}],createdAt:t0}}};const output=await new ProductionExecutionRecoveryBootstrap(active.adapter,unsafePlanner).bootstrapRecovery({evaluatedAt:t3});assert.ok(!/secret|token|stack|C:\\/i.test(JSON.stringify(output))) });
  assert.equal(count,15);console.log(`Sprint 108 durable recovery bootstrap smoke: PASS (${count}/15 scenarios)`);
}finally{await fs.rm(root,{recursive:true,force:true})}}
void main();
