import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { ProductionRuntimeInitializationError, ProductionRuntimeInitializer, type ProductionRuntimeInitializerDependencies } from "../src/lib/production/ProductionRuntimeInitializer";
import type { ProductionExecutionRecoveryBootstrapAttempt, ProductionExecutionRecoveryBootstrapClassification, ProductionExecutionRecoveryBootstrapResult } from "../src/types/productionExecutionRecoveryBootstrap";

const initializedAt="2026-07-13T10:00:00.000Z";
function attempt(attemptId:string,state:ProductionExecutionRecoveryBootstrapAttempt["state"],primaryClassification:ProductionExecutionRecoveryBootstrapClassification,values:readonly ProductionExecutionRecoveryBootstrapClassification[],over:Partial<ProductionExecutionRecoveryBootstrapAttempt>={}):ProductionExecutionRecoveryBootstrapAttempt{return{attemptId,state,primaryClassification,classifications:values,action:primaryClassification==="terminal"?"skip-terminal":primaryClassification==="expired-lease"?"recover-expired-lease":primaryClassification==="orphaned"?"manual-recovery":primaryClassification==="running"?"wait-for-owner":"resume-through-coordinator-worker",reasonCode:"ATTEMPT_ACTIVE",attemptVersion:1,journalSequence:1,journalValid:true,versionChainValid:true,recoveryCandidate:!values.includes("terminal"),terminal:values.includes("terminal"),evidence:[`classification:${primaryClassification}`],...over}}
function bootstrap(attempts:readonly ProductionExecutionRecoveryBootstrapAttempt[]=[],decision:ProductionExecutionRecoveryBootstrapResult["decision"]="ready"):ProductionExecutionRecoveryBootstrapResult{const counts:{[K in ProductionExecutionRecoveryBootstrapClassification]:number}={active:0,running:0,terminal:0,orphaned:0,"expired-lease":0,replayable:0};for(const item of attempts)for(const value of item.classifications)counts[value]++;return{schemaVersion:"1",bootstrapId:`bootstrap-${attempts.length}-${decision}`,evaluatedAt:initializedAt,decision,writeFree:true,attempts,plannerPlans:[],counts,evidence:["bootstrap:read-only"]}}
function dependencies(projects:readonly string[],values:Readonly<Record<string,ProductionExecutionRecoveryBootstrapResult|Error>>,counters:{bootstrap:number;mutation:number}):ProductionRuntimeInitializerDependencies{return{now:()=>initializedAt,listProjectSlugs:async()=>projects,createRecoveryBootstrap:(projectSlug)=>({bootstrapRecovery:async()=>{counters.bootstrap++;const value=values[projectSlug];if(value instanceof Error)throw value;return value}})}}

async function main(){let scenarios=0;const scenario=async(name:string,run:()=>unknown|Promise<unknown>)=>{await run();scenarios++;void name};
  const cleanCounters={bootstrap:0,mutation:0},clean=new ProductionRuntimeInitializer(dependencies([],{},cleanCounters)),cleanResult=await clean.initialize();
  await scenario("clean startup",()=>{assert.equal(cleanResult.ok,true);assert.equal(cleanResult.decision,"ready");assert.deepEqual(cleanResult.projects,[])});

  const attempts=[attempt("attempt-opened","opened","active",["active","replayable"]),attempt("attempt-running","active","running",["active","running","replayable"]),attempt("attempt-orphaned","unknown","orphaned",["orphaned"],{journalValid:false,versionChainValid:false}),attempt("attempt-expired","active","expired-lease",["active","running","expired-lease","replayable"]),attempt("attempt-terminal","succeeded","terminal",["terminal"],{recoveryCandidate:false,terminal:true})],recovery=bootstrap(attempts,"recovery-required"),counters={bootstrap:0,mutation:0},initializer=new ProductionRuntimeInitializer(dependencies(["project-1"],{"project-1":recovery},counters));
  const firstPromise=initializer.initialize(),secondPromise=initializer.initialize(),result=await firstPromise;
  await scenario("active and running classifications retained",()=>{assert.equal(result.ok,true);if(!result.ok)return;assert.equal(result.counts.active,3);assert.equal(result.counts.running,2);assert.equal(result.counts.orphaned,1);assert.equal(result.counts.replayable,3)});
  await scenario("terminal attempt not planned",()=>{assert.equal(result.ok,true);if(!result.ok)return;const terminal=result.projects[0].bootstrap.attempts.find((item)=>item.terminal);assert.equal(terminal?.recoveryCandidate,false);assert.equal(result.projects[0].bootstrap.plannerPlans.length,0)});
  await scenario("expired lease remains candidate only",()=>{assert.equal(result.ok,true);if(!result.ok)return;const expired=result.projects[0].bootstrap.attempts.find((item)=>item.primaryClassification==="expired-lease");assert.equal(expired?.recoveryCandidate,true);assert.equal(expired?.action,"recover-expired-lease");assert.equal(counters.mutation,0)});
  await scenario("same-process initialization is idempotent",async()=>{assert.strictEqual(firstPromise,secondPromise);assert.strictEqual(await secondPromise,result);assert.equal(counters.bootstrap,1)});

  const invalidCounters={bootstrap:0,mutation:0},invalidBootstrap=bootstrap([],"indeterminate"),invalid=await new ProductionRuntimeInitializer(dependencies(["project-invalid"],{"project-invalid":invalidBootstrap},invalidCounters)).initialize();
  await scenario("bootstrap validation failure structured",()=>{assert.equal(invalid.ok,false);assert.equal(invalid.reasonCode,"RUNTIME_BOOTSTRAP_INVALID");assert.equal(invalid.writeFree,true)});
  const clockFailure=await new ProductionRuntimeInitializer({now:()=>{throw new Error("raw clock stack")},listProjectSlugs:async()=>[],createRecoveryBootstrap:()=>{throw new Error("unreachable")}}).initialize();
  await scenario("clock failure structured",()=>{assert.equal(clockFailure.ok,false);assert.equal(clockFailure.reasonCode,"RUNTIME_CLOCK_INVALID");assert.equal(JSON.stringify(clockFailure).includes("raw clock"),false)});
  const partialCounters={bootstrap:0,mutation:0},partial=await new ProductionRuntimeInitializer(dependencies(["project-a","project-b"],{"project-a":bootstrap(),"project-b":new Error("raw secret stack")},partialCounters)).initialize();
  await scenario("partial initialization prevented",()=>{assert.equal(partial.ok,false);assert.equal(partial.reasonCode,"RUNTIME_BOOTSTRAP_FAILED");assert.equal(partial.partialInitialization,false);assert.deepEqual(partial.projects,[]);assert.equal(JSON.stringify(partial).includes("raw secret"),false)});
  await scenario("startup remains persistence write free",async()=>{assert.equal(counters.mutation+cleanCounters.mutation+invalidCounters.mutation+partialCounters.mutation,0);assert.equal(result.writeFree,true);const source=await fs.readFile("src/lib/production/ProductionRuntimeInitializer.ts","utf8");assert.ok(!/adapter\.write|\.mutate\(|\.execute\(|remediat/i.test(source))});

  const discovery=new ProductionRuntimeInitializer({now:()=>initializedAt,listProjectSlugs:async()=>{throw new Error("secret path")},createRecoveryBootstrap:()=>{throw new Error("unreachable")}}),discoveryResult=await discovery.initialize();
  await scenario("project discovery failure structured",()=>{assert.equal(discoveryResult.ok,false);assert.equal(discoveryResult.reasonCode,"RUNTIME_PROJECT_DISCOVERY_FAILED");assert.throws(()=>{if(!discoveryResult.ok)throw new ProductionRuntimeInitializationError(discoveryResult)},(error:unknown)=>error instanceof ProductionRuntimeInitializationError&&error.message==="RUNTIME_PROJECT_DISCOVERY_FAILED")});
  await scenario("real process hook is narrow",async()=>{const hook=await fs.readFile("instrumentation.ts","utf8"),root=await fs.readFile("src/lib/runtime/ProductionRuntimeCompositionRoot.ts","utf8");assert.match(hook,/await initializeProductionProcessRuntime\(\)/);assert.ok(!/catch\s*\(/.test(hook));assert.ok(!/PipelineQueueScheduler|PipelineRunner|ProductionExecutionWorker|setInterval|setTimeout|globalThis/.test(hook+root));assert.match(root,/createRootDirectory:\s*false/)});
  assert.equal(scenarios,11);console.log(`Sprint 109 process startup bootstrap integration smoke: PASS (${scenarios}/11 scenarios)`);
}
void main();
