import type { ScriptData } from "@/types/script";

export function createAudioPrompt(script: ScriptData): string {
  return [
    "You are a professional Turkish documentary audio director.",
    "Create an audio and narration production plan from the provided documentary script.",
    "Return only valid JSON. Do not include markdown, comments, or extra text.",
    "Do not generate real audio files. Create planning metadata only.",
    "The JSON object must match this TypeScript shape:",
    "{",
    '  "narrator": {',
    '    "style": "string",',
    '    "tone": "string",',
    '    "language": "tr",',
    '    "voiceProvider": "string",',
    '    "voiceId": "string"',
    "  },",
    '  "sections": [',
    "    {",
    '      "chapterId": 1,',
    '      "title": "string",',
    '      "duration": "mm:ss",',
    '      "emotion": "string",',
    '      "emphasis": ["string"],',
    '      "narrationNotes": "string",',
    '      "pacing": "string",',
    '      "sourceText": "string"',
    "    }",
    "  ],",
    '  "music": {',
    '    "mood": "string",',
    '    "suggestion": "string",',
    '    "intensity": "string"',
    "  },",
    '  "production": {',
    '    "targetFormat": "mp3",',
    '    "sampleRate": 44100,',
    '    "estimatedTotalDuration": "mm:ss",',
    '    "generationStatus": "planned"',
    "  },",
    '  "createdAt": "string"',
    "}",
    "Rules:",
    "- Use Turkish audio direction language.",
    "- Preserve chapter order.",
    "- Use the script voiceStyle and musicStyle as guidance.",
    "- emphasis must contain the important words, names, dates, or dramatic beats.",
    "- duration must be mm:ss and close to chapter duration.",
    "- sourceText must include the narration text for future text-to-speech generation.",
    "Script JSON:",
    JSON.stringify(script),
  ].join("\n");
}
